from __future__ import annotations

import flatbuffers
import numpy as np

import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class AmrSubboxPackParams(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> AmrSubboxPackParams: ...
  @classmethod
  def GetRootAsAmrSubboxPackParams(cls, buf: bytes, offset: int) -> AmrSubboxPackParams: ...
  @classmethod
  def AmrSubboxPackParamsBufferHasIdentifier(cls, buf: bytes, offset: int, size_prefixed: bool) -> bool: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def InputField(self) -> int: ...
  def InputVersion(self) -> int: ...
  def InputStep(self) -> int: ...
  def InputLevel(self) -> int: ...
  def HaloCells(self) -> int: ...
class AmrSubboxPackParamsT(object):
  inputField: int
  inputVersion: int
  inputStep: int
  inputLevel: int
  haloCells: int
  def __init__(
    self,
    inputField: int = ...,
    inputVersion: int = ...,
    inputStep: int = ...,
    inputLevel: int = ...,
    haloCells: int = ...,
  ) -> None: ...
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> AmrSubboxPackParamsT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> AmrSubboxPackParamsT: ...
  @classmethod
  def InitFromObj(cls, amrSubboxPackParams: AmrSubboxPackParams) -> AmrSubboxPackParamsT: ...
  def _UnPack(self, amrSubboxPackParams: AmrSubboxPackParams) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def AmrSubboxPackParamsStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def AmrSubboxPackParamsAddInputField(builder: flatbuffers.Builder, inputField: int) -> None: ...
def AmrSubboxPackParamsAddInputVersion(builder: flatbuffers.Builder, inputVersion: int) -> None: ...
def AmrSubboxPackParamsAddInputStep(builder: flatbuffers.Builder, inputStep: int) -> None: ...
def AmrSubboxPackParamsAddInputLevel(builder: flatbuffers.Builder, inputLevel: int) -> None: ...
def AmrSubboxPackParamsAddHaloCells(builder: flatbuffers.Builder, haloCells: int) -> None: ...
def AmrSubboxPackParamsEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

