# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fb

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
np = import_numpy()

class AmrSubboxPackParams(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = AmrSubboxPackParams()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsAmrSubboxPackParams(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def AmrSubboxPackParamsBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x4B\x50\x4C\x4E", size_prefixed=size_prefixed)

    # AmrSubboxPackParams
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # AmrSubboxPackParams
    def InputField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return -1

    # AmrSubboxPackParams
    def InputVersion(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # AmrSubboxPackParams
    def InputStep(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # AmrSubboxPackParams
    def InputLevel(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int16Flags, o + self._tab.Pos)
        return 0

    # AmrSubboxPackParams
    def HaloCells(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 1

def AmrSubboxPackParamsStart(builder: flatbuffers.Builder):
    builder.StartObject(5)

def Start(builder: flatbuffers.Builder):
    AmrSubboxPackParamsStart(builder)

def AmrSubboxPackParamsAddInputField(builder: flatbuffers.Builder, inputField: int):
    builder.PrependInt32Slot(0, inputField, -1)

def AddInputField(builder: flatbuffers.Builder, inputField: int):
    AmrSubboxPackParamsAddInputField(builder, inputField)

def AmrSubboxPackParamsAddInputVersion(builder: flatbuffers.Builder, inputVersion: int):
    builder.PrependInt32Slot(1, inputVersion, 0)

def AddInputVersion(builder: flatbuffers.Builder, inputVersion: int):
    AmrSubboxPackParamsAddInputVersion(builder, inputVersion)

def AmrSubboxPackParamsAddInputStep(builder: flatbuffers.Builder, inputStep: int):
    builder.PrependInt32Slot(2, inputStep, 0)

def AddInputStep(builder: flatbuffers.Builder, inputStep: int):
    AmrSubboxPackParamsAddInputStep(builder, inputStep)

def AmrSubboxPackParamsAddInputLevel(builder: flatbuffers.Builder, inputLevel: int):
    builder.PrependInt16Slot(3, inputLevel, 0)

def AddInputLevel(builder: flatbuffers.Builder, inputLevel: int):
    AmrSubboxPackParamsAddInputLevel(builder, inputLevel)

def AmrSubboxPackParamsAddHaloCells(builder: flatbuffers.Builder, haloCells: int):
    builder.PrependInt32Slot(4, haloCells, 1)

def AddHaloCells(builder: flatbuffers.Builder, haloCells: int):
    AmrSubboxPackParamsAddHaloCells(builder, haloCells)

def AmrSubboxPackParamsEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return AmrSubboxPackParamsEnd(builder)


class AmrSubboxPackParamsT(object):

    # AmrSubboxPackParamsT
    def __init__(
        self,
        inputField = -1,
        inputVersion = 0,
        inputStep = 0,
        inputLevel = 0,
        haloCells = 1,
    ):
        self.inputField = inputField  # type: int
        self.inputVersion = inputVersion  # type: int
        self.inputStep = inputStep  # type: int
        self.inputLevel = inputLevel  # type: int
        self.haloCells = haloCells  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        amrSubboxPackParams = AmrSubboxPackParams()
        amrSubboxPackParams.Init(buf, pos)
        return cls.InitFromObj(amrSubboxPackParams)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, amrSubboxPackParams):
        x = AmrSubboxPackParamsT()
        x._UnPack(amrSubboxPackParams)
        return x

    # AmrSubboxPackParamsT
    def _UnPack(self, amrSubboxPackParams):
        if amrSubboxPackParams is None:
            return
        self.inputField = amrSubboxPackParams.InputField()
        self.inputVersion = amrSubboxPackParams.InputVersion()
        self.inputStep = amrSubboxPackParams.InputStep()
        self.inputLevel = amrSubboxPackParams.InputLevel()
        self.haloCells = amrSubboxPackParams.HaloCells()

    # AmrSubboxPackParamsT
    def Pack(self, builder):
        AmrSubboxPackParamsStart(builder)
        AmrSubboxPackParamsAddInputField(builder, self.inputField)
        AmrSubboxPackParamsAddInputVersion(builder, self.inputVersion)
        AmrSubboxPackParamsAddInputStep(builder, self.inputStep)
        AmrSubboxPackParamsAddInputLevel(builder, self.inputLevel)
        AmrSubboxPackParamsAddHaloCells(builder, self.haloCells)
        amrSubboxPackParams = AmrSubboxPackParamsEnd(builder)
        return amrSubboxPackParams
