from __future__ import annotations

import flatbuffers
import numpy as np

import typing
from analysis.fb.DynamicUpperBound import DynamicUpperBound, DynamicUpperBoundT
from analysis.fb.InitPolicy import InitPolicy
from analysis.fb.ScalarType import ScalarType
from analysis.fb.ShapeRuleKind import ShapeRuleKind

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class BufferSpec(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> BufferSpec: ...
  @classmethod
  def GetRootAsBufferSpec(cls, buf: bytes, offset: int) -> BufferSpec: ...
  @classmethod
  def BufferSpecBufferHasIdentifier(cls, buf: bytes, offset: int, size_prefixed: bool) -> bool: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Scalar(self) -> typing.Literal[ScalarType.Opaque, ScalarType.U8, ScalarType.I64, ScalarType.F32, ScalarType.F64]: ...
  def ShapeKind(self) -> typing.Literal[ShapeRuleKind.Block, ShapeRuleKind.Fixed, ShapeRuleKind.LikeInput, ShapeRuleKind.Dynamic]: ...
  def FixedExtents(self, i: int) -> typing.List[int]: ...
  def FixedExtentsAsNumpy(self) -> np.ndarray: ...
  def FixedExtentsLength(self) -> int: ...
  def FixedExtentsIsNone(self) -> bool: ...
  def BlockComponents(self) -> int: ...
  def LikeInputIndex(self) -> int: ...
  def DynamicUpperBound(self) -> DynamicUpperBound | None: ...
  def Init(self) -> typing.Literal[InitPolicy.Uninitialized, InitPolicy.Zero]: ...
class BufferSpecT(object):
  scalar: typing.Literal[ScalarType.Opaque, ScalarType.U8, ScalarType.I64, ScalarType.F32, ScalarType.F64]
  shapeKind: typing.Literal[ShapeRuleKind.Block, ShapeRuleKind.Fixed, ShapeRuleKind.LikeInput, ShapeRuleKind.Dynamic]
  fixedExtents: typing.List[int]
  blockComponents: int
  likeInputIndex: int
  dynamicUpperBound: DynamicUpperBoundT | None
  init: typing.Literal[InitPolicy.Uninitialized, InitPolicy.Zero]
  def __init__(
    self,
    scalar: typing.Literal[ScalarType.Opaque, ScalarType.U8, ScalarType.I64, ScalarType.F32, ScalarType.F64] = ...,
    shapeKind: typing.Literal[ShapeRuleKind.Block, ShapeRuleKind.Fixed, ShapeRuleKind.LikeInput, ShapeRuleKind.Dynamic] = ...,
    fixedExtents: typing.List[int] | None = ...,
    blockComponents: int = ...,
    likeInputIndex: int = ...,
    dynamicUpperBound: 'DynamicUpperBoundT' | None = ...,
    init: typing.Literal[InitPolicy.Uninitialized, InitPolicy.Zero] = ...,
  ) -> None: ...
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> BufferSpecT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> BufferSpecT: ...
  @classmethod
  def InitFromObj(cls, bufferSpec: BufferSpec) -> BufferSpecT: ...
  def _UnPack(self, bufferSpec: BufferSpec) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def BufferSpecStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def BufferSpecAddScalar(builder: flatbuffers.Builder, scalar: typing.Literal[ScalarType.Opaque, ScalarType.U8, ScalarType.I64, ScalarType.F32, ScalarType.F64]) -> None: ...
def BufferSpecAddShapeKind(builder: flatbuffers.Builder, shapeKind: typing.Literal[ShapeRuleKind.Block, ShapeRuleKind.Fixed, ShapeRuleKind.LikeInput, ShapeRuleKind.Dynamic]) -> None: ...
def BufferSpecAddFixedExtents(builder: flatbuffers.Builder, fixedExtents: uoffset) -> None: ...
def BufferSpecStartFixedExtentsVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartFixedExtentsVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def BufferSpecAddBlockComponents(builder: flatbuffers.Builder, blockComponents: int) -> None: ...
def BufferSpecAddLikeInputIndex(builder: flatbuffers.Builder, likeInputIndex: int) -> None: ...
def BufferSpecAddDynamicUpperBound(builder: flatbuffers.Builder, dynamicUpperBound: uoffset) -> None: ...
def BufferSpecAddInit(builder: flatbuffers.Builder, init: typing.Literal[InitPolicy.Uninitialized, InitPolicy.Zero]) -> None: ...
def BufferSpecEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

