# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fb

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from analysis.fb.DynamicUpperBound import DynamicUpperBound
from typing import Optional
np = import_numpy()

class BufferSpec(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = BufferSpec()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsBufferSpec(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def BufferSpecBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x4B\x50\x4C\x4E", size_prefixed=size_prefixed)

    # BufferSpec
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # BufferSpec
    def Scalar(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # BufferSpec
    def ShapeKind(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 1

    # BufferSpec
    def FixedExtents(self, j: int):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 8))
        return 0

    # BufferSpec
    def FixedExtentsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint64Flags, o)
        return 0

    # BufferSpec
    def FixedExtentsLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # BufferSpec
    def FixedExtentsIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

    # BufferSpec
    def BlockComponents(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 1

    # BufferSpec
    def LikeInputIndex(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return -1

    # BufferSpec
    def DynamicUpperBound(self) -> Optional[DynamicUpperBound]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = DynamicUpperBound()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # BufferSpec
    def Init(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

def BufferSpecStart(builder: flatbuffers.Builder):
    builder.StartObject(7)

def Start(builder: flatbuffers.Builder):
    BufferSpecStart(builder)

def BufferSpecAddScalar(builder: flatbuffers.Builder, scalar: int):
    builder.PrependUint8Slot(0, scalar, 0)

def AddScalar(builder: flatbuffers.Builder, scalar: int):
    BufferSpecAddScalar(builder, scalar)

def BufferSpecAddShapeKind(builder: flatbuffers.Builder, shapeKind: int):
    builder.PrependUint8Slot(1, shapeKind, 1)

def AddShapeKind(builder: flatbuffers.Builder, shapeKind: int):
    BufferSpecAddShapeKind(builder, shapeKind)

def BufferSpecAddFixedExtents(builder: flatbuffers.Builder, fixedExtents: int):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(fixedExtents), 0)

def AddFixedExtents(builder: flatbuffers.Builder, fixedExtents: int):
    BufferSpecAddFixedExtents(builder, fixedExtents)

def BufferSpecStartFixedExtentsVector(builder, numElems: int) -> int:
    return builder.StartVector(8, numElems, 8)

def StartFixedExtentsVector(builder, numElems: int) -> int:
    return BufferSpecStartFixedExtentsVector(builder, numElems)

def BufferSpecAddBlockComponents(builder: flatbuffers.Builder, blockComponents: int):
    builder.PrependUint32Slot(3, blockComponents, 1)

def AddBlockComponents(builder: flatbuffers.Builder, blockComponents: int):
    BufferSpecAddBlockComponents(builder, blockComponents)

def BufferSpecAddLikeInputIndex(builder: flatbuffers.Builder, likeInputIndex: int):
    builder.PrependInt32Slot(4, likeInputIndex, -1)

def AddLikeInputIndex(builder: flatbuffers.Builder, likeInputIndex: int):
    BufferSpecAddLikeInputIndex(builder, likeInputIndex)

def BufferSpecAddDynamicUpperBound(builder: flatbuffers.Builder, dynamicUpperBound: int):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(dynamicUpperBound), 0)

def AddDynamicUpperBound(builder: flatbuffers.Builder, dynamicUpperBound: int):
    BufferSpecAddDynamicUpperBound(builder, dynamicUpperBound)

def BufferSpecAddInit(builder: flatbuffers.Builder, init: int):
    builder.PrependUint8Slot(6, init, 0)

def AddInit(builder: flatbuffers.Builder, init: int):
    BufferSpecAddInit(builder, init)

def BufferSpecEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return BufferSpecEnd(builder)

import analysis.fb.DynamicUpperBound
try:
    from typing import List, Optional
except:
    pass

class BufferSpecT(object):

    # BufferSpecT
    def __init__(
        self,
        scalar = 0,
        shapeKind = 1,
        fixedExtents = None,
        blockComponents = 1,
        likeInputIndex = -1,
        dynamicUpperBound = None,
        init = 0,
    ):
        self.scalar = scalar  # type: int
        self.shapeKind = shapeKind  # type: int
        self.fixedExtents = fixedExtents  # type: Optional[List[int]]
        self.blockComponents = blockComponents  # type: int
        self.likeInputIndex = likeInputIndex  # type: int
        self.dynamicUpperBound = dynamicUpperBound  # type: Optional[analysis.fb.DynamicUpperBound.DynamicUpperBoundT]
        self.init = init  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        bufferSpec = BufferSpec()
        bufferSpec.Init(buf, pos)
        return cls.InitFromObj(bufferSpec)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, bufferSpec):
        x = BufferSpecT()
        x._UnPack(bufferSpec)
        return x

    # BufferSpecT
    def _UnPack(self, bufferSpec):
        if bufferSpec is None:
            return
        self.scalar = bufferSpec.Scalar()
        self.shapeKind = bufferSpec.ShapeKind()
        if not bufferSpec.FixedExtentsIsNone():
            if np is None:
                self.fixedExtents = []
                for i in range(bufferSpec.FixedExtentsLength()):
                    self.fixedExtents.append(bufferSpec.FixedExtents(i))
            else:
                self.fixedExtents = bufferSpec.FixedExtentsAsNumpy()
        self.blockComponents = bufferSpec.BlockComponents()
        self.likeInputIndex = bufferSpec.LikeInputIndex()
        if bufferSpec.DynamicUpperBound() is not None:
            self.dynamicUpperBound = analysis.fb.DynamicUpperBound.DynamicUpperBoundT.InitFromObj(bufferSpec.DynamicUpperBound())
        self.init = bufferSpec.Init()

    # BufferSpecT
    def Pack(self, builder):
        if self.fixedExtents is not None:
            if np is not None and type(self.fixedExtents) is np.ndarray:
                fixedExtents = builder.CreateNumpyVector(self.fixedExtents)
            else:
                BufferSpecStartFixedExtentsVector(builder, len(self.fixedExtents))
                for i in reversed(range(len(self.fixedExtents))):
                    builder.PrependUint64(self.fixedExtents[i])
                fixedExtents = builder.EndVector()
        if self.dynamicUpperBound is not None:
            dynamicUpperBound = self.dynamicUpperBound.Pack(builder)
        BufferSpecStart(builder)
        BufferSpecAddScalar(builder, self.scalar)
        BufferSpecAddShapeKind(builder, self.shapeKind)
        if self.fixedExtents is not None:
            BufferSpecAddFixedExtents(builder, fixedExtents)
        BufferSpecAddBlockComponents(builder, self.blockComponents)
        BufferSpecAddLikeInputIndex(builder, self.likeInputIndex)
        if self.dynamicUpperBound is not None:
            BufferSpecAddDynamicUpperBound(builder, dynamicUpperBound)
        BufferSpecAddInit(builder, self.init)
        bufferSpec = BufferSpecEnd(builder)
        return bufferSpec
