from __future__ import annotations

import flatbuffers
import numpy as np

import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class CoveredBox(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> CoveredBox: ...
  @classmethod
  def GetRootAsCoveredBox(cls, buf: bytes, offset: int) -> CoveredBox: ...
  @classmethod
  def CoveredBoxBufferHasIdentifier(cls, buf: bytes, offset: int, size_prefixed: bool) -> bool: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Lo(self, i: int) -> typing.List[int]: ...
  def LoAsNumpy(self) -> np.ndarray: ...
  def LoLength(self) -> int: ...
  def LoIsNone(self) -> bool: ...
  def Hi(self, i: int) -> typing.List[int]: ...
  def HiAsNumpy(self) -> np.ndarray: ...
  def HiLength(self) -> int: ...
  def HiIsNone(self) -> bool: ...
class CoveredBoxT(object):
  lo: typing.List[int]
  hi: typing.List[int]
  def __init__(
    self,
    lo: typing.List[int] | None = ...,
    hi: typing.List[int] | None = ...,
  ) -> None: ...
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> CoveredBoxT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> CoveredBoxT: ...
  @classmethod
  def InitFromObj(cls, coveredBox: CoveredBox) -> CoveredBoxT: ...
  def _UnPack(self, coveredBox: CoveredBox) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def CoveredBoxStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def CoveredBoxAddLo(builder: flatbuffers.Builder, lo: uoffset) -> None: ...
def CoveredBoxStartLoVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartLoVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def CoveredBoxAddHi(builder: flatbuffers.Builder, hi: uoffset) -> None: ...
def CoveredBoxStartHiVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartHiVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def CoveredBoxEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

