from __future__ import annotations

import flatbuffers
import numpy as np

import typing
from analysis.fb.CoveredBox import CoveredBox, CoveredBoxT

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class CoveredBoxList(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> CoveredBoxList: ...
  @classmethod
  def GetRootAsCoveredBoxList(cls, buf: bytes, offset: int) -> CoveredBoxList: ...
  @classmethod
  def CoveredBoxListBufferHasIdentifier(cls, buf: bytes, offset: int, size_prefixed: bool) -> bool: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Boxes(self, i: int) -> CoveredBox | None: ...
  def BoxesLength(self) -> int: ...
  def BoxesIsNone(self) -> bool: ...
class CoveredBoxListT(object):
  boxes: typing.List[CoveredBoxT]
  def __init__(
    self,
    boxes: typing.List['CoveredBoxT'] | None = ...,
  ) -> None: ...
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> CoveredBoxListT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> CoveredBoxListT: ...
  @classmethod
  def InitFromObj(cls, coveredBoxList: CoveredBoxList) -> CoveredBoxListT: ...
  def _UnPack(self, coveredBoxList: CoveredBoxList) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def CoveredBoxListStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def CoveredBoxListAddBoxes(builder: flatbuffers.Builder, boxes: uoffset) -> None: ...
def CoveredBoxListStartBoxesVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartBoxesVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def CoveredBoxListEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

