# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fb

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from analysis.fb.CoveredBox import CoveredBox
from typing import Optional
np = import_numpy()

class CoveredBoxList(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = CoveredBoxList()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsCoveredBoxList(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def CoveredBoxListBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x4B\x50\x4C\x4E", size_prefixed=size_prefixed)

    # CoveredBoxList
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # CoveredBoxList
    def Boxes(self, j: int) -> Optional[CoveredBox]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = CoveredBox()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # CoveredBoxList
    def BoxesLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # CoveredBoxList
    def BoxesIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def CoveredBoxListStart(builder: flatbuffers.Builder):
    builder.StartObject(1)

def Start(builder: flatbuffers.Builder):
    CoveredBoxListStart(builder)

def CoveredBoxListAddBoxes(builder: flatbuffers.Builder, boxes: int):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(boxes), 0)

def AddBoxes(builder: flatbuffers.Builder, boxes: int):
    CoveredBoxListAddBoxes(builder, boxes)

def CoveredBoxListStartBoxesVector(builder, numElems: int) -> int:
    return builder.StartVector(4, numElems, 4)

def StartBoxesVector(builder, numElems: int) -> int:
    return CoveredBoxListStartBoxesVector(builder, numElems)

def CoveredBoxListEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return CoveredBoxListEnd(builder)

import analysis.fb.CoveredBox
try:
    from typing import List
except:
    pass

class CoveredBoxListT(object):

    # CoveredBoxListT
    def __init__(
        self,
        boxes = None,
    ):
        self.boxes = boxes  # type: Optional[List[analysis.fb.CoveredBox.CoveredBoxT]]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        coveredBoxList = CoveredBoxList()
        coveredBoxList.Init(buf, pos)
        return cls.InitFromObj(coveredBoxList)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, coveredBoxList):
        x = CoveredBoxListT()
        x._UnPack(coveredBoxList)
        return x

    # CoveredBoxListT
    def _UnPack(self, coveredBoxList):
        if coveredBoxList is None:
            return
        if not coveredBoxList.BoxesIsNone():
            self.boxes = []
            for i in range(coveredBoxList.BoxesLength()):
                if coveredBoxList.Boxes(i) is None:
                    self.boxes.append(None)
                else:
                    coveredBox_ = analysis.fb.CoveredBox.CoveredBoxT.InitFromObj(coveredBoxList.Boxes(i))
                    self.boxes.append(coveredBox_)

    # CoveredBoxListT
    def Pack(self, builder):
        if self.boxes is not None:
            boxeslist = []
            for i in range(len(self.boxes)):
                boxeslist.append(self.boxes[i].Pack(builder))
            CoveredBoxListStartBoxesVector(builder, len(self.boxes))
            for i in reversed(range(len(self.boxes))):
                builder.PrependUOffsetTRelative(boxeslist[i])
            boxes = builder.EndVector()
        CoveredBoxListStart(builder)
        if self.boxes is not None:
            CoveredBoxListAddBoxes(builder, boxes)
        coveredBoxList = CoveredBoxListEnd(builder)
        return coveredBoxList
