# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fb

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
np = import_numpy()

class CoveredBox(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = CoveredBox()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsCoveredBox(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def CoveredBoxBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x4B\x50\x4C\x4E", size_prefixed=size_prefixed)

    # CoveredBox
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # CoveredBox
    def Lo(self, j: int):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # CoveredBox
    def LoAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # CoveredBox
    def LoLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # CoveredBox
    def LoIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

    # CoveredBox
    def Hi(self, j: int):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # CoveredBox
    def HiAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # CoveredBox
    def HiLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # CoveredBox
    def HiIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

def CoveredBoxStart(builder: flatbuffers.Builder):
    builder.StartObject(2)

def Start(builder: flatbuffers.Builder):
    CoveredBoxStart(builder)

def CoveredBoxAddLo(builder: flatbuffers.Builder, lo: int):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(lo), 0)

def AddLo(builder: flatbuffers.Builder, lo: int):
    CoveredBoxAddLo(builder, lo)

def CoveredBoxStartLoVector(builder, numElems: int) -> int:
    return builder.StartVector(4, numElems, 4)

def StartLoVector(builder, numElems: int) -> int:
    return CoveredBoxStartLoVector(builder, numElems)

def CoveredBoxAddHi(builder: flatbuffers.Builder, hi: int):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(hi), 0)

def AddHi(builder: flatbuffers.Builder, hi: int):
    CoveredBoxAddHi(builder, hi)

def CoveredBoxStartHiVector(builder, numElems: int) -> int:
    return builder.StartVector(4, numElems, 4)

def StartHiVector(builder, numElems: int) -> int:
    return CoveredBoxStartHiVector(builder, numElems)

def CoveredBoxEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return CoveredBoxEnd(builder)

try:
    from typing import List
except:
    pass

class CoveredBoxT(object):

    # CoveredBoxT
    def __init__(
        self,
        lo = None,
        hi = None,
    ):
        self.lo = lo  # type: Optional[List[int]]
        self.hi = hi  # type: Optional[List[int]]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        coveredBox = CoveredBox()
        coveredBox.Init(buf, pos)
        return cls.InitFromObj(coveredBox)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, coveredBox):
        x = CoveredBoxT()
        x._UnPack(coveredBox)
        return x

    # CoveredBoxT
    def _UnPack(self, coveredBox):
        if coveredBox is None:
            return
        if not coveredBox.LoIsNone():
            if np is None:
                self.lo = []
                for i in range(coveredBox.LoLength()):
                    self.lo.append(coveredBox.Lo(i))
            else:
                self.lo = coveredBox.LoAsNumpy()
        if not coveredBox.HiIsNone():
            if np is None:
                self.hi = []
                for i in range(coveredBox.HiLength()):
                    self.hi.append(coveredBox.Hi(i))
            else:
                self.hi = coveredBox.HiAsNumpy()

    # CoveredBoxT
    def Pack(self, builder):
        if self.lo is not None:
            if np is not None and type(self.lo) is np.ndarray:
                lo = builder.CreateNumpyVector(self.lo)
            else:
                CoveredBoxStartLoVector(builder, len(self.lo))
                for i in reversed(range(len(self.lo))):
                    builder.PrependInt32(self.lo[i])
                lo = builder.EndVector()
        if self.hi is not None:
            if np is not None and type(self.hi) is np.ndarray:
                hi = builder.CreateNumpyVector(self.hi)
            else:
                CoveredBoxStartHiVector(builder, len(self.hi))
                for i in reversed(range(len(self.hi))):
                    builder.PrependInt32(self.hi[i])
                hi = builder.EndVector()
        CoveredBoxStart(builder)
        if self.lo is not None:
            CoveredBoxAddLo(builder, lo)
        if self.hi is not None:
            CoveredBoxAddHi(builder, hi)
        coveredBox = CoveredBoxEnd(builder)
        return coveredBox
