# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fb

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
np = import_numpy()

class CylindricalFluxParams(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = CylindricalFluxParams()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsCylindricalFluxParams(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def CylindricalFluxParamsBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x4B\x50\x4C\x4E", size_prefixed=size_prefixed)

    # CylindricalFluxParams
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # CylindricalFluxParams
    def Radius(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # CylindricalFluxParams
    def Heights(self, j: int):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Float64Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 8))
        return 0

    # CylindricalFluxParams
    def HeightsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float64Flags, o)
        return 0

    # CylindricalFluxParams
    def HeightsLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # CylindricalFluxParams
    def HeightsIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

    # CylindricalFluxParams
    def HeightIndices(self, j: int):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # CylindricalFluxParams
    def HeightIndicesAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # CylindricalFluxParams
    def HeightIndicesLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # CylindricalFluxParams
    def HeightIndicesIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

    # CylindricalFluxParams
    def TemperatureBins(self, j: int):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Float64Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 8))
        return 0

    # CylindricalFluxParams
    def TemperatureBinsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float64Flags, o)
        return 0

    # CylindricalFluxParams
    def TemperatureBinsLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # CylindricalFluxParams
    def TemperatureBinsIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        return o == 0

    # CylindricalFluxParams
    def NumHeights(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # CylindricalFluxParams
    def Gamma(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 1.6666666666666667

def CylindricalFluxParamsStart(builder: flatbuffers.Builder):
    builder.StartObject(6)

def Start(builder: flatbuffers.Builder):
    CylindricalFluxParamsStart(builder)

def CylindricalFluxParamsAddRadius(builder: flatbuffers.Builder, radius: float):
    builder.PrependFloat64Slot(0, radius, 0.0)

def AddRadius(builder: flatbuffers.Builder, radius: float):
    CylindricalFluxParamsAddRadius(builder, radius)

def CylindricalFluxParamsAddHeights(builder: flatbuffers.Builder, heights: int):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(heights), 0)

def AddHeights(builder: flatbuffers.Builder, heights: int):
    CylindricalFluxParamsAddHeights(builder, heights)

def CylindricalFluxParamsStartHeightsVector(builder, numElems: int) -> int:
    return builder.StartVector(8, numElems, 8)

def StartHeightsVector(builder, numElems: int) -> int:
    return CylindricalFluxParamsStartHeightsVector(builder, numElems)

def CylindricalFluxParamsAddHeightIndices(builder: flatbuffers.Builder, heightIndices: int):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(heightIndices), 0)

def AddHeightIndices(builder: flatbuffers.Builder, heightIndices: int):
    CylindricalFluxParamsAddHeightIndices(builder, heightIndices)

def CylindricalFluxParamsStartHeightIndicesVector(builder, numElems: int) -> int:
    return builder.StartVector(4, numElems, 4)

def StartHeightIndicesVector(builder, numElems: int) -> int:
    return CylindricalFluxParamsStartHeightIndicesVector(builder, numElems)

def CylindricalFluxParamsAddTemperatureBins(builder: flatbuffers.Builder, temperatureBins: int):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(temperatureBins), 0)

def AddTemperatureBins(builder: flatbuffers.Builder, temperatureBins: int):
    CylindricalFluxParamsAddTemperatureBins(builder, temperatureBins)

def CylindricalFluxParamsStartTemperatureBinsVector(builder, numElems: int) -> int:
    return builder.StartVector(8, numElems, 8)

def StartTemperatureBinsVector(builder, numElems: int) -> int:
    return CylindricalFluxParamsStartTemperatureBinsVector(builder, numElems)

def CylindricalFluxParamsAddNumHeights(builder: flatbuffers.Builder, numHeights: int):
    builder.PrependUint64Slot(4, numHeights, 0)

def AddNumHeights(builder: flatbuffers.Builder, numHeights: int):
    CylindricalFluxParamsAddNumHeights(builder, numHeights)

def CylindricalFluxParamsAddGamma(builder: flatbuffers.Builder, gamma: float):
    builder.PrependFloat64Slot(5, gamma, 1.6666666666666667)

def AddGamma(builder: flatbuffers.Builder, gamma: float):
    CylindricalFluxParamsAddGamma(builder, gamma)

def CylindricalFluxParamsEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return CylindricalFluxParamsEnd(builder)

try:
    from typing import List
except:
    pass

class CylindricalFluxParamsT(object):

    # CylindricalFluxParamsT
    def __init__(
        self,
        radius = 0.0,
        heights = None,
        heightIndices = None,
        temperatureBins = None,
        numHeights = 0,
        gamma = 1.6666666666666667,
    ):
        self.radius = radius  # type: float
        self.heights = heights  # type: Optional[List[float]]
        self.heightIndices = heightIndices  # type: Optional[List[int]]
        self.temperatureBins = temperatureBins  # type: Optional[List[float]]
        self.numHeights = numHeights  # type: int
        self.gamma = gamma  # type: float

    @classmethod
    def InitFromBuf(cls, buf, pos):
        cylindricalFluxParams = CylindricalFluxParams()
        cylindricalFluxParams.Init(buf, pos)
        return cls.InitFromObj(cylindricalFluxParams)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, cylindricalFluxParams):
        x = CylindricalFluxParamsT()
        x._UnPack(cylindricalFluxParams)
        return x

    # CylindricalFluxParamsT
    def _UnPack(self, cylindricalFluxParams):
        if cylindricalFluxParams is None:
            return
        self.radius = cylindricalFluxParams.Radius()
        if not cylindricalFluxParams.HeightsIsNone():
            if np is None:
                self.heights = []
                for i in range(cylindricalFluxParams.HeightsLength()):
                    self.heights.append(cylindricalFluxParams.Heights(i))
            else:
                self.heights = cylindricalFluxParams.HeightsAsNumpy()
        if not cylindricalFluxParams.HeightIndicesIsNone():
            if np is None:
                self.heightIndices = []
                for i in range(cylindricalFluxParams.HeightIndicesLength()):
                    self.heightIndices.append(cylindricalFluxParams.HeightIndices(i))
            else:
                self.heightIndices = cylindricalFluxParams.HeightIndicesAsNumpy()
        if not cylindricalFluxParams.TemperatureBinsIsNone():
            if np is None:
                self.temperatureBins = []
                for i in range(cylindricalFluxParams.TemperatureBinsLength()):
                    self.temperatureBins.append(cylindricalFluxParams.TemperatureBins(i))
            else:
                self.temperatureBins = cylindricalFluxParams.TemperatureBinsAsNumpy()
        self.numHeights = cylindricalFluxParams.NumHeights()
        self.gamma = cylindricalFluxParams.Gamma()

    # CylindricalFluxParamsT
    def Pack(self, builder):
        if self.heights is not None:
            if np is not None and type(self.heights) is np.ndarray:
                heights = builder.CreateNumpyVector(self.heights)
            else:
                CylindricalFluxParamsStartHeightsVector(builder, len(self.heights))
                for i in reversed(range(len(self.heights))):
                    builder.PrependFloat64(self.heights[i])
                heights = builder.EndVector()
        if self.heightIndices is not None:
            if np is not None and type(self.heightIndices) is np.ndarray:
                heightIndices = builder.CreateNumpyVector(self.heightIndices)
            else:
                CylindricalFluxParamsStartHeightIndicesVector(builder, len(self.heightIndices))
                for i in reversed(range(len(self.heightIndices))):
                    builder.PrependInt32(self.heightIndices[i])
                heightIndices = builder.EndVector()
        if self.temperatureBins is not None:
            if np is not None and type(self.temperatureBins) is np.ndarray:
                temperatureBins = builder.CreateNumpyVector(self.temperatureBins)
            else:
                CylindricalFluxParamsStartTemperatureBinsVector(builder, len(self.temperatureBins))
                for i in reversed(range(len(self.temperatureBins))):
                    builder.PrependFloat64(self.temperatureBins[i])
                temperatureBins = builder.EndVector()
        CylindricalFluxParamsStart(builder)
        CylindricalFluxParamsAddRadius(builder, self.radius)
        if self.heights is not None:
            CylindricalFluxParamsAddHeights(builder, heights)
        if self.heightIndices is not None:
            CylindricalFluxParamsAddHeightIndices(builder, heightIndices)
        if self.temperatureBins is not None:
            CylindricalFluxParamsAddTemperatureBins(builder, temperatureBins)
        CylindricalFluxParamsAddNumHeights(builder, self.numHeights)
        CylindricalFluxParamsAddGamma(builder, self.gamma)
        cylindricalFluxParams = CylindricalFluxParamsEnd(builder)
        return cylindricalFluxParams
