from __future__ import annotations

import flatbuffers
import numpy as np

import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class CylindricalFluxParams(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> CylindricalFluxParams: ...
  @classmethod
  def GetRootAsCylindricalFluxParams(cls, buf: bytes, offset: int) -> CylindricalFluxParams: ...
  @classmethod
  def CylindricalFluxParamsBufferHasIdentifier(cls, buf: bytes, offset: int, size_prefixed: bool) -> bool: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Radius(self) -> float: ...
  def Heights(self, i: int) -> typing.List[float]: ...
  def HeightsAsNumpy(self) -> np.ndarray: ...
  def HeightsLength(self) -> int: ...
  def HeightsIsNone(self) -> bool: ...
  def HeightIndices(self, i: int) -> typing.List[int]: ...
  def HeightIndicesAsNumpy(self) -> np.ndarray: ...
  def HeightIndicesLength(self) -> int: ...
  def HeightIndicesIsNone(self) -> bool: ...
  def TemperatureBins(self, i: int) -> typing.List[float]: ...
  def TemperatureBinsAsNumpy(self) -> np.ndarray: ...
  def TemperatureBinsLength(self) -> int: ...
  def TemperatureBinsIsNone(self) -> bool: ...
  def NumHeights(self) -> int: ...
  def Gamma(self) -> float: ...
class CylindricalFluxParamsT(object):
  radius: float
  heights: typing.List[float]
  heightIndices: typing.List[int]
  temperatureBins: typing.List[float]
  numHeights: int
  gamma: float
  def __init__(
    self,
    radius: float = ...,
    heights: typing.List[float] | None = ...,
    heightIndices: typing.List[int] | None = ...,
    temperatureBins: typing.List[float] | None = ...,
    numHeights: int = ...,
    gamma: float = ...,
  ) -> None: ...
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> CylindricalFluxParamsT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> CylindricalFluxParamsT: ...
  @classmethod
  def InitFromObj(cls, cylindricalFluxParams: CylindricalFluxParams) -> CylindricalFluxParamsT: ...
  def _UnPack(self, cylindricalFluxParams: CylindricalFluxParams) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def CylindricalFluxParamsStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def CylindricalFluxParamsAddRadius(builder: flatbuffers.Builder, radius: float) -> None: ...
def CylindricalFluxParamsAddHeights(builder: flatbuffers.Builder, heights: uoffset) -> None: ...
def CylindricalFluxParamsStartHeightsVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartHeightsVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def CylindricalFluxParamsAddHeightIndices(builder: flatbuffers.Builder, heightIndices: uoffset) -> None: ...
def CylindricalFluxParamsStartHeightIndicesVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartHeightIndicesVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def CylindricalFluxParamsAddTemperatureBins(builder: flatbuffers.Builder, temperatureBins: uoffset) -> None: ...
def CylindricalFluxParamsStartTemperatureBinsVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartTemperatureBinsVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def CylindricalFluxParamsAddNumHeights(builder: flatbuffers.Builder, numHeights: int) -> None: ...
def CylindricalFluxParamsAddGamma(builder: flatbuffers.Builder, gamma: float) -> None: ...
def CylindricalFluxParamsEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

