from __future__ import annotations

import flatbuffers
import numpy as np

import typing
from analysis.fb.DepKind import DepKind

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class DependencyRule(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> DependencyRule: ...
  @classmethod
  def GetRootAsDependencyRule(cls, buf: bytes, offset: int) -> DependencyRule: ...
  @classmethod
  def DependencyRuleBufferHasIdentifier(cls, buf: bytes, offset: int, size_prefixed: bool) -> bool: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Kind(self) -> typing.Literal[DepKind.None_, DepKind.FaceNeighbors]: ...
  def Width(self) -> int: ...
  def Faces(self, i: int) -> typing.List[bool]: ...
  def FacesAsNumpy(self) -> np.ndarray: ...
  def FacesLength(self) -> int: ...
  def FacesIsNone(self) -> bool: ...
  def HaloInputs(self, i: int) -> typing.List[int]: ...
  def HaloInputsAsNumpy(self) -> np.ndarray: ...
  def HaloInputsLength(self) -> int: ...
  def HaloInputsIsNone(self) -> bool: ...
class DependencyRuleT(object):
  kind: typing.Literal[DepKind.None_, DepKind.FaceNeighbors]
  width: int
  faces: typing.List[bool]
  haloInputs: typing.List[int]
  def __init__(
    self,
    kind: typing.Literal[DepKind.None_, DepKind.FaceNeighbors] = ...,
    width: int = ...,
    faces: typing.List[bool] | None = ...,
    haloInputs: typing.List[int] | None = ...,
  ) -> None: ...
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> DependencyRuleT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> DependencyRuleT: ...
  @classmethod
  def InitFromObj(cls, dependencyRule: DependencyRule) -> DependencyRuleT: ...
  def _UnPack(self, dependencyRule: DependencyRule) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def DependencyRuleStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def DependencyRuleAddKind(builder: flatbuffers.Builder, kind: typing.Literal[DepKind.None_, DepKind.FaceNeighbors]) -> None: ...
def DependencyRuleAddWidth(builder: flatbuffers.Builder, width: int) -> None: ...
def DependencyRuleAddFaces(builder: flatbuffers.Builder, faces: uoffset) -> None: ...
def DependencyRuleStartFacesVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartFacesVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def DependencyRuleAddHaloInputs(builder: flatbuffers.Builder, haloInputs: uoffset) -> None: ...
def DependencyRuleStartHaloInputsVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartHaloInputsVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def DependencyRuleEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

