# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fb

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
np = import_numpy()

class DependencyRule(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = DependencyRule()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsDependencyRule(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def DependencyRuleBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x4B\x50\x4C\x4E", size_prefixed=size_prefixed)

    # DependencyRule
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # DependencyRule
    def Kind(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # DependencyRule
    def Width(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # DependencyRule
    def Faces(self, j: int):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.BoolFlags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # DependencyRule
    def FacesAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.BoolFlags, o)
        return 0

    # DependencyRule
    def FacesLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # DependencyRule
    def FacesIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

    # DependencyRule
    def HaloInputs(self, j: int):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # DependencyRule
    def HaloInputsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # DependencyRule
    def HaloInputsLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # DependencyRule
    def HaloInputsIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        return o == 0

def DependencyRuleStart(builder: flatbuffers.Builder):
    builder.StartObject(4)

def Start(builder: flatbuffers.Builder):
    DependencyRuleStart(builder)

def DependencyRuleAddKind(builder: flatbuffers.Builder, kind: int):
    builder.PrependUint8Slot(0, kind, 0)

def AddKind(builder: flatbuffers.Builder, kind: int):
    DependencyRuleAddKind(builder, kind)

def DependencyRuleAddWidth(builder: flatbuffers.Builder, width: int):
    builder.PrependInt32Slot(1, width, 0)

def AddWidth(builder: flatbuffers.Builder, width: int):
    DependencyRuleAddWidth(builder, width)

def DependencyRuleAddFaces(builder: flatbuffers.Builder, faces: int):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(faces), 0)

def AddFaces(builder: flatbuffers.Builder, faces: int):
    DependencyRuleAddFaces(builder, faces)

def DependencyRuleStartFacesVector(builder, numElems: int) -> int:
    return builder.StartVector(1, numElems, 1)

def StartFacesVector(builder, numElems: int) -> int:
    return DependencyRuleStartFacesVector(builder, numElems)

def DependencyRuleAddHaloInputs(builder: flatbuffers.Builder, haloInputs: int):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(haloInputs), 0)

def AddHaloInputs(builder: flatbuffers.Builder, haloInputs: int):
    DependencyRuleAddHaloInputs(builder, haloInputs)

def DependencyRuleStartHaloInputsVector(builder, numElems: int) -> int:
    return builder.StartVector(4, numElems, 4)

def StartHaloInputsVector(builder, numElems: int) -> int:
    return DependencyRuleStartHaloInputsVector(builder, numElems)

def DependencyRuleEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return DependencyRuleEnd(builder)

try:
    from typing import List
except:
    pass

class DependencyRuleT(object):

    # DependencyRuleT
    def __init__(
        self,
        kind = 0,
        width = 0,
        faces = None,
        haloInputs = None,
    ):
        self.kind = kind  # type: int
        self.width = width  # type: int
        self.faces = faces  # type: Optional[List[bool]]
        self.haloInputs = haloInputs  # type: Optional[List[int]]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        dependencyRule = DependencyRule()
        dependencyRule.Init(buf, pos)
        return cls.InitFromObj(dependencyRule)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, dependencyRule):
        x = DependencyRuleT()
        x._UnPack(dependencyRule)
        return x

    # DependencyRuleT
    def _UnPack(self, dependencyRule):
        if dependencyRule is None:
            return
        self.kind = dependencyRule.Kind()
        self.width = dependencyRule.Width()
        if not dependencyRule.FacesIsNone():
            if np is None:
                self.faces = []
                for i in range(dependencyRule.FacesLength()):
                    self.faces.append(dependencyRule.Faces(i))
            else:
                self.faces = dependencyRule.FacesAsNumpy()
        if not dependencyRule.HaloInputsIsNone():
            if np is None:
                self.haloInputs = []
                for i in range(dependencyRule.HaloInputsLength()):
                    self.haloInputs.append(dependencyRule.HaloInputs(i))
            else:
                self.haloInputs = dependencyRule.HaloInputsAsNumpy()

    # DependencyRuleT
    def Pack(self, builder):
        if self.faces is not None:
            if np is not None and type(self.faces) is np.ndarray:
                faces = builder.CreateNumpyVector(self.faces)
            else:
                DependencyRuleStartFacesVector(builder, len(self.faces))
                for i in reversed(range(len(self.faces))):
                    builder.PrependBool(self.faces[i])
                faces = builder.EndVector()
        if self.haloInputs is not None:
            if np is not None and type(self.haloInputs) is np.ndarray:
                haloInputs = builder.CreateNumpyVector(self.haloInputs)
            else:
                DependencyRuleStartHaloInputsVector(builder, len(self.haloInputs))
                for i in reversed(range(len(self.haloInputs))):
                    builder.PrependInt32(self.haloInputs[i])
                haloInputs = builder.EndVector()
        DependencyRuleStart(builder)
        DependencyRuleAddKind(builder, self.kind)
        DependencyRuleAddWidth(builder, self.width)
        if self.faces is not None:
            DependencyRuleAddFaces(builder, faces)
        if self.haloInputs is not None:
            DependencyRuleAddHaloInputs(builder, haloInputs)
        dependencyRule = DependencyRuleEnd(builder)
        return dependencyRule
