# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fb

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
np = import_numpy()

class Domain(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Domain()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsDomain(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def DomainBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x4B\x50\x4C\x4E", size_prefixed=size_prefixed)

    # Domain
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Domain
    def Step(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Domain
    def Level(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int16Flags, o + self._tab.Pos)
        return 0

    # Domain
    def Blocks(self, j: int):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # Domain
    def BlocksAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # Domain
    def BlocksLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Domain
    def BlocksIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

    # Domain
    def AllBlocks(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return True

def DomainStart(builder: flatbuffers.Builder):
    builder.StartObject(4)

def Start(builder: flatbuffers.Builder):
    DomainStart(builder)

def DomainAddStep(builder: flatbuffers.Builder, step: int):
    builder.PrependInt32Slot(0, step, 0)

def AddStep(builder: flatbuffers.Builder, step: int):
    DomainAddStep(builder, step)

def DomainAddLevel(builder: flatbuffers.Builder, level: int):
    builder.PrependInt16Slot(1, level, 0)

def AddLevel(builder: flatbuffers.Builder, level: int):
    DomainAddLevel(builder, level)

def DomainAddBlocks(builder: flatbuffers.Builder, blocks: int):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(blocks), 0)

def AddBlocks(builder: flatbuffers.Builder, blocks: int):
    DomainAddBlocks(builder, blocks)

def DomainStartBlocksVector(builder, numElems: int) -> int:
    return builder.StartVector(4, numElems, 4)

def StartBlocksVector(builder, numElems: int) -> int:
    return DomainStartBlocksVector(builder, numElems)

def DomainAddAllBlocks(builder: flatbuffers.Builder, allBlocks: bool):
    builder.PrependBoolSlot(3, allBlocks, 1)

def AddAllBlocks(builder: flatbuffers.Builder, allBlocks: bool):
    DomainAddAllBlocks(builder, allBlocks)

def DomainEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return DomainEnd(builder)

try:
    from typing import List
except:
    pass

class DomainT(object):

    # DomainT
    def __init__(
        self,
        step = 0,
        level = 0,
        blocks = None,
        allBlocks = True,
    ):
        self.step = step  # type: int
        self.level = level  # type: int
        self.blocks = blocks  # type: Optional[List[int]]
        self.allBlocks = allBlocks  # type: bool

    @classmethod
    def InitFromBuf(cls, buf, pos):
        domain = Domain()
        domain.Init(buf, pos)
        return cls.InitFromObj(domain)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, domain):
        x = DomainT()
        x._UnPack(domain)
        return x

    # DomainT
    def _UnPack(self, domain):
        if domain is None:
            return
        self.step = domain.Step()
        self.level = domain.Level()
        if not domain.BlocksIsNone():
            if np is None:
                self.blocks = []
                for i in range(domain.BlocksLength()):
                    self.blocks.append(domain.Blocks(i))
            else:
                self.blocks = domain.BlocksAsNumpy()
        self.allBlocks = domain.AllBlocks()

    # DomainT
    def Pack(self, builder):
        if self.blocks is not None:
            if np is not None and type(self.blocks) is np.ndarray:
                blocks = builder.CreateNumpyVector(self.blocks)
            else:
                DomainStartBlocksVector(builder, len(self.blocks))
                for i in reversed(range(len(self.blocks))):
                    builder.PrependInt32(self.blocks[i])
                blocks = builder.EndVector()
        DomainStart(builder)
        DomainAddStep(builder, self.step)
        DomainAddLevel(builder, self.level)
        if self.blocks is not None:
            DomainAddBlocks(builder, blocks)
        DomainAddAllBlocks(builder, self.allBlocks)
        domain = DomainEnd(builder)
        return domain
