from __future__ import annotations

import flatbuffers
import numpy as np

import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Domain(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Domain: ...
  @classmethod
  def GetRootAsDomain(cls, buf: bytes, offset: int) -> Domain: ...
  @classmethod
  def DomainBufferHasIdentifier(cls, buf: bytes, offset: int, size_prefixed: bool) -> bool: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Step(self) -> int: ...
  def Level(self) -> int: ...
  def Blocks(self, i: int) -> typing.List[int]: ...
  def BlocksAsNumpy(self) -> np.ndarray: ...
  def BlocksLength(self) -> int: ...
  def BlocksIsNone(self) -> bool: ...
  def AllBlocks(self) -> bool: ...
class DomainT(object):
  step: int
  level: int
  blocks: typing.List[int]
  allBlocks: bool
  def __init__(
    self,
    step: int = ...,
    level: int = ...,
    blocks: typing.List[int] | None = ...,
    allBlocks: bool = ...,
  ) -> None: ...
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> DomainT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> DomainT: ...
  @classmethod
  def InitFromObj(cls, domain: Domain) -> DomainT: ...
  def _UnPack(self, domain: Domain) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def DomainStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def DomainAddStep(builder: flatbuffers.Builder, step: int) -> None: ...
def DomainAddLevel(builder: flatbuffers.Builder, level: int) -> None: ...
def DomainAddBlocks(builder: flatbuffers.Builder, blocks: uoffset) -> None: ...
def DomainStartBlocksVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartBlocksVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def DomainAddAllBlocks(builder: flatbuffers.Builder, allBlocks: bool) -> None: ...
def DomainEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

