from __future__ import annotations

import flatbuffers
import numpy as np

import typing
from analysis.fb.DynamicUpperBoundKind import DynamicUpperBoundKind

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class DynamicUpperBound(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> DynamicUpperBound: ...
  @classmethod
  def GetRootAsDynamicUpperBound(cls, buf: bytes, offset: int) -> DynamicUpperBound: ...
  @classmethod
  def DynamicUpperBoundBufferHasIdentifier(cls, buf: bytes, offset: int, size_prefixed: bool) -> bool: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Kind(self) -> typing.Literal[DynamicUpperBoundKind.Literal, DynamicUpperBoundKind.LikeInput, DynamicUpperBoundKind.BackendChunk, DynamicUpperBoundKind.AmrSubboxPack]: ...
  def Value(self) -> int: ...
  def InputIndex(self) -> int: ...
class DynamicUpperBoundT(object):
  kind: typing.Literal[DynamicUpperBoundKind.Literal, DynamicUpperBoundKind.LikeInput, DynamicUpperBoundKind.BackendChunk, DynamicUpperBoundKind.AmrSubboxPack]
  value: int
  inputIndex: int
  def __init__(
    self,
    kind: typing.Literal[DynamicUpperBoundKind.Literal, DynamicUpperBoundKind.LikeInput, DynamicUpperBoundKind.BackendChunk, DynamicUpperBoundKind.AmrSubboxPack] = ...,
    value: int = ...,
    inputIndex: int = ...,
  ) -> None: ...
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> DynamicUpperBoundT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> DynamicUpperBoundT: ...
  @classmethod
  def InitFromObj(cls, dynamicUpperBound: DynamicUpperBound) -> DynamicUpperBoundT: ...
  def _UnPack(self, dynamicUpperBound: DynamicUpperBound) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def DynamicUpperBoundStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def DynamicUpperBoundAddKind(builder: flatbuffers.Builder, kind: typing.Literal[DynamicUpperBoundKind.Literal, DynamicUpperBoundKind.LikeInput, DynamicUpperBoundKind.BackendChunk, DynamicUpperBoundKind.AmrSubboxPack]) -> None: ...
def DynamicUpperBoundAddValue(builder: flatbuffers.Builder, value: int) -> None: ...
def DynamicUpperBoundAddInputIndex(builder: flatbuffers.Builder, inputIndex: int) -> None: ...
def DynamicUpperBoundEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

