# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fb

class DynamicUpperBoundKind(object):
    Literal = 0
    LikeInput = 1
    BackendChunk = 2
    AmrSubboxPack = 3
