# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fb

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
np = import_numpy()

class DynamicUpperBound(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = DynamicUpperBound()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsDynamicUpperBound(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def DynamicUpperBoundBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x4B\x50\x4C\x4E", size_prefixed=size_prefixed)

    # DynamicUpperBound
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # DynamicUpperBound
    def Kind(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # DynamicUpperBound
    def Value(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # DynamicUpperBound
    def InputIndex(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return -1

def DynamicUpperBoundStart(builder: flatbuffers.Builder):
    builder.StartObject(3)

def Start(builder: flatbuffers.Builder):
    DynamicUpperBoundStart(builder)

def DynamicUpperBoundAddKind(builder: flatbuffers.Builder, kind: int):
    builder.PrependUint8Slot(0, kind, 0)

def AddKind(builder: flatbuffers.Builder, kind: int):
    DynamicUpperBoundAddKind(builder, kind)

def DynamicUpperBoundAddValue(builder: flatbuffers.Builder, value: int):
    builder.PrependUint64Slot(1, value, 0)

def AddValue(builder: flatbuffers.Builder, value: int):
    DynamicUpperBoundAddValue(builder, value)

def DynamicUpperBoundAddInputIndex(builder: flatbuffers.Builder, inputIndex: int):
    builder.PrependInt32Slot(2, inputIndex, -1)

def AddInputIndex(builder: flatbuffers.Builder, inputIndex: int):
    DynamicUpperBoundAddInputIndex(builder, inputIndex)

def DynamicUpperBoundEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return DynamicUpperBoundEnd(builder)


class DynamicUpperBoundT(object):

    # DynamicUpperBoundT
    def __init__(
        self,
        kind = 0,
        value = 0,
        inputIndex = -1,
    ):
        self.kind = kind  # type: int
        self.value = value  # type: int
        self.inputIndex = inputIndex  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        dynamicUpperBound = DynamicUpperBound()
        dynamicUpperBound.Init(buf, pos)
        return cls.InitFromObj(dynamicUpperBound)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, dynamicUpperBound):
        x = DynamicUpperBoundT()
        x._UnPack(dynamicUpperBound)
        return x

    # DynamicUpperBoundT
    def _UnPack(self, dynamicUpperBound):
        if dynamicUpperBound is None:
            return
        self.kind = dynamicUpperBound.Kind()
        self.value = dynamicUpperBound.Value()
        self.inputIndex = dynamicUpperBound.InputIndex()

    # DynamicUpperBoundT
    def Pack(self, builder):
        DynamicUpperBoundStart(builder)
        DynamicUpperBoundAddKind(builder, self.kind)
        DynamicUpperBoundAddValue(builder, self.value)
        DynamicUpperBoundAddInputIndex(builder, self.inputIndex)
        dynamicUpperBound = DynamicUpperBoundEnd(builder)
        return dynamicUpperBound
