# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fb

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from analysis.fb.Domain import Domain
from typing import Optional
np = import_numpy()

class FieldRef(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = FieldRef()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsFieldRef(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def FieldRefBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x4B\x50\x4C\x4E", size_prefixed=size_prefixed)

    # FieldRef
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # FieldRef
    def Field(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # FieldRef
    def Version(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # FieldRef
    def Domain(self) -> Optional[Domain]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = Domain()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def FieldRefStart(builder: flatbuffers.Builder):
    builder.StartObject(3)

def Start(builder: flatbuffers.Builder):
    FieldRefStart(builder)

def FieldRefAddField(builder: flatbuffers.Builder, field: int):
    builder.PrependInt32Slot(0, field, 0)

def AddField(builder: flatbuffers.Builder, field: int):
    FieldRefAddField(builder, field)

def FieldRefAddVersion(builder: flatbuffers.Builder, version: int):
    builder.PrependInt32Slot(1, version, 0)

def AddVersion(builder: flatbuffers.Builder, version: int):
    FieldRefAddVersion(builder, version)

def FieldRefAddDomain(builder: flatbuffers.Builder, domain: int):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(domain), 0)

def AddDomain(builder: flatbuffers.Builder, domain: int):
    FieldRefAddDomain(builder, domain)

def FieldRefEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return FieldRefEnd(builder)

import analysis.fb.Domain
try:
    from typing import Optional
except:
    pass

class FieldRefT(object):

    # FieldRefT
    def __init__(
        self,
        field = 0,
        version = 0,
        domain = None,
    ):
        self.field = field  # type: int
        self.version = version  # type: int
        self.domain = domain  # type: Optional[analysis.fb.Domain.DomainT]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        fieldRef = FieldRef()
        fieldRef.Init(buf, pos)
        return cls.InitFromObj(fieldRef)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, fieldRef):
        x = FieldRefT()
        x._UnPack(fieldRef)
        return x

    # FieldRefT
    def _UnPack(self, fieldRef):
        if fieldRef is None:
            return
        self.field = fieldRef.Field()
        self.version = fieldRef.Version()
        if fieldRef.Domain() is not None:
            self.domain = analysis.fb.Domain.DomainT.InitFromObj(fieldRef.Domain())

    # FieldRefT
    def Pack(self, builder):
        if self.domain is not None:
            domain = self.domain.Pack(builder)
        FieldRefStart(builder)
        FieldRefAddField(builder, self.field)
        FieldRefAddVersion(builder, self.version)
        if self.domain is not None:
            FieldRefAddDomain(builder, domain)
        fieldRef = FieldRefEnd(builder)
        return fieldRef
