from __future__ import annotations

import flatbuffers
import numpy as np

import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class FieldExprParams(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> FieldExprParams: ...
  @classmethod
  def GetRootAsFieldExprParams(cls, buf: bytes, offset: int) -> FieldExprParams: ...
  @classmethod
  def FieldExprParamsBufferHasIdentifier(cls, buf: bytes, offset: int, size_prefixed: bool) -> bool: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Expression(self) -> str | None: ...
  def Variables(self, i: int) -> str: ...
  def VariablesLength(self) -> int: ...
  def VariablesIsNone(self) -> bool: ...
class FieldExprParamsT(object):
  expression: str | None
  variables: typing.List[str]
  def __init__(
    self,
    expression: str | None = ...,
    variables: typing.List[str] | None = ...,
  ) -> None: ...
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> FieldExprParamsT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> FieldExprParamsT: ...
  @classmethod
  def InitFromObj(cls, fieldExprParams: FieldExprParams) -> FieldExprParamsT: ...
  def _UnPack(self, fieldExprParams: FieldExprParams) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def FieldExprParamsStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def FieldExprParamsAddExpression(builder: flatbuffers.Builder, expression: uoffset) -> None: ...
def FieldExprParamsAddVariables(builder: flatbuffers.Builder, variables: uoffset) -> None: ...
def FieldExprParamsStartVariablesVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartVariablesVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def FieldExprParamsEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

