from __future__ import annotations

import flatbuffers
import numpy as np

import typing
from analysis.fb.Domain import Domain, DomainT

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class FieldRef(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> FieldRef: ...
  @classmethod
  def GetRootAsFieldRef(cls, buf: bytes, offset: int) -> FieldRef: ...
  @classmethod
  def FieldRefBufferHasIdentifier(cls, buf: bytes, offset: int, size_prefixed: bool) -> bool: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Field(self) -> int: ...
  def Version(self) -> int: ...
  def Domain(self) -> Domain | None: ...
class FieldRefT(object):
  field: int
  version: int
  domain: DomainT | None
  def __init__(
    self,
    field: int = ...,
    version: int = ...,
    domain: 'DomainT' | None = ...,
  ) -> None: ...
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> FieldRefT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> FieldRefT: ...
  @classmethod
  def InitFromObj(cls, fieldRef: FieldRef) -> FieldRefT: ...
  def _UnPack(self, fieldRef: FieldRef) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def FieldRefStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def FieldRefAddField(builder: flatbuffers.Builder, field: int) -> None: ...
def FieldRefAddVersion(builder: flatbuffers.Builder, version: int) -> None: ...
def FieldRefAddDomain(builder: flatbuffers.Builder, domain: uoffset) -> None: ...
def FieldRefEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

