# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fb

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from typing import Optional
np = import_numpy()

class FieldExprParams(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = FieldExprParams()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsFieldExprParams(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def FieldExprParamsBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x4B\x50\x4C\x4E", size_prefixed=size_prefixed)

    # FieldExprParams
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # FieldExprParams
    def Expression(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # FieldExprParams
    def Variables(self, j: int):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.String(a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return ""

    # FieldExprParams
    def VariablesLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # FieldExprParams
    def VariablesIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

def FieldExprParamsStart(builder: flatbuffers.Builder):
    builder.StartObject(2)

def Start(builder: flatbuffers.Builder):
    FieldExprParamsStart(builder)

def FieldExprParamsAddExpression(builder: flatbuffers.Builder, expression: int):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(expression), 0)

def AddExpression(builder: flatbuffers.Builder, expression: int):
    FieldExprParamsAddExpression(builder, expression)

def FieldExprParamsAddVariables(builder: flatbuffers.Builder, variables: int):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(variables), 0)

def AddVariables(builder: flatbuffers.Builder, variables: int):
    FieldExprParamsAddVariables(builder, variables)

def FieldExprParamsStartVariablesVector(builder, numElems: int) -> int:
    return builder.StartVector(4, numElems, 4)

def StartVariablesVector(builder, numElems: int) -> int:
    return FieldExprParamsStartVariablesVector(builder, numElems)

def FieldExprParamsEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return FieldExprParamsEnd(builder)

try:
    from typing import List
except:
    pass

class FieldExprParamsT(object):

    # FieldExprParamsT
    def __init__(
        self,
        expression = None,
        variables = None,
    ):
        self.expression = expression  # type: Optional[str]
        self.variables = variables  # type: Optional[List[Optional[str]]]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        fieldExprParams = FieldExprParams()
        fieldExprParams.Init(buf, pos)
        return cls.InitFromObj(fieldExprParams)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, fieldExprParams):
        x = FieldExprParamsT()
        x._UnPack(fieldExprParams)
        return x

    # FieldExprParamsT
    def _UnPack(self, fieldExprParams):
        if fieldExprParams is None:
            return
        self.expression = fieldExprParams.Expression()
        if not fieldExprParams.VariablesIsNone():
            self.variables = []
            for i in range(fieldExprParams.VariablesLength()):
                self.variables.append(fieldExprParams.Variables(i))

    # FieldExprParamsT
    def Pack(self, builder):
        if self.expression is not None:
            expression = builder.CreateString(self.expression)
        if self.variables is not None:
            variableslist = []
            for i in range(len(self.variables)):
                variableslist.append(builder.CreateString(self.variables[i]))
            FieldExprParamsStartVariablesVector(builder, len(self.variables))
            for i in reversed(range(len(self.variables))):
                builder.PrependUOffsetTRelative(variableslist[i])
            variables = builder.EndVector()
        FieldExprParamsStart(builder)
        if self.expression is not None:
            FieldExprParamsAddExpression(builder, expression)
        if self.variables is not None:
            FieldExprParamsAddVariables(builder, variables)
        fieldExprParams = FieldExprParamsEnd(builder)
        return fieldExprParams
