from __future__ import annotations

import flatbuffers
import numpy as np

import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class FiniteOnlyParams(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> FiniteOnlyParams: ...
  @classmethod
  def GetRootAsFiniteOnlyParams(cls, buf: bytes, offset: int) -> FiniteOnlyParams: ...
  @classmethod
  def FiniteOnlyParamsBufferHasIdentifier(cls, buf: bytes, offset: int, size_prefixed: bool) -> bool: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def FiniteOnly(self) -> bool: ...
class FiniteOnlyParamsT(object):
  finiteOnly: bool
  def __init__(
    self,
    finiteOnly: bool = ...,
  ) -> None: ...
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> FiniteOnlyParamsT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> FiniteOnlyParamsT: ...
  @classmethod
  def InitFromObj(cls, finiteOnlyParams: FiniteOnlyParams) -> FiniteOnlyParamsT: ...
  def _UnPack(self, finiteOnlyParams: FiniteOnlyParams) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def FiniteOnlyParamsStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def FiniteOnlyParamsAddFiniteOnly(builder: flatbuffers.Builder, finiteOnly: bool) -> None: ...
def FiniteOnlyParamsEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

