# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fb

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
np = import_numpy()

class FiniteOnlyParams(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = FiniteOnlyParams()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsFiniteOnlyParams(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def FiniteOnlyParamsBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x4B\x50\x4C\x4E", size_prefixed=size_prefixed)

    # FiniteOnlyParams
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # FiniteOnlyParams
    def FiniteOnly(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return True

def FiniteOnlyParamsStart(builder: flatbuffers.Builder):
    builder.StartObject(1)

def Start(builder: flatbuffers.Builder):
    FiniteOnlyParamsStart(builder)

def FiniteOnlyParamsAddFiniteOnly(builder: flatbuffers.Builder, finiteOnly: bool):
    builder.PrependBoolSlot(0, finiteOnly, 1)

def AddFiniteOnly(builder: flatbuffers.Builder, finiteOnly: bool):
    FiniteOnlyParamsAddFiniteOnly(builder, finiteOnly)

def FiniteOnlyParamsEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return FiniteOnlyParamsEnd(builder)


class FiniteOnlyParamsT(object):

    # FiniteOnlyParamsT
    def __init__(
        self,
        finiteOnly = True,
    ):
        self.finiteOnly = finiteOnly  # type: bool

    @classmethod
    def InitFromBuf(cls, buf, pos):
        finiteOnlyParams = FiniteOnlyParams()
        finiteOnlyParams.Init(buf, pos)
        return cls.InitFromObj(finiteOnlyParams)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, finiteOnlyParams):
        x = FiniteOnlyParamsT()
        x._UnPack(finiteOnlyParams)
        return x

    # FiniteOnlyParamsT
    def _UnPack(self, finiteOnlyParams):
        if finiteOnlyParams is None:
            return
        self.finiteOnly = finiteOnlyParams.FiniteOnly()

    # FiniteOnlyParamsT
    def Pack(self, builder):
        FiniteOnlyParamsStart(builder)
        FiniteOnlyParamsAddFiniteOnly(builder, self.finiteOnly)
        finiteOnlyParams = FiniteOnlyParamsEnd(builder)
        return finiteOnlyParams
