from __future__ import annotations

import flatbuffers
import numpy as np

import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class FluxSurfaceParams(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> FluxSurfaceParams: ...
  @classmethod
  def GetRootAsFluxSurfaceParams(cls, buf: bytes, offset: int) -> FluxSurfaceParams: ...
  @classmethod
  def FluxSurfaceParamsBufferHasIdentifier(cls, buf: bytes, offset: int, size_prefixed: bool) -> bool: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Radii(self, i: int) -> typing.List[float]: ...
  def RadiiAsNumpy(self) -> np.ndarray: ...
  def RadiiLength(self) -> int: ...
  def RadiiIsNone(self) -> bool: ...
  def RadiusIndices(self, i: int) -> typing.List[int]: ...
  def RadiusIndicesAsNumpy(self) -> np.ndarray: ...
  def RadiusIndicesLength(self) -> int: ...
  def RadiusIndicesIsNone(self) -> bool: ...
  def TemperatureBins(self, i: int) -> typing.List[float]: ...
  def TemperatureBinsAsNumpy(self) -> np.ndarray: ...
  def TemperatureBinsLength(self) -> int: ...
  def TemperatureBinsIsNone(self) -> bool: ...
  def NumRadii(self) -> int: ...
  def Gamma(self) -> float: ...
class FluxSurfaceParamsT(object):
  radii: typing.List[float]
  radiusIndices: typing.List[int]
  temperatureBins: typing.List[float]
  numRadii: int
  gamma: float
  def __init__(
    self,
    radii: typing.List[float] | None = ...,
    radiusIndices: typing.List[int] | None = ...,
    temperatureBins: typing.List[float] | None = ...,
    numRadii: int = ...,
    gamma: float = ...,
  ) -> None: ...
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> FluxSurfaceParamsT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> FluxSurfaceParamsT: ...
  @classmethod
  def InitFromObj(cls, fluxSurfaceParams: FluxSurfaceParams) -> FluxSurfaceParamsT: ...
  def _UnPack(self, fluxSurfaceParams: FluxSurfaceParams) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def FluxSurfaceParamsStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def FluxSurfaceParamsAddRadii(builder: flatbuffers.Builder, radii: uoffset) -> None: ...
def FluxSurfaceParamsStartRadiiVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartRadiiVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def FluxSurfaceParamsAddRadiusIndices(builder: flatbuffers.Builder, radiusIndices: uoffset) -> None: ...
def FluxSurfaceParamsStartRadiusIndicesVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartRadiusIndicesVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def FluxSurfaceParamsAddTemperatureBins(builder: flatbuffers.Builder, temperatureBins: uoffset) -> None: ...
def FluxSurfaceParamsStartTemperatureBinsVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartTemperatureBinsVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def FluxSurfaceParamsAddNumRadii(builder: flatbuffers.Builder, numRadii: int) -> None: ...
def FluxSurfaceParamsAddGamma(builder: flatbuffers.Builder, gamma: float) -> None: ...
def FluxSurfaceParamsEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

