# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fb

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
np = import_numpy()

class FluxSurfaceParams(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = FluxSurfaceParams()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsFluxSurfaceParams(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def FluxSurfaceParamsBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x4B\x50\x4C\x4E", size_prefixed=size_prefixed)

    # FluxSurfaceParams
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # FluxSurfaceParams
    def Radii(self, j: int):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Float64Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 8))
        return 0

    # FluxSurfaceParams
    def RadiiAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float64Flags, o)
        return 0

    # FluxSurfaceParams
    def RadiiLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # FluxSurfaceParams
    def RadiiIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

    # FluxSurfaceParams
    def RadiusIndices(self, j: int):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # FluxSurfaceParams
    def RadiusIndicesAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # FluxSurfaceParams
    def RadiusIndicesLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # FluxSurfaceParams
    def RadiusIndicesIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

    # FluxSurfaceParams
    def TemperatureBins(self, j: int):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Float64Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 8))
        return 0

    # FluxSurfaceParams
    def TemperatureBinsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float64Flags, o)
        return 0

    # FluxSurfaceParams
    def TemperatureBinsLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # FluxSurfaceParams
    def TemperatureBinsIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

    # FluxSurfaceParams
    def NumRadii(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # FluxSurfaceParams
    def Gamma(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 1.6666666666666667

def FluxSurfaceParamsStart(builder: flatbuffers.Builder):
    builder.StartObject(5)

def Start(builder: flatbuffers.Builder):
    FluxSurfaceParamsStart(builder)

def FluxSurfaceParamsAddRadii(builder: flatbuffers.Builder, radii: int):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(radii), 0)

def AddRadii(builder: flatbuffers.Builder, radii: int):
    FluxSurfaceParamsAddRadii(builder, radii)

def FluxSurfaceParamsStartRadiiVector(builder, numElems: int) -> int:
    return builder.StartVector(8, numElems, 8)

def StartRadiiVector(builder, numElems: int) -> int:
    return FluxSurfaceParamsStartRadiiVector(builder, numElems)

def FluxSurfaceParamsAddRadiusIndices(builder: flatbuffers.Builder, radiusIndices: int):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(radiusIndices), 0)

def AddRadiusIndices(builder: flatbuffers.Builder, radiusIndices: int):
    FluxSurfaceParamsAddRadiusIndices(builder, radiusIndices)

def FluxSurfaceParamsStartRadiusIndicesVector(builder, numElems: int) -> int:
    return builder.StartVector(4, numElems, 4)

def StartRadiusIndicesVector(builder, numElems: int) -> int:
    return FluxSurfaceParamsStartRadiusIndicesVector(builder, numElems)

def FluxSurfaceParamsAddTemperatureBins(builder: flatbuffers.Builder, temperatureBins: int):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(temperatureBins), 0)

def AddTemperatureBins(builder: flatbuffers.Builder, temperatureBins: int):
    FluxSurfaceParamsAddTemperatureBins(builder, temperatureBins)

def FluxSurfaceParamsStartTemperatureBinsVector(builder, numElems: int) -> int:
    return builder.StartVector(8, numElems, 8)

def StartTemperatureBinsVector(builder, numElems: int) -> int:
    return FluxSurfaceParamsStartTemperatureBinsVector(builder, numElems)

def FluxSurfaceParamsAddNumRadii(builder: flatbuffers.Builder, numRadii: int):
    builder.PrependUint64Slot(3, numRadii, 0)

def AddNumRadii(builder: flatbuffers.Builder, numRadii: int):
    FluxSurfaceParamsAddNumRadii(builder, numRadii)

def FluxSurfaceParamsAddGamma(builder: flatbuffers.Builder, gamma: float):
    builder.PrependFloat64Slot(4, gamma, 1.6666666666666667)

def AddGamma(builder: flatbuffers.Builder, gamma: float):
    FluxSurfaceParamsAddGamma(builder, gamma)

def FluxSurfaceParamsEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return FluxSurfaceParamsEnd(builder)

try:
    from typing import List
except:
    pass

class FluxSurfaceParamsT(object):

    # FluxSurfaceParamsT
    def __init__(
        self,
        radii = None,
        radiusIndices = None,
        temperatureBins = None,
        numRadii = 0,
        gamma = 1.6666666666666667,
    ):
        self.radii = radii  # type: Optional[List[float]]
        self.radiusIndices = radiusIndices  # type: Optional[List[int]]
        self.temperatureBins = temperatureBins  # type: Optional[List[float]]
        self.numRadii = numRadii  # type: int
        self.gamma = gamma  # type: float

    @classmethod
    def InitFromBuf(cls, buf, pos):
        fluxSurfaceParams = FluxSurfaceParams()
        fluxSurfaceParams.Init(buf, pos)
        return cls.InitFromObj(fluxSurfaceParams)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, fluxSurfaceParams):
        x = FluxSurfaceParamsT()
        x._UnPack(fluxSurfaceParams)
        return x

    # FluxSurfaceParamsT
    def _UnPack(self, fluxSurfaceParams):
        if fluxSurfaceParams is None:
            return
        if not fluxSurfaceParams.RadiiIsNone():
            if np is None:
                self.radii = []
                for i in range(fluxSurfaceParams.RadiiLength()):
                    self.radii.append(fluxSurfaceParams.Radii(i))
            else:
                self.radii = fluxSurfaceParams.RadiiAsNumpy()
        if not fluxSurfaceParams.RadiusIndicesIsNone():
            if np is None:
                self.radiusIndices = []
                for i in range(fluxSurfaceParams.RadiusIndicesLength()):
                    self.radiusIndices.append(fluxSurfaceParams.RadiusIndices(i))
            else:
                self.radiusIndices = fluxSurfaceParams.RadiusIndicesAsNumpy()
        if not fluxSurfaceParams.TemperatureBinsIsNone():
            if np is None:
                self.temperatureBins = []
                for i in range(fluxSurfaceParams.TemperatureBinsLength()):
                    self.temperatureBins.append(fluxSurfaceParams.TemperatureBins(i))
            else:
                self.temperatureBins = fluxSurfaceParams.TemperatureBinsAsNumpy()
        self.numRadii = fluxSurfaceParams.NumRadii()
        self.gamma = fluxSurfaceParams.Gamma()

    # FluxSurfaceParamsT
    def Pack(self, builder):
        if self.radii is not None:
            if np is not None and type(self.radii) is np.ndarray:
                radii = builder.CreateNumpyVector(self.radii)
            else:
                FluxSurfaceParamsStartRadiiVector(builder, len(self.radii))
                for i in reversed(range(len(self.radii))):
                    builder.PrependFloat64(self.radii[i])
                radii = builder.EndVector()
        if self.radiusIndices is not None:
            if np is not None and type(self.radiusIndices) is np.ndarray:
                radiusIndices = builder.CreateNumpyVector(self.radiusIndices)
            else:
                FluxSurfaceParamsStartRadiusIndicesVector(builder, len(self.radiusIndices))
                for i in reversed(range(len(self.radiusIndices))):
                    builder.PrependInt32(self.radiusIndices[i])
                radiusIndices = builder.EndVector()
        if self.temperatureBins is not None:
            if np is not None and type(self.temperatureBins) is np.ndarray:
                temperatureBins = builder.CreateNumpyVector(self.temperatureBins)
            else:
                FluxSurfaceParamsStartTemperatureBinsVector(builder, len(self.temperatureBins))
                for i in reversed(range(len(self.temperatureBins))):
                    builder.PrependFloat64(self.temperatureBins[i])
                temperatureBins = builder.EndVector()
        FluxSurfaceParamsStart(builder)
        if self.radii is not None:
            FluxSurfaceParamsAddRadii(builder, radii)
        if self.radiusIndices is not None:
            FluxSurfaceParamsAddRadiusIndices(builder, radiusIndices)
        if self.temperatureBins is not None:
            FluxSurfaceParamsAddTemperatureBins(builder, temperatureBins)
        FluxSurfaceParamsAddNumRadii(builder, self.numRadii)
        FluxSurfaceParamsAddGamma(builder, self.gamma)
        fluxSurfaceParams = FluxSurfaceParamsEnd(builder)
        return fluxSurfaceParams
