from __future__ import annotations

import flatbuffers
import numpy as np

import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class GradStencilParams(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> GradStencilParams: ...
  @classmethod
  def GetRootAsGradStencilParams(cls, buf: bytes, offset: int) -> GradStencilParams: ...
  @classmethod
  def GradStencilParamsBufferHasIdentifier(cls, buf: bytes, offset: int, size_prefixed: bool) -> bool: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def InputField(self) -> int: ...
  def InputVersion(self) -> int: ...
  def InputStep(self) -> int: ...
  def InputLevel(self) -> int: ...
  def StencilRadius(self) -> int: ...
class GradStencilParamsT(object):
  inputField: int
  inputVersion: int
  inputStep: int
  inputLevel: int
  stencilRadius: int
  def __init__(
    self,
    inputField: int = ...,
    inputVersion: int = ...,
    inputStep: int = ...,
    inputLevel: int = ...,
    stencilRadius: int = ...,
  ) -> None: ...
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> GradStencilParamsT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> GradStencilParamsT: ...
  @classmethod
  def InitFromObj(cls, gradStencilParams: GradStencilParams) -> GradStencilParamsT: ...
  def _UnPack(self, gradStencilParams: GradStencilParams) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def GradStencilParamsStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def GradStencilParamsAddInputField(builder: flatbuffers.Builder, inputField: int) -> None: ...
def GradStencilParamsAddInputVersion(builder: flatbuffers.Builder, inputVersion: int) -> None: ...
def GradStencilParamsAddInputStep(builder: flatbuffers.Builder, inputStep: int) -> None: ...
def GradStencilParamsAddInputLevel(builder: flatbuffers.Builder, inputLevel: int) -> None: ...
def GradStencilParamsAddStencilRadius(builder: flatbuffers.Builder, stencilRadius: int) -> None: ...
def GradStencilParamsEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

