# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fb

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
np = import_numpy()

class GradStencilParams(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = GradStencilParams()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsGradStencilParams(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def GradStencilParamsBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x4B\x50\x4C\x4E", size_prefixed=size_prefixed)

    # GradStencilParams
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # GradStencilParams
    def InputField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return -1

    # GradStencilParams
    def InputVersion(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # GradStencilParams
    def InputStep(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # GradStencilParams
    def InputLevel(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int16Flags, o + self._tab.Pos)
        return 0

    # GradStencilParams
    def StencilRadius(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 1

def GradStencilParamsStart(builder: flatbuffers.Builder):
    builder.StartObject(5)

def Start(builder: flatbuffers.Builder):
    GradStencilParamsStart(builder)

def GradStencilParamsAddInputField(builder: flatbuffers.Builder, inputField: int):
    builder.PrependInt32Slot(0, inputField, -1)

def AddInputField(builder: flatbuffers.Builder, inputField: int):
    GradStencilParamsAddInputField(builder, inputField)

def GradStencilParamsAddInputVersion(builder: flatbuffers.Builder, inputVersion: int):
    builder.PrependInt32Slot(1, inputVersion, 0)

def AddInputVersion(builder: flatbuffers.Builder, inputVersion: int):
    GradStencilParamsAddInputVersion(builder, inputVersion)

def GradStencilParamsAddInputStep(builder: flatbuffers.Builder, inputStep: int):
    builder.PrependInt32Slot(2, inputStep, 0)

def AddInputStep(builder: flatbuffers.Builder, inputStep: int):
    GradStencilParamsAddInputStep(builder, inputStep)

def GradStencilParamsAddInputLevel(builder: flatbuffers.Builder, inputLevel: int):
    builder.PrependInt16Slot(3, inputLevel, 0)

def AddInputLevel(builder: flatbuffers.Builder, inputLevel: int):
    GradStencilParamsAddInputLevel(builder, inputLevel)

def GradStencilParamsAddStencilRadius(builder: flatbuffers.Builder, stencilRadius: int):
    builder.PrependInt32Slot(4, stencilRadius, 1)

def AddStencilRadius(builder: flatbuffers.Builder, stencilRadius: int):
    GradStencilParamsAddStencilRadius(builder, stencilRadius)

def GradStencilParamsEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return GradStencilParamsEnd(builder)


class GradStencilParamsT(object):

    # GradStencilParamsT
    def __init__(
        self,
        inputField = -1,
        inputVersion = 0,
        inputStep = 0,
        inputLevel = 0,
        stencilRadius = 1,
    ):
        self.inputField = inputField  # type: int
        self.inputVersion = inputVersion  # type: int
        self.inputStep = inputStep  # type: int
        self.inputLevel = inputLevel  # type: int
        self.stencilRadius = stencilRadius  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        gradStencilParams = GradStencilParams()
        gradStencilParams.Init(buf, pos)
        return cls.InitFromObj(gradStencilParams)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, gradStencilParams):
        x = GradStencilParamsT()
        x._UnPack(gradStencilParams)
        return x

    # GradStencilParamsT
    def _UnPack(self, gradStencilParams):
        if gradStencilParams is None:
            return
        self.inputField = gradStencilParams.InputField()
        self.inputVersion = gradStencilParams.InputVersion()
        self.inputStep = gradStencilParams.InputStep()
        self.inputLevel = gradStencilParams.InputLevel()
        self.stencilRadius = gradStencilParams.StencilRadius()

    # GradStencilParamsT
    def Pack(self, builder):
        GradStencilParamsStart(builder)
        GradStencilParamsAddInputField(builder, self.inputField)
        GradStencilParamsAddInputVersion(builder, self.inputVersion)
        GradStencilParamsAddInputStep(builder, self.inputStep)
        GradStencilParamsAddInputLevel(builder, self.inputLevel)
        GradStencilParamsAddStencilRadius(builder, self.stencilRadius)
        gradStencilParams = GradStencilParamsEnd(builder)
        return gradStencilParams
