# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fb

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
np = import_numpy()

class GraphReduceSpec(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = GraphReduceSpec()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsGraphReduceSpec(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def GraphReduceSpecBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x4B\x50\x4C\x4E", size_prefixed=size_prefixed)

    # GraphReduceSpec
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # GraphReduceSpec
    def FanIn(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 1

    # GraphReduceSpec
    def NumInputs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # GraphReduceSpec
    def InputBase(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # GraphReduceSpec
    def OutputBase(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # GraphReduceSpec
    def InputBlocks(self, j: int):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # GraphReduceSpec
    def InputBlocksAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # GraphReduceSpec
    def InputBlocksLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # GraphReduceSpec
    def InputBlocksIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        return o == 0

    # GraphReduceSpec
    def OutputBlocks(self, j: int):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # GraphReduceSpec
    def OutputBlocksAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # GraphReduceSpec
    def OutputBlocksLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # GraphReduceSpec
    def OutputBlocksIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        return o == 0

    # GraphReduceSpec
    def GroupOffsets(self, j: int):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # GraphReduceSpec
    def GroupOffsetsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # GraphReduceSpec
    def GroupOffsetsLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # GraphReduceSpec
    def GroupOffsetsIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        return o == 0

def GraphReduceSpecStart(builder: flatbuffers.Builder):
    builder.StartObject(7)

def Start(builder: flatbuffers.Builder):
    GraphReduceSpecStart(builder)

def GraphReduceSpecAddFanIn(builder: flatbuffers.Builder, fanIn: int):
    builder.PrependInt32Slot(0, fanIn, 1)

def AddFanIn(builder: flatbuffers.Builder, fanIn: int):
    GraphReduceSpecAddFanIn(builder, fanIn)

def GraphReduceSpecAddNumInputs(builder: flatbuffers.Builder, numInputs: int):
    builder.PrependInt32Slot(1, numInputs, 0)

def AddNumInputs(builder: flatbuffers.Builder, numInputs: int):
    GraphReduceSpecAddNumInputs(builder, numInputs)

def GraphReduceSpecAddInputBase(builder: flatbuffers.Builder, inputBase: int):
    builder.PrependInt32Slot(2, inputBase, 0)

def AddInputBase(builder: flatbuffers.Builder, inputBase: int):
    GraphReduceSpecAddInputBase(builder, inputBase)

def GraphReduceSpecAddOutputBase(builder: flatbuffers.Builder, outputBase: int):
    builder.PrependInt32Slot(3, outputBase, 0)

def AddOutputBase(builder: flatbuffers.Builder, outputBase: int):
    GraphReduceSpecAddOutputBase(builder, outputBase)

def GraphReduceSpecAddInputBlocks(builder: flatbuffers.Builder, inputBlocks: int):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(inputBlocks), 0)

def AddInputBlocks(builder: flatbuffers.Builder, inputBlocks: int):
    GraphReduceSpecAddInputBlocks(builder, inputBlocks)

def GraphReduceSpecStartInputBlocksVector(builder, numElems: int) -> int:
    return builder.StartVector(4, numElems, 4)

def StartInputBlocksVector(builder, numElems: int) -> int:
    return GraphReduceSpecStartInputBlocksVector(builder, numElems)

def GraphReduceSpecAddOutputBlocks(builder: flatbuffers.Builder, outputBlocks: int):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(outputBlocks), 0)

def AddOutputBlocks(builder: flatbuffers.Builder, outputBlocks: int):
    GraphReduceSpecAddOutputBlocks(builder, outputBlocks)

def GraphReduceSpecStartOutputBlocksVector(builder, numElems: int) -> int:
    return builder.StartVector(4, numElems, 4)

def StartOutputBlocksVector(builder, numElems: int) -> int:
    return GraphReduceSpecStartOutputBlocksVector(builder, numElems)

def GraphReduceSpecAddGroupOffsets(builder: flatbuffers.Builder, groupOffsets: int):
    builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(groupOffsets), 0)

def AddGroupOffsets(builder: flatbuffers.Builder, groupOffsets: int):
    GraphReduceSpecAddGroupOffsets(builder, groupOffsets)

def GraphReduceSpecStartGroupOffsetsVector(builder, numElems: int) -> int:
    return builder.StartVector(4, numElems, 4)

def StartGroupOffsetsVector(builder, numElems: int) -> int:
    return GraphReduceSpecStartGroupOffsetsVector(builder, numElems)

def GraphReduceSpecEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return GraphReduceSpecEnd(builder)

try:
    from typing import List
except:
    pass

class GraphReduceSpecT(object):

    # GraphReduceSpecT
    def __init__(
        self,
        fanIn = 1,
        numInputs = 0,
        inputBase = 0,
        outputBase = 0,
        inputBlocks = None,
        outputBlocks = None,
        groupOffsets = None,
    ):
        self.fanIn = fanIn  # type: int
        self.numInputs = numInputs  # type: int
        self.inputBase = inputBase  # type: int
        self.outputBase = outputBase  # type: int
        self.inputBlocks = inputBlocks  # type: Optional[List[int]]
        self.outputBlocks = outputBlocks  # type: Optional[List[int]]
        self.groupOffsets = groupOffsets  # type: Optional[List[int]]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        graphReduceSpec = GraphReduceSpec()
        graphReduceSpec.Init(buf, pos)
        return cls.InitFromObj(graphReduceSpec)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, graphReduceSpec):
        x = GraphReduceSpecT()
        x._UnPack(graphReduceSpec)
        return x

    # GraphReduceSpecT
    def _UnPack(self, graphReduceSpec):
        if graphReduceSpec is None:
            return
        self.fanIn = graphReduceSpec.FanIn()
        self.numInputs = graphReduceSpec.NumInputs()
        self.inputBase = graphReduceSpec.InputBase()
        self.outputBase = graphReduceSpec.OutputBase()
        if not graphReduceSpec.InputBlocksIsNone():
            if np is None:
                self.inputBlocks = []
                for i in range(graphReduceSpec.InputBlocksLength()):
                    self.inputBlocks.append(graphReduceSpec.InputBlocks(i))
            else:
                self.inputBlocks = graphReduceSpec.InputBlocksAsNumpy()
        if not graphReduceSpec.OutputBlocksIsNone():
            if np is None:
                self.outputBlocks = []
                for i in range(graphReduceSpec.OutputBlocksLength()):
                    self.outputBlocks.append(graphReduceSpec.OutputBlocks(i))
            else:
                self.outputBlocks = graphReduceSpec.OutputBlocksAsNumpy()
        if not graphReduceSpec.GroupOffsetsIsNone():
            if np is None:
                self.groupOffsets = []
                for i in range(graphReduceSpec.GroupOffsetsLength()):
                    self.groupOffsets.append(graphReduceSpec.GroupOffsets(i))
            else:
                self.groupOffsets = graphReduceSpec.GroupOffsetsAsNumpy()

    # GraphReduceSpecT
    def Pack(self, builder):
        if self.inputBlocks is not None:
            if np is not None and type(self.inputBlocks) is np.ndarray:
                inputBlocks = builder.CreateNumpyVector(self.inputBlocks)
            else:
                GraphReduceSpecStartInputBlocksVector(builder, len(self.inputBlocks))
                for i in reversed(range(len(self.inputBlocks))):
                    builder.PrependInt32(self.inputBlocks[i])
                inputBlocks = builder.EndVector()
        if self.outputBlocks is not None:
            if np is not None and type(self.outputBlocks) is np.ndarray:
                outputBlocks = builder.CreateNumpyVector(self.outputBlocks)
            else:
                GraphReduceSpecStartOutputBlocksVector(builder, len(self.outputBlocks))
                for i in reversed(range(len(self.outputBlocks))):
                    builder.PrependInt32(self.outputBlocks[i])
                outputBlocks = builder.EndVector()
        if self.groupOffsets is not None:
            if np is not None and type(self.groupOffsets) is np.ndarray:
                groupOffsets = builder.CreateNumpyVector(self.groupOffsets)
            else:
                GraphReduceSpecStartGroupOffsetsVector(builder, len(self.groupOffsets))
                for i in reversed(range(len(self.groupOffsets))):
                    builder.PrependInt32(self.groupOffsets[i])
                groupOffsets = builder.EndVector()
        GraphReduceSpecStart(builder)
        GraphReduceSpecAddFanIn(builder, self.fanIn)
        GraphReduceSpecAddNumInputs(builder, self.numInputs)
        GraphReduceSpecAddInputBase(builder, self.inputBase)
        GraphReduceSpecAddOutputBase(builder, self.outputBase)
        if self.inputBlocks is not None:
            GraphReduceSpecAddInputBlocks(builder, inputBlocks)
        if self.outputBlocks is not None:
            GraphReduceSpecAddOutputBlocks(builder, outputBlocks)
        if self.groupOffsets is not None:
            GraphReduceSpecAddGroupOffsets(builder, groupOffsets)
        graphReduceSpec = GraphReduceSpecEnd(builder)
        return graphReduceSpec
