from __future__ import annotations

import flatbuffers
import numpy as np

import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class GraphReduceSpec(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> GraphReduceSpec: ...
  @classmethod
  def GetRootAsGraphReduceSpec(cls, buf: bytes, offset: int) -> GraphReduceSpec: ...
  @classmethod
  def GraphReduceSpecBufferHasIdentifier(cls, buf: bytes, offset: int, size_prefixed: bool) -> bool: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def FanIn(self) -> int: ...
  def NumInputs(self) -> int: ...
  def InputBase(self) -> int: ...
  def OutputBase(self) -> int: ...
  def InputBlocks(self, i: int) -> typing.List[int]: ...
  def InputBlocksAsNumpy(self) -> np.ndarray: ...
  def InputBlocksLength(self) -> int: ...
  def InputBlocksIsNone(self) -> bool: ...
  def OutputBlocks(self, i: int) -> typing.List[int]: ...
  def OutputBlocksAsNumpy(self) -> np.ndarray: ...
  def OutputBlocksLength(self) -> int: ...
  def OutputBlocksIsNone(self) -> bool: ...
  def GroupOffsets(self, i: int) -> typing.List[int]: ...
  def GroupOffsetsAsNumpy(self) -> np.ndarray: ...
  def GroupOffsetsLength(self) -> int: ...
  def GroupOffsetsIsNone(self) -> bool: ...
class GraphReduceSpecT(object):
  fanIn: int
  numInputs: int
  inputBase: int
  outputBase: int
  inputBlocks: typing.List[int]
  outputBlocks: typing.List[int]
  groupOffsets: typing.List[int]
  def __init__(
    self,
    fanIn: int = ...,
    numInputs: int = ...,
    inputBase: int = ...,
    outputBase: int = ...,
    inputBlocks: typing.List[int] | None = ...,
    outputBlocks: typing.List[int] | None = ...,
    groupOffsets: typing.List[int] | None = ...,
  ) -> None: ...
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> GraphReduceSpecT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> GraphReduceSpecT: ...
  @classmethod
  def InitFromObj(cls, graphReduceSpec: GraphReduceSpec) -> GraphReduceSpecT: ...
  def _UnPack(self, graphReduceSpec: GraphReduceSpec) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def GraphReduceSpecStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def GraphReduceSpecAddFanIn(builder: flatbuffers.Builder, fanIn: int) -> None: ...
def GraphReduceSpecAddNumInputs(builder: flatbuffers.Builder, numInputs: int) -> None: ...
def GraphReduceSpecAddInputBase(builder: flatbuffers.Builder, inputBase: int) -> None: ...
def GraphReduceSpecAddOutputBase(builder: flatbuffers.Builder, outputBase: int) -> None: ...
def GraphReduceSpecAddInputBlocks(builder: flatbuffers.Builder, inputBlocks: uoffset) -> None: ...
def GraphReduceSpecStartInputBlocksVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartInputBlocksVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def GraphReduceSpecAddOutputBlocks(builder: flatbuffers.Builder, outputBlocks: uoffset) -> None: ...
def GraphReduceSpecStartOutputBlocksVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartOutputBlocksVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def GraphReduceSpecAddGroupOffsets(builder: flatbuffers.Builder, groupOffsets: uoffset) -> None: ...
def GraphReduceSpecStartGroupOffsetsVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartGroupOffsetsVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def GraphReduceSpecEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

