# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fb

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from typing import Optional
np = import_numpy()

class Histogram2DParams(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Histogram2DParams()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsHistogram2DParams(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def Histogram2DParamsBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x4B\x50\x4C\x4E", size_prefixed=size_prefixed)

    # Histogram2DParams
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Histogram2DParams
    def XRange(self, j: int):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Float64Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 8))
        return 0

    # Histogram2DParams
    def XRangeAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float64Flags, o)
        return 0

    # Histogram2DParams
    def XRangeLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Histogram2DParams
    def XRangeIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

    # Histogram2DParams
    def YRange(self, j: int):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Float64Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 8))
        return 0

    # Histogram2DParams
    def YRangeAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float64Flags, o)
        return 0

    # Histogram2DParams
    def YRangeLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Histogram2DParams
    def YRangeIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

    # Histogram2DParams
    def Bins(self, j: int):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # Histogram2DParams
    def BinsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # Histogram2DParams
    def BinsLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Histogram2DParams
    def BinsIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

    # Histogram2DParams
    def WeightMode(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def Histogram2DParamsStart(builder: flatbuffers.Builder):
    builder.StartObject(4)

def Start(builder: flatbuffers.Builder):
    Histogram2DParamsStart(builder)

def Histogram2DParamsAddXRange(builder: flatbuffers.Builder, xRange: int):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(xRange), 0)

def AddXRange(builder: flatbuffers.Builder, xRange: int):
    Histogram2DParamsAddXRange(builder, xRange)

def Histogram2DParamsStartXRangeVector(builder, numElems: int) -> int:
    return builder.StartVector(8, numElems, 8)

def StartXRangeVector(builder, numElems: int) -> int:
    return Histogram2DParamsStartXRangeVector(builder, numElems)

def Histogram2DParamsAddYRange(builder: flatbuffers.Builder, yRange: int):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(yRange), 0)

def AddYRange(builder: flatbuffers.Builder, yRange: int):
    Histogram2DParamsAddYRange(builder, yRange)

def Histogram2DParamsStartYRangeVector(builder, numElems: int) -> int:
    return builder.StartVector(8, numElems, 8)

def StartYRangeVector(builder, numElems: int) -> int:
    return Histogram2DParamsStartYRangeVector(builder, numElems)

def Histogram2DParamsAddBins(builder: flatbuffers.Builder, bins: int):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(bins), 0)

def AddBins(builder: flatbuffers.Builder, bins: int):
    Histogram2DParamsAddBins(builder, bins)

def Histogram2DParamsStartBinsVector(builder, numElems: int) -> int:
    return builder.StartVector(4, numElems, 4)

def StartBinsVector(builder, numElems: int) -> int:
    return Histogram2DParamsStartBinsVector(builder, numElems)

def Histogram2DParamsAddWeightMode(builder: flatbuffers.Builder, weightMode: int):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(weightMode), 0)

def AddWeightMode(builder: flatbuffers.Builder, weightMode: int):
    Histogram2DParamsAddWeightMode(builder, weightMode)

def Histogram2DParamsEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return Histogram2DParamsEnd(builder)

try:
    from typing import List
except:
    pass

class Histogram2DParamsT(object):

    # Histogram2DParamsT
    def __init__(
        self,
        xRange = None,
        yRange = None,
        bins = None,
        weightMode = None,
    ):
        self.xRange = xRange  # type: Optional[List[float]]
        self.yRange = yRange  # type: Optional[List[float]]
        self.bins = bins  # type: Optional[List[int]]
        self.weightMode = weightMode  # type: Optional[str]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        histogram2Dparams = Histogram2DParams()
        histogram2Dparams.Init(buf, pos)
        return cls.InitFromObj(histogram2Dparams)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, histogram2Dparams):
        x = Histogram2DParamsT()
        x._UnPack(histogram2Dparams)
        return x

    # Histogram2DParamsT
    def _UnPack(self, histogram2Dparams):
        if histogram2Dparams is None:
            return
        if not histogram2Dparams.XRangeIsNone():
            if np is None:
                self.xRange = []
                for i in range(histogram2Dparams.XRangeLength()):
                    self.xRange.append(histogram2Dparams.XRange(i))
            else:
                self.xRange = histogram2Dparams.XRangeAsNumpy()
        if not histogram2Dparams.YRangeIsNone():
            if np is None:
                self.yRange = []
                for i in range(histogram2Dparams.YRangeLength()):
                    self.yRange.append(histogram2Dparams.YRange(i))
            else:
                self.yRange = histogram2Dparams.YRangeAsNumpy()
        if not histogram2Dparams.BinsIsNone():
            if np is None:
                self.bins = []
                for i in range(histogram2Dparams.BinsLength()):
                    self.bins.append(histogram2Dparams.Bins(i))
            else:
                self.bins = histogram2Dparams.BinsAsNumpy()
        self.weightMode = histogram2Dparams.WeightMode()

    # Histogram2DParamsT
    def Pack(self, builder):
        if self.xRange is not None:
            if np is not None and type(self.xRange) is np.ndarray:
                xRange = builder.CreateNumpyVector(self.xRange)
            else:
                Histogram2DParamsStartXRangeVector(builder, len(self.xRange))
                for i in reversed(range(len(self.xRange))):
                    builder.PrependFloat64(self.xRange[i])
                xRange = builder.EndVector()
        if self.yRange is not None:
            if np is not None and type(self.yRange) is np.ndarray:
                yRange = builder.CreateNumpyVector(self.yRange)
            else:
                Histogram2DParamsStartYRangeVector(builder, len(self.yRange))
                for i in reversed(range(len(self.yRange))):
                    builder.PrependFloat64(self.yRange[i])
                yRange = builder.EndVector()
        if self.bins is not None:
            if np is not None and type(self.bins) is np.ndarray:
                bins = builder.CreateNumpyVector(self.bins)
            else:
                Histogram2DParamsStartBinsVector(builder, len(self.bins))
                for i in reversed(range(len(self.bins))):
                    builder.PrependInt32(self.bins[i])
                bins = builder.EndVector()
        if self.weightMode is not None:
            weightMode = builder.CreateString(self.weightMode)
        Histogram2DParamsStart(builder)
        if self.xRange is not None:
            Histogram2DParamsAddXRange(builder, xRange)
        if self.yRange is not None:
            Histogram2DParamsAddYRange(builder, yRange)
        if self.bins is not None:
            Histogram2DParamsAddBins(builder, bins)
        if self.weightMode is not None:
            Histogram2DParamsAddWeightMode(builder, weightMode)
        histogram2Dparams = Histogram2DParamsEnd(builder)
        return histogram2Dparams
