# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fb

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
np = import_numpy()

class Histogram1DParams(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Histogram1DParams()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsHistogram1DParams(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def Histogram1DParamsBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x4B\x50\x4C\x4E", size_prefixed=size_prefixed)

    # Histogram1DParams
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Histogram1DParams
    def Bounds(self, j: int):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Float64Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 8))
        return 0

    # Histogram1DParams
    def BoundsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float64Flags, o)
        return 0

    # Histogram1DParams
    def BoundsLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Histogram1DParams
    def BoundsIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

    # Histogram1DParams
    def Bins(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 1

def Histogram1DParamsStart(builder: flatbuffers.Builder):
    builder.StartObject(2)

def Start(builder: flatbuffers.Builder):
    Histogram1DParamsStart(builder)

def Histogram1DParamsAddBounds(builder: flatbuffers.Builder, bounds: int):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(bounds), 0)

def AddBounds(builder: flatbuffers.Builder, bounds: int):
    Histogram1DParamsAddBounds(builder, bounds)

def Histogram1DParamsStartBoundsVector(builder, numElems: int) -> int:
    return builder.StartVector(8, numElems, 8)

def StartBoundsVector(builder, numElems: int) -> int:
    return Histogram1DParamsStartBoundsVector(builder, numElems)

def Histogram1DParamsAddBins(builder: flatbuffers.Builder, bins: int):
    builder.PrependInt32Slot(1, bins, 1)

def AddBins(builder: flatbuffers.Builder, bins: int):
    Histogram1DParamsAddBins(builder, bins)

def Histogram1DParamsEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return Histogram1DParamsEnd(builder)

try:
    from typing import List
except:
    pass

class Histogram1DParamsT(object):

    # Histogram1DParamsT
    def __init__(
        self,
        bounds = None,
        bins = 1,
    ):
        self.bounds = bounds  # type: Optional[List[float]]
        self.bins = bins  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        histogram1Dparams = Histogram1DParams()
        histogram1Dparams.Init(buf, pos)
        return cls.InitFromObj(histogram1Dparams)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, histogram1Dparams):
        x = Histogram1DParamsT()
        x._UnPack(histogram1Dparams)
        return x

    # Histogram1DParamsT
    def _UnPack(self, histogram1Dparams):
        if histogram1Dparams is None:
            return
        if not histogram1Dparams.BoundsIsNone():
            if np is None:
                self.bounds = []
                for i in range(histogram1Dparams.BoundsLength()):
                    self.bounds.append(histogram1Dparams.Bounds(i))
            else:
                self.bounds = histogram1Dparams.BoundsAsNumpy()
        self.bins = histogram1Dparams.Bins()

    # Histogram1DParamsT
    def Pack(self, builder):
        if self.bounds is not None:
            if np is not None and type(self.bounds) is np.ndarray:
                bounds = builder.CreateNumpyVector(self.bounds)
            else:
                Histogram1DParamsStartBoundsVector(builder, len(self.bounds))
                for i in reversed(range(len(self.bounds))):
                    builder.PrependFloat64(self.bounds[i])
                bounds = builder.EndVector()
        Histogram1DParamsStart(builder)
        if self.bounds is not None:
            Histogram1DParamsAddBounds(builder, bounds)
        Histogram1DParamsAddBins(builder, self.bins)
        histogram1Dparams = Histogram1DParamsEnd(builder)
        return histogram1Dparams
