from __future__ import annotations

import flatbuffers
import numpy as np

import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Histogram1DParams(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Histogram1DParams: ...
  @classmethod
  def GetRootAsHistogram1DParams(cls, buf: bytes, offset: int) -> Histogram1DParams: ...
  @classmethod
  def Histogram1DParamsBufferHasIdentifier(cls, buf: bytes, offset: int, size_prefixed: bool) -> bool: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Bounds(self, i: int) -> typing.List[float]: ...
  def BoundsAsNumpy(self) -> np.ndarray: ...
  def BoundsLength(self) -> int: ...
  def BoundsIsNone(self) -> bool: ...
  def Bins(self) -> int: ...
class Histogram1DParamsT(object):
  bounds: typing.List[float]
  bins: int
  def __init__(
    self,
    bounds: typing.List[float] | None = ...,
    bins: int = ...,
  ) -> None: ...
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Histogram1DParamsT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Histogram1DParamsT: ...
  @classmethod
  def InitFromObj(cls, histogram1Dparams: Histogram1DParams) -> Histogram1DParamsT: ...
  def _UnPack(self, histogram1Dparams: Histogram1DParams) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Histogram1DParamsStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Histogram1DParamsAddBounds(builder: flatbuffers.Builder, bounds: uoffset) -> None: ...
def Histogram1DParamsStartBoundsVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartBoundsVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def Histogram1DParamsAddBins(builder: flatbuffers.Builder, bins: int) -> None: ...
def Histogram1DParamsEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

