from __future__ import annotations

import flatbuffers
import numpy as np

import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Histogram2DParams(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Histogram2DParams: ...
  @classmethod
  def GetRootAsHistogram2DParams(cls, buf: bytes, offset: int) -> Histogram2DParams: ...
  @classmethod
  def Histogram2DParamsBufferHasIdentifier(cls, buf: bytes, offset: int, size_prefixed: bool) -> bool: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def XRange(self, i: int) -> typing.List[float]: ...
  def XRangeAsNumpy(self) -> np.ndarray: ...
  def XRangeLength(self) -> int: ...
  def XRangeIsNone(self) -> bool: ...
  def YRange(self, i: int) -> typing.List[float]: ...
  def YRangeAsNumpy(self) -> np.ndarray: ...
  def YRangeLength(self) -> int: ...
  def YRangeIsNone(self) -> bool: ...
  def Bins(self, i: int) -> typing.List[int]: ...
  def BinsAsNumpy(self) -> np.ndarray: ...
  def BinsLength(self) -> int: ...
  def BinsIsNone(self) -> bool: ...
  def WeightMode(self) -> str | None: ...
class Histogram2DParamsT(object):
  xRange: typing.List[float]
  yRange: typing.List[float]
  bins: typing.List[int]
  weightMode: str | None
  def __init__(
    self,
    xRange: typing.List[float] | None = ...,
    yRange: typing.List[float] | None = ...,
    bins: typing.List[int] | None = ...,
    weightMode: str | None = ...,
  ) -> None: ...
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Histogram2DParamsT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Histogram2DParamsT: ...
  @classmethod
  def InitFromObj(cls, histogram2Dparams: Histogram2DParams) -> Histogram2DParamsT: ...
  def _UnPack(self, histogram2Dparams: Histogram2DParams) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Histogram2DParamsStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Histogram2DParamsAddXRange(builder: flatbuffers.Builder, xRange: uoffset) -> None: ...
def Histogram2DParamsStartXRangeVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartXRangeVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def Histogram2DParamsAddYRange(builder: flatbuffers.Builder, yRange: uoffset) -> None: ...
def Histogram2DParamsStartYRangeVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartYRangeVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def Histogram2DParamsAddBins(builder: flatbuffers.Builder, bins: uoffset) -> None: ...
def Histogram2DParamsStartBinsVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartBinsVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def Histogram2DParamsAddWeightMode(builder: flatbuffers.Builder, weightMode: uoffset) -> None: ...
def Histogram2DParamsEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

