# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fb

class KernelParams(object):
    NONE = 0
    AmrSubboxPackParams = 1
    GradStencilParams = 2
    PlotfileLoadParams = 3
    FluxSurfaceParams = 4
    CylindricalFluxParams = 5
    UniformSliceCellParams = 6
    UniformProjectionParams = 7
    FieldExprParams = 8
    UniformSliceParams = 9
    Histogram1DParams = 10
    Histogram2DParams = 11
    ParticleFieldParams = 12
    ParticleCicGridParams = 13
    ParticleCicProjectionParams = 14
    ScalarParams = 15
    ValuesParams = 16
    FiniteOnlyParams = 17
    ParticleHistogramParams = 18
    TopKModesParams = 19
    SliceFinalizeParams = 20

def KernelParamsCreator(unionType, table):
    from flatbuffers.table import Table
    if not isinstance(table, Table):
        return None
    if unionType == KernelParams.AmrSubboxPackParams:
        import analysis.fb.AmrSubboxPackParams
        return analysis.fb.AmrSubboxPackParams.AmrSubboxPackParamsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == KernelParams.GradStencilParams:
        import analysis.fb.GradStencilParams
        return analysis.fb.GradStencilParams.GradStencilParamsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == KernelParams.PlotfileLoadParams:
        import analysis.fb.PlotfileLoadParams
        return analysis.fb.PlotfileLoadParams.PlotfileLoadParamsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == KernelParams.FluxSurfaceParams:
        import analysis.fb.FluxSurfaceParams
        return analysis.fb.FluxSurfaceParams.FluxSurfaceParamsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == KernelParams.CylindricalFluxParams:
        import analysis.fb.CylindricalFluxParams
        return analysis.fb.CylindricalFluxParams.CylindricalFluxParamsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == KernelParams.UniformSliceCellParams:
        import analysis.fb.UniformSliceCellParams
        return analysis.fb.UniformSliceCellParams.UniformSliceCellParamsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == KernelParams.UniformProjectionParams:
        import analysis.fb.UniformProjectionParams
        return analysis.fb.UniformProjectionParams.UniformProjectionParamsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == KernelParams.FieldExprParams:
        import analysis.fb.FieldExprParams
        return analysis.fb.FieldExprParams.FieldExprParamsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == KernelParams.UniformSliceParams:
        import analysis.fb.UniformSliceParams
        return analysis.fb.UniformSliceParams.UniformSliceParamsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == KernelParams.Histogram1DParams:
        import analysis.fb.Histogram1DParams
        return analysis.fb.Histogram1DParams.Histogram1DParamsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == KernelParams.Histogram2DParams:
        import analysis.fb.Histogram2DParams
        return analysis.fb.Histogram2DParams.Histogram2DParamsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == KernelParams.ParticleFieldParams:
        import analysis.fb.ParticleFieldParams
        return analysis.fb.ParticleFieldParams.ParticleFieldParamsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == KernelParams.ParticleCicGridParams:
        import analysis.fb.ParticleCicGridParams
        return analysis.fb.ParticleCicGridParams.ParticleCicGridParamsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == KernelParams.ParticleCicProjectionParams:
        import analysis.fb.ParticleCicProjectionParams
        return analysis.fb.ParticleCicProjectionParams.ParticleCicProjectionParamsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == KernelParams.ScalarParams:
        import analysis.fb.ScalarParams
        return analysis.fb.ScalarParams.ScalarParamsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == KernelParams.ValuesParams:
        import analysis.fb.ValuesParams
        return analysis.fb.ValuesParams.ValuesParamsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == KernelParams.FiniteOnlyParams:
        import analysis.fb.FiniteOnlyParams
        return analysis.fb.FiniteOnlyParams.FiniteOnlyParamsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == KernelParams.ParticleHistogramParams:
        import analysis.fb.ParticleHistogramParams
        return analysis.fb.ParticleHistogramParams.ParticleHistogramParamsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == KernelParams.TopKModesParams:
        import analysis.fb.TopKModesParams
        return analysis.fb.TopKModesParams.TopKModesParamsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == KernelParams.SliceFinalizeParams:
        import analysis.fb.SliceFinalizeParams
        return analysis.fb.SliceFinalizeParams.SliceFinalizeParamsT.InitFromBuf(table.Bytes, table.Pos)
    return None
