# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fb

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from analysis.fb.BufferSpec import BufferSpec
from typing import Optional
np = import_numpy()

class OutputRef(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = OutputRef()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsOutputRef(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def OutputRefBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x4B\x50\x4C\x4E", size_prefixed=size_prefixed)

    # OutputRef
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # OutputRef
    def Field(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # OutputRef
    def Version(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # OutputRef
    def Buffer(self) -> Optional[BufferSpec]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = BufferSpec()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def OutputRefStart(builder: flatbuffers.Builder):
    builder.StartObject(3)

def Start(builder: flatbuffers.Builder):
    OutputRefStart(builder)

def OutputRefAddField(builder: flatbuffers.Builder, field: int):
    builder.PrependInt32Slot(0, field, 0)

def AddField(builder: flatbuffers.Builder, field: int):
    OutputRefAddField(builder, field)

def OutputRefAddVersion(builder: flatbuffers.Builder, version: int):
    builder.PrependInt32Slot(1, version, 0)

def AddVersion(builder: flatbuffers.Builder, version: int):
    OutputRefAddVersion(builder, version)

def OutputRefAddBuffer(builder: flatbuffers.Builder, buffer: int):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(buffer), 0)

def AddBuffer(builder: flatbuffers.Builder, buffer: int):
    OutputRefAddBuffer(builder, buffer)

def OutputRefEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return OutputRefEnd(builder)

import analysis.fb.BufferSpec
try:
    from typing import Optional
except:
    pass

class OutputRefT(object):

    # OutputRefT
    def __init__(
        self,
        field = 0,
        version = 0,
        buffer = None,
    ):
        self.field = field  # type: int
        self.version = version  # type: int
        self.buffer = buffer  # type: Optional[analysis.fb.BufferSpec.BufferSpecT]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        outputRef = OutputRef()
        outputRef.Init(buf, pos)
        return cls.InitFromObj(outputRef)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, outputRef):
        x = OutputRefT()
        x._UnPack(outputRef)
        return x

    # OutputRefT
    def _UnPack(self, outputRef):
        if outputRef is None:
            return
        self.field = outputRef.Field()
        self.version = outputRef.Version()
        if outputRef.Buffer() is not None:
            self.buffer = analysis.fb.BufferSpec.BufferSpecT.InitFromObj(outputRef.Buffer())

    # OutputRefT
    def Pack(self, builder):
        if self.buffer is not None:
            buffer = self.buffer.Pack(builder)
        OutputRefStart(builder)
        OutputRefAddField(builder, self.field)
        OutputRefAddVersion(builder, self.version)
        if self.buffer is not None:
            OutputRefAddBuffer(builder, buffer)
        outputRef = OutputRefEnd(builder)
        return outputRef
