from __future__ import annotations

import flatbuffers
import numpy as np

import typing
from analysis.fb.BufferSpec import BufferSpec, BufferSpecT

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class OutputRef(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> OutputRef: ...
  @classmethod
  def GetRootAsOutputRef(cls, buf: bytes, offset: int) -> OutputRef: ...
  @classmethod
  def OutputRefBufferHasIdentifier(cls, buf: bytes, offset: int, size_prefixed: bool) -> bool: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Field(self) -> int: ...
  def Version(self) -> int: ...
  def Buffer(self) -> BufferSpec | None: ...
class OutputRefT(object):
  field: int
  version: int
  buffer: BufferSpecT | None
  def __init__(
    self,
    field: int = ...,
    version: int = ...,
    buffer: 'BufferSpecT' | None = ...,
  ) -> None: ...
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> OutputRefT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> OutputRefT: ...
  @classmethod
  def InitFromObj(cls, outputRef: OutputRef) -> OutputRefT: ...
  def _UnPack(self, outputRef: OutputRef) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def OutputRefStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def OutputRefAddField(builder: flatbuffers.Builder, field: int) -> None: ...
def OutputRefAddVersion(builder: flatbuffers.Builder, version: int) -> None: ...
def OutputRefAddBuffer(builder: flatbuffers.Builder, buffer: uoffset) -> None: ...
def OutputRefEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

