# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fb

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
np = import_numpy()

class ParticleHistogramParams(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ParticleHistogramParams()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsParticleHistogramParams(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def ParticleHistogramParamsBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x4B\x50\x4C\x4E", size_prefixed=size_prefixed)

    # ParticleHistogramParams
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ParticleHistogramParams
    def Edges(self, j: int):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Float64Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 8))
        return 0

    # ParticleHistogramParams
    def EdgesAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float64Flags, o)
        return 0

    # ParticleHistogramParams
    def EdgesLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ParticleHistogramParams
    def EdgesIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

    # ParticleHistogramParams
    def Density(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def ParticleHistogramParamsStart(builder: flatbuffers.Builder):
    builder.StartObject(2)

def Start(builder: flatbuffers.Builder):
    ParticleHistogramParamsStart(builder)

def ParticleHistogramParamsAddEdges(builder: flatbuffers.Builder, edges: int):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(edges), 0)

def AddEdges(builder: flatbuffers.Builder, edges: int):
    ParticleHistogramParamsAddEdges(builder, edges)

def ParticleHistogramParamsStartEdgesVector(builder, numElems: int) -> int:
    return builder.StartVector(8, numElems, 8)

def StartEdgesVector(builder, numElems: int) -> int:
    return ParticleHistogramParamsStartEdgesVector(builder, numElems)

def ParticleHistogramParamsAddDensity(builder: flatbuffers.Builder, density: bool):
    builder.PrependBoolSlot(1, density, 0)

def AddDensity(builder: flatbuffers.Builder, density: bool):
    ParticleHistogramParamsAddDensity(builder, density)

def ParticleHistogramParamsEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return ParticleHistogramParamsEnd(builder)

try:
    from typing import List
except:
    pass

class ParticleHistogramParamsT(object):

    # ParticleHistogramParamsT
    def __init__(
        self,
        edges = None,
        density = False,
    ):
        self.edges = edges  # type: Optional[List[float]]
        self.density = density  # type: bool

    @classmethod
    def InitFromBuf(cls, buf, pos):
        particleHistogramParams = ParticleHistogramParams()
        particleHistogramParams.Init(buf, pos)
        return cls.InitFromObj(particleHistogramParams)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, particleHistogramParams):
        x = ParticleHistogramParamsT()
        x._UnPack(particleHistogramParams)
        return x

    # ParticleHistogramParamsT
    def _UnPack(self, particleHistogramParams):
        if particleHistogramParams is None:
            return
        if not particleHistogramParams.EdgesIsNone():
            if np is None:
                self.edges = []
                for i in range(particleHistogramParams.EdgesLength()):
                    self.edges.append(particleHistogramParams.Edges(i))
            else:
                self.edges = particleHistogramParams.EdgesAsNumpy()
        self.density = particleHistogramParams.Density()

    # ParticleHistogramParamsT
    def Pack(self, builder):
        if self.edges is not None:
            if np is not None and type(self.edges) is np.ndarray:
                edges = builder.CreateNumpyVector(self.edges)
            else:
                ParticleHistogramParamsStartEdgesVector(builder, len(self.edges))
                for i in reversed(range(len(self.edges))):
                    builder.PrependFloat64(self.edges[i])
                edges = builder.EndVector()
        ParticleHistogramParamsStart(builder)
        if self.edges is not None:
            ParticleHistogramParamsAddEdges(builder, edges)
        ParticleHistogramParamsAddDensity(builder, self.density)
        particleHistogramParams = ParticleHistogramParamsEnd(builder)
        return particleHistogramParams
