from __future__ import annotations

import flatbuffers
import numpy as np

import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class ParticleHistogramParams(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> ParticleHistogramParams: ...
  @classmethod
  def GetRootAsParticleHistogramParams(cls, buf: bytes, offset: int) -> ParticleHistogramParams: ...
  @classmethod
  def ParticleHistogramParamsBufferHasIdentifier(cls, buf: bytes, offset: int, size_prefixed: bool) -> bool: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Edges(self, i: int) -> typing.List[float]: ...
  def EdgesAsNumpy(self) -> np.ndarray: ...
  def EdgesLength(self) -> int: ...
  def EdgesIsNone(self) -> bool: ...
  def Density(self) -> bool: ...
class ParticleHistogramParamsT(object):
  edges: typing.List[float]
  density: bool
  def __init__(
    self,
    edges: typing.List[float] | None = ...,
    density: bool = ...,
  ) -> None: ...
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> ParticleHistogramParamsT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> ParticleHistogramParamsT: ...
  @classmethod
  def InitFromObj(cls, particleHistogramParams: ParticleHistogramParams) -> ParticleHistogramParamsT: ...
  def _UnPack(self, particleHistogramParams: ParticleHistogramParams) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def ParticleHistogramParamsStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def ParticleHistogramParamsAddEdges(builder: flatbuffers.Builder, edges: uoffset) -> None: ...
def ParticleHistogramParamsStartEdgesVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartEdgesVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def ParticleHistogramParamsAddDensity(builder: flatbuffers.Builder, density: bool) -> None: ...
def ParticleHistogramParamsEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

