from __future__ import annotations

import flatbuffers
import numpy as np

import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class ParticleFieldParams(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> ParticleFieldParams: ...
  @classmethod
  def GetRootAsParticleFieldParams(cls, buf: bytes, offset: int) -> ParticleFieldParams: ...
  @classmethod
  def ParticleFieldParamsBufferHasIdentifier(cls, buf: bytes, offset: int, size_prefixed: bool) -> bool: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def ParticleType(self) -> str | None: ...
  def FieldName(self) -> str | None: ...
class ParticleFieldParamsT(object):
  particleType: str | None
  fieldName: str | None
  def __init__(
    self,
    particleType: str | None = ...,
    fieldName: str | None = ...,
  ) -> None: ...
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> ParticleFieldParamsT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> ParticleFieldParamsT: ...
  @classmethod
  def InitFromObj(cls, particleFieldParams: ParticleFieldParams) -> ParticleFieldParamsT: ...
  def _UnPack(self, particleFieldParams: ParticleFieldParams) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def ParticleFieldParamsStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def ParticleFieldParamsAddParticleType(builder: flatbuffers.Builder, particleType: uoffset) -> None: ...
def ParticleFieldParamsAddFieldName(builder: flatbuffers.Builder, fieldName: uoffset) -> None: ...
def ParticleFieldParamsEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

