from __future__ import annotations

import flatbuffers
import numpy as np

import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class ParticleCicProjectionParams(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> ParticleCicProjectionParams: ...
  @classmethod
  def GetRootAsParticleCicProjectionParams(cls, buf: bytes, offset: int) -> ParticleCicProjectionParams: ...
  @classmethod
  def ParticleCicProjectionParamsBufferHasIdentifier(cls, buf: bytes, offset: int, size_prefixed: bool) -> bool: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def ParticleType(self) -> str | None: ...
  def LevelIndex(self) -> int: ...
  def Axis(self) -> int: ...
  def AxisBounds(self, i: int) -> typing.List[float]: ...
  def AxisBoundsAsNumpy(self) -> np.ndarray: ...
  def AxisBoundsLength(self) -> int: ...
  def AxisBoundsIsNone(self) -> bool: ...
  def Rect(self, i: int) -> typing.List[float]: ...
  def RectAsNumpy(self) -> np.ndarray: ...
  def RectLength(self) -> int: ...
  def RectIsNone(self) -> bool: ...
  def Resolution(self, i: int) -> typing.List[int]: ...
  def ResolutionAsNumpy(self) -> np.ndarray: ...
  def ResolutionLength(self) -> int: ...
  def ResolutionIsNone(self) -> bool: ...
  def MassMax(self) -> float: ...
  def HasMassMax(self) -> bool: ...
class ParticleCicProjectionParamsT(object):
  particleType: str | None
  levelIndex: int
  axis: int
  axisBounds: typing.List[float]
  rect: typing.List[float]
  resolution: typing.List[int]
  massMax: float
  hasMassMax: bool
  def __init__(
    self,
    particleType: str | None = ...,
    levelIndex: int = ...,
    axis: int = ...,
    axisBounds: typing.List[float] | None = ...,
    rect: typing.List[float] | None = ...,
    resolution: typing.List[int] | None = ...,
    massMax: float = ...,
    hasMassMax: bool = ...,
  ) -> None: ...
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> ParticleCicProjectionParamsT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> ParticleCicProjectionParamsT: ...
  @classmethod
  def InitFromObj(cls, particleCicProjectionParams: ParticleCicProjectionParams) -> ParticleCicProjectionParamsT: ...
  def _UnPack(self, particleCicProjectionParams: ParticleCicProjectionParams) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def ParticleCicProjectionParamsStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def ParticleCicProjectionParamsAddParticleType(builder: flatbuffers.Builder, particleType: uoffset) -> None: ...
def ParticleCicProjectionParamsAddLevelIndex(builder: flatbuffers.Builder, levelIndex: int) -> None: ...
def ParticleCicProjectionParamsAddAxis(builder: flatbuffers.Builder, axis: int) -> None: ...
def ParticleCicProjectionParamsAddAxisBounds(builder: flatbuffers.Builder, axisBounds: uoffset) -> None: ...
def ParticleCicProjectionParamsStartAxisBoundsVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartAxisBoundsVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def ParticleCicProjectionParamsAddRect(builder: flatbuffers.Builder, rect: uoffset) -> None: ...
def ParticleCicProjectionParamsStartRectVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartRectVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def ParticleCicProjectionParamsAddResolution(builder: flatbuffers.Builder, resolution: uoffset) -> None: ...
def ParticleCicProjectionParamsStartResolutionVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartResolutionVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def ParticleCicProjectionParamsAddMassMax(builder: flatbuffers.Builder, massMax: float) -> None: ...
def ParticleCicProjectionParamsAddHasMassMax(builder: flatbuffers.Builder, hasMassMax: bool) -> None: ...
def ParticleCicProjectionParamsEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

