from __future__ import annotations

import flatbuffers
import numpy as np

import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class ParticleCicGridParams(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> ParticleCicGridParams: ...
  @classmethod
  def GetRootAsParticleCicGridParams(cls, buf: bytes, offset: int) -> ParticleCicGridParams: ...
  @classmethod
  def ParticleCicGridParamsBufferHasIdentifier(cls, buf: bytes, offset: int, size_prefixed: bool) -> bool: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def ParticleType(self) -> str | None: ...
  def LevelIndex(self) -> int: ...
  def Axis(self) -> int: ...
  def AxisBounds(self, i: int) -> typing.List[float]: ...
  def AxisBoundsAsNumpy(self) -> np.ndarray: ...
  def AxisBoundsLength(self) -> int: ...
  def AxisBoundsIsNone(self) -> bool: ...
  def MassMax(self) -> float: ...
  def HasMassMax(self) -> bool: ...
class ParticleCicGridParamsT(object):
  particleType: str | None
  levelIndex: int
  axis: int
  axisBounds: typing.List[float]
  massMax: float
  hasMassMax: bool
  def __init__(
    self,
    particleType: str | None = ...,
    levelIndex: int = ...,
    axis: int = ...,
    axisBounds: typing.List[float] | None = ...,
    massMax: float = ...,
    hasMassMax: bool = ...,
  ) -> None: ...
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> ParticleCicGridParamsT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> ParticleCicGridParamsT: ...
  @classmethod
  def InitFromObj(cls, particleCicGridParams: ParticleCicGridParams) -> ParticleCicGridParamsT: ...
  def _UnPack(self, particleCicGridParams: ParticleCicGridParams) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def ParticleCicGridParamsStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def ParticleCicGridParamsAddParticleType(builder: flatbuffers.Builder, particleType: uoffset) -> None: ...
def ParticleCicGridParamsAddLevelIndex(builder: flatbuffers.Builder, levelIndex: int) -> None: ...
def ParticleCicGridParamsAddAxis(builder: flatbuffers.Builder, axis: int) -> None: ...
def ParticleCicGridParamsAddAxisBounds(builder: flatbuffers.Builder, axisBounds: uoffset) -> None: ...
def ParticleCicGridParamsStartAxisBoundsVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartAxisBoundsVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def ParticleCicGridParamsAddMassMax(builder: flatbuffers.Builder, massMax: float) -> None: ...
def ParticleCicGridParamsAddHasMassMax(builder: flatbuffers.Builder, hasMassMax: bool) -> None: ...
def ParticleCicGridParamsEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

