# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fb

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from typing import Optional
np = import_numpy()

class ParticleCicProjectionParams(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ParticleCicProjectionParams()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsParticleCicProjectionParams(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def ParticleCicProjectionParamsBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x4B\x50\x4C\x4E", size_prefixed=size_prefixed)

    # ParticleCicProjectionParams
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ParticleCicProjectionParams
    def ParticleType(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ParticleCicProjectionParams
    def LevelIndex(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return -1

    # ParticleCicProjectionParams
    def Axis(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 2

    # ParticleCicProjectionParams
    def AxisBounds(self, j: int):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Float64Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 8))
        return 0

    # ParticleCicProjectionParams
    def AxisBoundsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float64Flags, o)
        return 0

    # ParticleCicProjectionParams
    def AxisBoundsLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ParticleCicProjectionParams
    def AxisBoundsIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        return o == 0

    # ParticleCicProjectionParams
    def Rect(self, j: int):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Float64Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 8))
        return 0

    # ParticleCicProjectionParams
    def RectAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float64Flags, o)
        return 0

    # ParticleCicProjectionParams
    def RectLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ParticleCicProjectionParams
    def RectIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        return o == 0

    # ParticleCicProjectionParams
    def Resolution(self, j: int):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # ParticleCicProjectionParams
    def ResolutionAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # ParticleCicProjectionParams
    def ResolutionLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ParticleCicProjectionParams
    def ResolutionIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        return o == 0

    # ParticleCicProjectionParams
    def MassMax(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # ParticleCicProjectionParams
    def HasMassMax(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def ParticleCicProjectionParamsStart(builder: flatbuffers.Builder):
    builder.StartObject(8)

def Start(builder: flatbuffers.Builder):
    ParticleCicProjectionParamsStart(builder)

def ParticleCicProjectionParamsAddParticleType(builder: flatbuffers.Builder, particleType: int):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(particleType), 0)

def AddParticleType(builder: flatbuffers.Builder, particleType: int):
    ParticleCicProjectionParamsAddParticleType(builder, particleType)

def ParticleCicProjectionParamsAddLevelIndex(builder: flatbuffers.Builder, levelIndex: int):
    builder.PrependInt32Slot(1, levelIndex, -1)

def AddLevelIndex(builder: flatbuffers.Builder, levelIndex: int):
    ParticleCicProjectionParamsAddLevelIndex(builder, levelIndex)

def ParticleCicProjectionParamsAddAxis(builder: flatbuffers.Builder, axis: int):
    builder.PrependInt32Slot(2, axis, 2)

def AddAxis(builder: flatbuffers.Builder, axis: int):
    ParticleCicProjectionParamsAddAxis(builder, axis)

def ParticleCicProjectionParamsAddAxisBounds(builder: flatbuffers.Builder, axisBounds: int):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(axisBounds), 0)

def AddAxisBounds(builder: flatbuffers.Builder, axisBounds: int):
    ParticleCicProjectionParamsAddAxisBounds(builder, axisBounds)

def ParticleCicProjectionParamsStartAxisBoundsVector(builder, numElems: int) -> int:
    return builder.StartVector(8, numElems, 8)

def StartAxisBoundsVector(builder, numElems: int) -> int:
    return ParticleCicProjectionParamsStartAxisBoundsVector(builder, numElems)

def ParticleCicProjectionParamsAddRect(builder: flatbuffers.Builder, rect: int):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(rect), 0)

def AddRect(builder: flatbuffers.Builder, rect: int):
    ParticleCicProjectionParamsAddRect(builder, rect)

def ParticleCicProjectionParamsStartRectVector(builder, numElems: int) -> int:
    return builder.StartVector(8, numElems, 8)

def StartRectVector(builder, numElems: int) -> int:
    return ParticleCicProjectionParamsStartRectVector(builder, numElems)

def ParticleCicProjectionParamsAddResolution(builder: flatbuffers.Builder, resolution: int):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(resolution), 0)

def AddResolution(builder: flatbuffers.Builder, resolution: int):
    ParticleCicProjectionParamsAddResolution(builder, resolution)

def ParticleCicProjectionParamsStartResolutionVector(builder, numElems: int) -> int:
    return builder.StartVector(4, numElems, 4)

def StartResolutionVector(builder, numElems: int) -> int:
    return ParticleCicProjectionParamsStartResolutionVector(builder, numElems)

def ParticleCicProjectionParamsAddMassMax(builder: flatbuffers.Builder, massMax: float):
    builder.PrependFloat64Slot(6, massMax, 0.0)

def AddMassMax(builder: flatbuffers.Builder, massMax: float):
    ParticleCicProjectionParamsAddMassMax(builder, massMax)

def ParticleCicProjectionParamsAddHasMassMax(builder: flatbuffers.Builder, hasMassMax: bool):
    builder.PrependBoolSlot(7, hasMassMax, 0)

def AddHasMassMax(builder: flatbuffers.Builder, hasMassMax: bool):
    ParticleCicProjectionParamsAddHasMassMax(builder, hasMassMax)

def ParticleCicProjectionParamsEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return ParticleCicProjectionParamsEnd(builder)

try:
    from typing import List
except:
    pass

class ParticleCicProjectionParamsT(object):

    # ParticleCicProjectionParamsT
    def __init__(
        self,
        particleType = None,
        levelIndex = -1,
        axis = 2,
        axisBounds = None,
        rect = None,
        resolution = None,
        massMax = 0.0,
        hasMassMax = False,
    ):
        self.particleType = particleType  # type: Optional[str]
        self.levelIndex = levelIndex  # type: int
        self.axis = axis  # type: int
        self.axisBounds = axisBounds  # type: Optional[List[float]]
        self.rect = rect  # type: Optional[List[float]]
        self.resolution = resolution  # type: Optional[List[int]]
        self.massMax = massMax  # type: float
        self.hasMassMax = hasMassMax  # type: bool

    @classmethod
    def InitFromBuf(cls, buf, pos):
        particleCicProjectionParams = ParticleCicProjectionParams()
        particleCicProjectionParams.Init(buf, pos)
        return cls.InitFromObj(particleCicProjectionParams)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, particleCicProjectionParams):
        x = ParticleCicProjectionParamsT()
        x._UnPack(particleCicProjectionParams)
        return x

    # ParticleCicProjectionParamsT
    def _UnPack(self, particleCicProjectionParams):
        if particleCicProjectionParams is None:
            return
        self.particleType = particleCicProjectionParams.ParticleType()
        self.levelIndex = particleCicProjectionParams.LevelIndex()
        self.axis = particleCicProjectionParams.Axis()
        if not particleCicProjectionParams.AxisBoundsIsNone():
            if np is None:
                self.axisBounds = []
                for i in range(particleCicProjectionParams.AxisBoundsLength()):
                    self.axisBounds.append(particleCicProjectionParams.AxisBounds(i))
            else:
                self.axisBounds = particleCicProjectionParams.AxisBoundsAsNumpy()
        if not particleCicProjectionParams.RectIsNone():
            if np is None:
                self.rect = []
                for i in range(particleCicProjectionParams.RectLength()):
                    self.rect.append(particleCicProjectionParams.Rect(i))
            else:
                self.rect = particleCicProjectionParams.RectAsNumpy()
        if not particleCicProjectionParams.ResolutionIsNone():
            if np is None:
                self.resolution = []
                for i in range(particleCicProjectionParams.ResolutionLength()):
                    self.resolution.append(particleCicProjectionParams.Resolution(i))
            else:
                self.resolution = particleCicProjectionParams.ResolutionAsNumpy()
        self.massMax = particleCicProjectionParams.MassMax()
        self.hasMassMax = particleCicProjectionParams.HasMassMax()

    # ParticleCicProjectionParamsT
    def Pack(self, builder):
        if self.particleType is not None:
            particleType = builder.CreateString(self.particleType)
        if self.axisBounds is not None:
            if np is not None and type(self.axisBounds) is np.ndarray:
                axisBounds = builder.CreateNumpyVector(self.axisBounds)
            else:
                ParticleCicProjectionParamsStartAxisBoundsVector(builder, len(self.axisBounds))
                for i in reversed(range(len(self.axisBounds))):
                    builder.PrependFloat64(self.axisBounds[i])
                axisBounds = builder.EndVector()
        if self.rect is not None:
            if np is not None and type(self.rect) is np.ndarray:
                rect = builder.CreateNumpyVector(self.rect)
            else:
                ParticleCicProjectionParamsStartRectVector(builder, len(self.rect))
                for i in reversed(range(len(self.rect))):
                    builder.PrependFloat64(self.rect[i])
                rect = builder.EndVector()
        if self.resolution is not None:
            if np is not None and type(self.resolution) is np.ndarray:
                resolution = builder.CreateNumpyVector(self.resolution)
            else:
                ParticleCicProjectionParamsStartResolutionVector(builder, len(self.resolution))
                for i in reversed(range(len(self.resolution))):
                    builder.PrependInt32(self.resolution[i])
                resolution = builder.EndVector()
        ParticleCicProjectionParamsStart(builder)
        if self.particleType is not None:
            ParticleCicProjectionParamsAddParticleType(builder, particleType)
        ParticleCicProjectionParamsAddLevelIndex(builder, self.levelIndex)
        ParticleCicProjectionParamsAddAxis(builder, self.axis)
        if self.axisBounds is not None:
            ParticleCicProjectionParamsAddAxisBounds(builder, axisBounds)
        if self.rect is not None:
            ParticleCicProjectionParamsAddRect(builder, rect)
        if self.resolution is not None:
            ParticleCicProjectionParamsAddResolution(builder, resolution)
        ParticleCicProjectionParamsAddMassMax(builder, self.massMax)
        ParticleCicProjectionParamsAddHasMassMax(builder, self.hasMassMax)
        particleCicProjectionParams = ParticleCicProjectionParamsEnd(builder)
        return particleCicProjectionParams
