# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fb

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from typing import Optional
np = import_numpy()

class ParticleFieldParams(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ParticleFieldParams()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsParticleFieldParams(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def ParticleFieldParamsBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x4B\x50\x4C\x4E", size_prefixed=size_prefixed)

    # ParticleFieldParams
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ParticleFieldParams
    def ParticleType(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ParticleFieldParams
    def FieldName(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def ParticleFieldParamsStart(builder: flatbuffers.Builder):
    builder.StartObject(2)

def Start(builder: flatbuffers.Builder):
    ParticleFieldParamsStart(builder)

def ParticleFieldParamsAddParticleType(builder: flatbuffers.Builder, particleType: int):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(particleType), 0)

def AddParticleType(builder: flatbuffers.Builder, particleType: int):
    ParticleFieldParamsAddParticleType(builder, particleType)

def ParticleFieldParamsAddFieldName(builder: flatbuffers.Builder, fieldName: int):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(fieldName), 0)

def AddFieldName(builder: flatbuffers.Builder, fieldName: int):
    ParticleFieldParamsAddFieldName(builder, fieldName)

def ParticleFieldParamsEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return ParticleFieldParamsEnd(builder)


class ParticleFieldParamsT(object):

    # ParticleFieldParamsT
    def __init__(
        self,
        particleType = None,
        fieldName = None,
    ):
        self.particleType = particleType  # type: Optional[str]
        self.fieldName = fieldName  # type: Optional[str]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        particleFieldParams = ParticleFieldParams()
        particleFieldParams.Init(buf, pos)
        return cls.InitFromObj(particleFieldParams)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, particleFieldParams):
        x = ParticleFieldParamsT()
        x._UnPack(particleFieldParams)
        return x

    # ParticleFieldParamsT
    def _UnPack(self, particleFieldParams):
        if particleFieldParams is None:
            return
        self.particleType = particleFieldParams.ParticleType()
        self.fieldName = particleFieldParams.FieldName()

    # ParticleFieldParamsT
    def Pack(self, builder):
        if self.particleType is not None:
            particleType = builder.CreateString(self.particleType)
        if self.fieldName is not None:
            fieldName = builder.CreateString(self.fieldName)
        ParticleFieldParamsStart(builder)
        if self.particleType is not None:
            ParticleFieldParamsAddParticleType(builder, particleType)
        if self.fieldName is not None:
            ParticleFieldParamsAddFieldName(builder, fieldName)
        particleFieldParams = ParticleFieldParamsEnd(builder)
        return particleFieldParams
