# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fb

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from typing import Optional
np = import_numpy()

class ParticleCicGridParams(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ParticleCicGridParams()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsParticleCicGridParams(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def ParticleCicGridParamsBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x4B\x50\x4C\x4E", size_prefixed=size_prefixed)

    # ParticleCicGridParams
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ParticleCicGridParams
    def ParticleType(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ParticleCicGridParams
    def LevelIndex(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return -1

    # ParticleCicGridParams
    def Axis(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 2

    # ParticleCicGridParams
    def AxisBounds(self, j: int):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Float64Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 8))
        return 0

    # ParticleCicGridParams
    def AxisBoundsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float64Flags, o)
        return 0

    # ParticleCicGridParams
    def AxisBoundsLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ParticleCicGridParams
    def AxisBoundsIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        return o == 0

    # ParticleCicGridParams
    def MassMax(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # ParticleCicGridParams
    def HasMassMax(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def ParticleCicGridParamsStart(builder: flatbuffers.Builder):
    builder.StartObject(6)

def Start(builder: flatbuffers.Builder):
    ParticleCicGridParamsStart(builder)

def ParticleCicGridParamsAddParticleType(builder: flatbuffers.Builder, particleType: int):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(particleType), 0)

def AddParticleType(builder: flatbuffers.Builder, particleType: int):
    ParticleCicGridParamsAddParticleType(builder, particleType)

def ParticleCicGridParamsAddLevelIndex(builder: flatbuffers.Builder, levelIndex: int):
    builder.PrependInt32Slot(1, levelIndex, -1)

def AddLevelIndex(builder: flatbuffers.Builder, levelIndex: int):
    ParticleCicGridParamsAddLevelIndex(builder, levelIndex)

def ParticleCicGridParamsAddAxis(builder: flatbuffers.Builder, axis: int):
    builder.PrependInt32Slot(2, axis, 2)

def AddAxis(builder: flatbuffers.Builder, axis: int):
    ParticleCicGridParamsAddAxis(builder, axis)

def ParticleCicGridParamsAddAxisBounds(builder: flatbuffers.Builder, axisBounds: int):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(axisBounds), 0)

def AddAxisBounds(builder: flatbuffers.Builder, axisBounds: int):
    ParticleCicGridParamsAddAxisBounds(builder, axisBounds)

def ParticleCicGridParamsStartAxisBoundsVector(builder, numElems: int) -> int:
    return builder.StartVector(8, numElems, 8)

def StartAxisBoundsVector(builder, numElems: int) -> int:
    return ParticleCicGridParamsStartAxisBoundsVector(builder, numElems)

def ParticleCicGridParamsAddMassMax(builder: flatbuffers.Builder, massMax: float):
    builder.PrependFloat64Slot(4, massMax, 0.0)

def AddMassMax(builder: flatbuffers.Builder, massMax: float):
    ParticleCicGridParamsAddMassMax(builder, massMax)

def ParticleCicGridParamsAddHasMassMax(builder: flatbuffers.Builder, hasMassMax: bool):
    builder.PrependBoolSlot(5, hasMassMax, 0)

def AddHasMassMax(builder: flatbuffers.Builder, hasMassMax: bool):
    ParticleCicGridParamsAddHasMassMax(builder, hasMassMax)

def ParticleCicGridParamsEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return ParticleCicGridParamsEnd(builder)

try:
    from typing import List
except:
    pass

class ParticleCicGridParamsT(object):

    # ParticleCicGridParamsT
    def __init__(
        self,
        particleType = None,
        levelIndex = -1,
        axis = 2,
        axisBounds = None,
        massMax = 0.0,
        hasMassMax = False,
    ):
        self.particleType = particleType  # type: Optional[str]
        self.levelIndex = levelIndex  # type: int
        self.axis = axis  # type: int
        self.axisBounds = axisBounds  # type: Optional[List[float]]
        self.massMax = massMax  # type: float
        self.hasMassMax = hasMassMax  # type: bool

    @classmethod
    def InitFromBuf(cls, buf, pos):
        particleCicGridParams = ParticleCicGridParams()
        particleCicGridParams.Init(buf, pos)
        return cls.InitFromObj(particleCicGridParams)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, particleCicGridParams):
        x = ParticleCicGridParamsT()
        x._UnPack(particleCicGridParams)
        return x

    # ParticleCicGridParamsT
    def _UnPack(self, particleCicGridParams):
        if particleCicGridParams is None:
            return
        self.particleType = particleCicGridParams.ParticleType()
        self.levelIndex = particleCicGridParams.LevelIndex()
        self.axis = particleCicGridParams.Axis()
        if not particleCicGridParams.AxisBoundsIsNone():
            if np is None:
                self.axisBounds = []
                for i in range(particleCicGridParams.AxisBoundsLength()):
                    self.axisBounds.append(particleCicGridParams.AxisBounds(i))
            else:
                self.axisBounds = particleCicGridParams.AxisBoundsAsNumpy()
        self.massMax = particleCicGridParams.MassMax()
        self.hasMassMax = particleCicGridParams.HasMassMax()

    # ParticleCicGridParamsT
    def Pack(self, builder):
        if self.particleType is not None:
            particleType = builder.CreateString(self.particleType)
        if self.axisBounds is not None:
            if np is not None and type(self.axisBounds) is np.ndarray:
                axisBounds = builder.CreateNumpyVector(self.axisBounds)
            else:
                ParticleCicGridParamsStartAxisBoundsVector(builder, len(self.axisBounds))
                for i in reversed(range(len(self.axisBounds))):
                    builder.PrependFloat64(self.axisBounds[i])
                axisBounds = builder.EndVector()
        ParticleCicGridParamsStart(builder)
        if self.particleType is not None:
            ParticleCicGridParamsAddParticleType(builder, particleType)
        ParticleCicGridParamsAddLevelIndex(builder, self.levelIndex)
        ParticleCicGridParamsAddAxis(builder, self.axis)
        if self.axisBounds is not None:
            ParticleCicGridParamsAddAxisBounds(builder, axisBounds)
        ParticleCicGridParamsAddMassMax(builder, self.massMax)
        ParticleCicGridParamsAddHasMassMax(builder, self.hasMassMax)
        particleCicGridParams = ParticleCicGridParamsEnd(builder)
        return particleCicGridParams
