# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fb

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from analysis.fb.CoveredBoxList import CoveredBoxList
from analysis.fb.Stage import Stage
from typing import Optional
np = import_numpy()

class Plan(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Plan()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsPlan(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def PlanBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x4B\x50\x4C\x4E", size_prefixed=size_prefixed)

    # Plan
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Plan
    def Stages(self, j: int) -> Optional[Stage]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = Stage()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Plan
    def StagesLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Plan
    def StagesIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

    # Plan
    def SharedCoveredBoxes(self, j: int) -> Optional[CoveredBoxList]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = CoveredBoxList()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Plan
    def SharedCoveredBoxesLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Plan
    def SharedCoveredBoxesIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

def PlanStart(builder: flatbuffers.Builder):
    builder.StartObject(2)

def Start(builder: flatbuffers.Builder):
    PlanStart(builder)

def PlanAddStages(builder: flatbuffers.Builder, stages: int):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(stages), 0)

def AddStages(builder: flatbuffers.Builder, stages: int):
    PlanAddStages(builder, stages)

def PlanStartStagesVector(builder, numElems: int) -> int:
    return builder.StartVector(4, numElems, 4)

def StartStagesVector(builder, numElems: int) -> int:
    return PlanStartStagesVector(builder, numElems)

def PlanAddSharedCoveredBoxes(builder: flatbuffers.Builder, sharedCoveredBoxes: int):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(sharedCoveredBoxes), 0)

def AddSharedCoveredBoxes(builder: flatbuffers.Builder, sharedCoveredBoxes: int):
    PlanAddSharedCoveredBoxes(builder, sharedCoveredBoxes)

def PlanStartSharedCoveredBoxesVector(builder, numElems: int) -> int:
    return builder.StartVector(4, numElems, 4)

def StartSharedCoveredBoxesVector(builder, numElems: int) -> int:
    return PlanStartSharedCoveredBoxesVector(builder, numElems)

def PlanEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return PlanEnd(builder)

import analysis.fb.CoveredBoxList
import analysis.fb.Stage
try:
    from typing import List
except:
    pass

class PlanT(object):

    # PlanT
    def __init__(
        self,
        stages = None,
        sharedCoveredBoxes = None,
    ):
        self.stages = stages  # type: Optional[List[analysis.fb.Stage.StageT]]
        self.sharedCoveredBoxes = sharedCoveredBoxes  # type: Optional[List[analysis.fb.CoveredBoxList.CoveredBoxListT]]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        plan = Plan()
        plan.Init(buf, pos)
        return cls.InitFromObj(plan)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, plan):
        x = PlanT()
        x._UnPack(plan)
        return x

    # PlanT
    def _UnPack(self, plan):
        if plan is None:
            return
        if not plan.StagesIsNone():
            self.stages = []
            for i in range(plan.StagesLength()):
                if plan.Stages(i) is None:
                    self.stages.append(None)
                else:
                    stage_ = analysis.fb.Stage.StageT.InitFromObj(plan.Stages(i))
                    self.stages.append(stage_)
        if not plan.SharedCoveredBoxesIsNone():
            self.sharedCoveredBoxes = []
            for i in range(plan.SharedCoveredBoxesLength()):
                if plan.SharedCoveredBoxes(i) is None:
                    self.sharedCoveredBoxes.append(None)
                else:
                    coveredBoxList_ = analysis.fb.CoveredBoxList.CoveredBoxListT.InitFromObj(plan.SharedCoveredBoxes(i))
                    self.sharedCoveredBoxes.append(coveredBoxList_)

    # PlanT
    def Pack(self, builder):
        if self.stages is not None:
            stageslist = []
            for i in range(len(self.stages)):
                stageslist.append(self.stages[i].Pack(builder))
            PlanStartStagesVector(builder, len(self.stages))
            for i in reversed(range(len(self.stages))):
                builder.PrependUOffsetTRelative(stageslist[i])
            stages = builder.EndVector()
        if self.sharedCoveredBoxes is not None:
            sharedCoveredBoxeslist = []
            for i in range(len(self.sharedCoveredBoxes)):
                sharedCoveredBoxeslist.append(self.sharedCoveredBoxes[i].Pack(builder))
            PlanStartSharedCoveredBoxesVector(builder, len(self.sharedCoveredBoxes))
            for i in reversed(range(len(self.sharedCoveredBoxes))):
                builder.PrependUOffsetTRelative(sharedCoveredBoxeslist[i])
            sharedCoveredBoxes = builder.EndVector()
        PlanStart(builder)
        if self.stages is not None:
            PlanAddStages(builder, stages)
        if self.sharedCoveredBoxes is not None:
            PlanAddSharedCoveredBoxes(builder, sharedCoveredBoxes)
        plan = PlanEnd(builder)
        return plan
