from __future__ import annotations

import flatbuffers
import numpy as np

import typing
from analysis.fb.CoveredBoxList import CoveredBoxList, CoveredBoxListT
from analysis.fb.Stage import Stage, StageT

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Plan(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Plan: ...
  @classmethod
  def GetRootAsPlan(cls, buf: bytes, offset: int) -> Plan: ...
  @classmethod
  def PlanBufferHasIdentifier(cls, buf: bytes, offset: int, size_prefixed: bool) -> bool: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Stages(self, i: int) -> Stage | None: ...
  def StagesLength(self) -> int: ...
  def StagesIsNone(self) -> bool: ...
  def SharedCoveredBoxes(self, i: int) -> CoveredBoxList | None: ...
  def SharedCoveredBoxesLength(self) -> int: ...
  def SharedCoveredBoxesIsNone(self) -> bool: ...
class PlanT(object):
  stages: typing.List[StageT]
  sharedCoveredBoxes: typing.List[CoveredBoxListT]
  def __init__(
    self,
    stages: typing.List['StageT'] | None = ...,
    sharedCoveredBoxes: typing.List['CoveredBoxListT'] | None = ...,
  ) -> None: ...
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> PlanT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> PlanT: ...
  @classmethod
  def InitFromObj(cls, plan: Plan) -> PlanT: ...
  def _UnPack(self, plan: Plan) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def PlanStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def PlanAddStages(builder: flatbuffers.Builder, stages: uoffset) -> None: ...
def PlanStartStagesVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartStagesVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def PlanAddSharedCoveredBoxes(builder: flatbuffers.Builder, sharedCoveredBoxes: uoffset) -> None: ...
def PlanStartSharedCoveredBoxesVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartSharedCoveredBoxesVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def PlanEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

