from __future__ import annotations

import flatbuffers
import numpy as np

import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class PlotfileLoadParams(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> PlotfileLoadParams: ...
  @classmethod
  def GetRootAsPlotfileLoadParams(cls, buf: bytes, offset: int) -> PlotfileLoadParams: ...
  @classmethod
  def PlotfileLoadParamsBufferHasIdentifier(cls, buf: bytes, offset: int, size_prefixed: bool) -> bool: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Plotfile(self) -> str | None: ...
  def Level(self) -> int: ...
  def Comp(self) -> int: ...
class PlotfileLoadParamsT(object):
  plotfile: str | None
  level: int
  comp: int
  def __init__(
    self,
    plotfile: str | None = ...,
    level: int = ...,
    comp: int = ...,
  ) -> None: ...
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> PlotfileLoadParamsT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> PlotfileLoadParamsT: ...
  @classmethod
  def InitFromObj(cls, plotfileLoadParams: PlotfileLoadParams) -> PlotfileLoadParamsT: ...
  def _UnPack(self, plotfileLoadParams: PlotfileLoadParams) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def PlotfileLoadParamsStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def PlotfileLoadParamsAddPlotfile(builder: flatbuffers.Builder, plotfile: uoffset) -> None: ...
def PlotfileLoadParamsAddLevel(builder: flatbuffers.Builder, level: int) -> None: ...
def PlotfileLoadParamsAddComp(builder: flatbuffers.Builder, comp: int) -> None: ...
def PlotfileLoadParamsEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

