# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fb

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from typing import Optional
np = import_numpy()

class PlotfileLoadParams(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = PlotfileLoadParams()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsPlotfileLoadParams(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def PlotfileLoadParamsBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x4B\x50\x4C\x4E", size_prefixed=size_prefixed)

    # PlotfileLoadParams
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # PlotfileLoadParams
    def Plotfile(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # PlotfileLoadParams
    def Level(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # PlotfileLoadParams
    def Comp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def PlotfileLoadParamsStart(builder: flatbuffers.Builder):
    builder.StartObject(3)

def Start(builder: flatbuffers.Builder):
    PlotfileLoadParamsStart(builder)

def PlotfileLoadParamsAddPlotfile(builder: flatbuffers.Builder, plotfile: int):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(plotfile), 0)

def AddPlotfile(builder: flatbuffers.Builder, plotfile: int):
    PlotfileLoadParamsAddPlotfile(builder, plotfile)

def PlotfileLoadParamsAddLevel(builder: flatbuffers.Builder, level: int):
    builder.PrependInt32Slot(1, level, 0)

def AddLevel(builder: flatbuffers.Builder, level: int):
    PlotfileLoadParamsAddLevel(builder, level)

def PlotfileLoadParamsAddComp(builder: flatbuffers.Builder, comp: int):
    builder.PrependInt32Slot(2, comp, 0)

def AddComp(builder: flatbuffers.Builder, comp: int):
    PlotfileLoadParamsAddComp(builder, comp)

def PlotfileLoadParamsEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return PlotfileLoadParamsEnd(builder)


class PlotfileLoadParamsT(object):

    # PlotfileLoadParamsT
    def __init__(
        self,
        plotfile = None,
        level = 0,
        comp = 0,
    ):
        self.plotfile = plotfile  # type: Optional[str]
        self.level = level  # type: int
        self.comp = comp  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        plotfileLoadParams = PlotfileLoadParams()
        plotfileLoadParams.Init(buf, pos)
        return cls.InitFromObj(plotfileLoadParams)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, plotfileLoadParams):
        x = PlotfileLoadParamsT()
        x._UnPack(plotfileLoadParams)
        return x

    # PlotfileLoadParamsT
    def _UnPack(self, plotfileLoadParams):
        if plotfileLoadParams is None:
            return
        self.plotfile = plotfileLoadParams.Plotfile()
        self.level = plotfileLoadParams.Level()
        self.comp = plotfileLoadParams.Comp()

    # PlotfileLoadParamsT
    def Pack(self, builder):
        if self.plotfile is not None:
            plotfile = builder.CreateString(self.plotfile)
        PlotfileLoadParamsStart(builder)
        if self.plotfile is not None:
            PlotfileLoadParamsAddPlotfile(builder, plotfile)
        PlotfileLoadParamsAddLevel(builder, self.level)
        PlotfileLoadParamsAddComp(builder, self.comp)
        plotfileLoadParams = PlotfileLoadParamsEnd(builder)
        return plotfileLoadParams
