# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fb

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
np = import_numpy()

class ScalarParams(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ScalarParams()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsScalarParams(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def ScalarParamsBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x4B\x50\x4C\x4E", size_prefixed=size_prefixed)

    # ScalarParams
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ScalarParams
    def Scalar(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

def ScalarParamsStart(builder: flatbuffers.Builder):
    builder.StartObject(1)

def Start(builder: flatbuffers.Builder):
    ScalarParamsStart(builder)

def ScalarParamsAddScalar(builder: flatbuffers.Builder, scalar: float):
    builder.PrependFloat64Slot(0, scalar, 0.0)

def AddScalar(builder: flatbuffers.Builder, scalar: float):
    ScalarParamsAddScalar(builder, scalar)

def ScalarParamsEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return ScalarParamsEnd(builder)


class ScalarParamsT(object):

    # ScalarParamsT
    def __init__(
        self,
        scalar = 0.0,
    ):
        self.scalar = scalar  # type: float

    @classmethod
    def InitFromBuf(cls, buf, pos):
        scalarParams = ScalarParams()
        scalarParams.Init(buf, pos)
        return cls.InitFromObj(scalarParams)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, scalarParams):
        x = ScalarParamsT()
        x._UnPack(scalarParams)
        return x

    # ScalarParamsT
    def _UnPack(self, scalarParams):
        if scalarParams is None:
            return
        self.scalar = scalarParams.Scalar()

    # ScalarParamsT
    def Pack(self, builder):
        ScalarParamsStart(builder)
        ScalarParamsAddScalar(builder, self.scalar)
        scalarParams = ScalarParamsEnd(builder)
        return scalarParams
