from __future__ import annotations

import flatbuffers
import numpy as np

import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class ScalarParams(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> ScalarParams: ...
  @classmethod
  def GetRootAsScalarParams(cls, buf: bytes, offset: int) -> ScalarParams: ...
  @classmethod
  def ScalarParamsBufferHasIdentifier(cls, buf: bytes, offset: int, size_prefixed: bool) -> bool: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Scalar(self) -> float: ...
class ScalarParamsT(object):
  scalar: float
  def __init__(
    self,
    scalar: float = ...,
  ) -> None: ...
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> ScalarParamsT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> ScalarParamsT: ...
  @classmethod
  def InitFromObj(cls, scalarParams: ScalarParams) -> ScalarParamsT: ...
  def _UnPack(self, scalarParams: ScalarParams) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def ScalarParamsStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def ScalarParamsAddScalar(builder: flatbuffers.Builder, scalar: float) -> None: ...
def ScalarParamsEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

