from __future__ import annotations

import flatbuffers
import numpy as np

import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class SliceFinalizeParams(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> SliceFinalizeParams: ...
  @classmethod
  def GetRootAsSliceFinalizeParams(cls, buf: bytes, offset: int) -> SliceFinalizeParams: ...
  @classmethod
  def SliceFinalizeParamsBufferHasIdentifier(cls, buf: bytes, offset: int, size_prefixed: bool) -> bool: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def PixelArea(self) -> float: ...
class SliceFinalizeParamsT(object):
  pixelArea: float
  def __init__(
    self,
    pixelArea: float = ...,
  ) -> None: ...
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> SliceFinalizeParamsT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> SliceFinalizeParamsT: ...
  @classmethod
  def InitFromObj(cls, sliceFinalizeParams: SliceFinalizeParams) -> SliceFinalizeParamsT: ...
  def _UnPack(self, sliceFinalizeParams: SliceFinalizeParams) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def SliceFinalizeParamsStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def SliceFinalizeParamsAddPixelArea(builder: flatbuffers.Builder, pixelArea: float) -> None: ...
def SliceFinalizeParamsEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

