# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fb

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
np = import_numpy()

class SliceFinalizeParams(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SliceFinalizeParams()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSliceFinalizeParams(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def SliceFinalizeParamsBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x4B\x50\x4C\x4E", size_prefixed=size_prefixed)

    # SliceFinalizeParams
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SliceFinalizeParams
    def PixelArea(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 1.0

def SliceFinalizeParamsStart(builder: flatbuffers.Builder):
    builder.StartObject(1)

def Start(builder: flatbuffers.Builder):
    SliceFinalizeParamsStart(builder)

def SliceFinalizeParamsAddPixelArea(builder: flatbuffers.Builder, pixelArea: float):
    builder.PrependFloat64Slot(0, pixelArea, 1.0)

def AddPixelArea(builder: flatbuffers.Builder, pixelArea: float):
    SliceFinalizeParamsAddPixelArea(builder, pixelArea)

def SliceFinalizeParamsEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return SliceFinalizeParamsEnd(builder)


class SliceFinalizeParamsT(object):

    # SliceFinalizeParamsT
    def __init__(
        self,
        pixelArea = 1.0,
    ):
        self.pixelArea = pixelArea  # type: float

    @classmethod
    def InitFromBuf(cls, buf, pos):
        sliceFinalizeParams = SliceFinalizeParams()
        sliceFinalizeParams.Init(buf, pos)
        return cls.InitFromObj(sliceFinalizeParams)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, sliceFinalizeParams):
        x = SliceFinalizeParamsT()
        x._UnPack(sliceFinalizeParams)
        return x

    # SliceFinalizeParamsT
    def _UnPack(self, sliceFinalizeParams):
        if sliceFinalizeParams is None:
            return
        self.pixelArea = sliceFinalizeParams.PixelArea()

    # SliceFinalizeParamsT
    def Pack(self, builder):
        SliceFinalizeParamsStart(builder)
        SliceFinalizeParamsAddPixelArea(builder, self.pixelArea)
        sliceFinalizeParams = SliceFinalizeParamsEnd(builder)
        return sliceFinalizeParams
