# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fb

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from analysis.fb.TaskTemplate import TaskTemplate
from typing import Optional
np = import_numpy()

class Stage(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Stage()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsStage(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def StageBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x4B\x50\x4C\x4E", size_prefixed=size_prefixed)

    # Stage
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Stage
    def Name(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Stage
    def Plane(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # Stage
    def After(self, j: int):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # Stage
    def AfterAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # Stage
    def AfterLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Stage
    def AfterIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

    # Stage
    def Templates(self, j: int) -> Optional[TaskTemplate]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = TaskTemplate()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Stage
    def TemplatesLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Stage
    def TemplatesIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        return o == 0

def StageStart(builder: flatbuffers.Builder):
    builder.StartObject(4)

def Start(builder: flatbuffers.Builder):
    StageStart(builder)

def StageAddName(builder: flatbuffers.Builder, name: int):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(name), 0)

def AddName(builder: flatbuffers.Builder, name: int):
    StageAddName(builder, name)

def StageAddPlane(builder: flatbuffers.Builder, plane: int):
    builder.PrependUint8Slot(1, plane, 0)

def AddPlane(builder: flatbuffers.Builder, plane: int):
    StageAddPlane(builder, plane)

def StageAddAfter(builder: flatbuffers.Builder, after: int):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(after), 0)

def AddAfter(builder: flatbuffers.Builder, after: int):
    StageAddAfter(builder, after)

def StageStartAfterVector(builder, numElems: int) -> int:
    return builder.StartVector(4, numElems, 4)

def StartAfterVector(builder, numElems: int) -> int:
    return StageStartAfterVector(builder, numElems)

def StageAddTemplates(builder: flatbuffers.Builder, templates: int):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(templates), 0)

def AddTemplates(builder: flatbuffers.Builder, templates: int):
    StageAddTemplates(builder, templates)

def StageStartTemplatesVector(builder, numElems: int) -> int:
    return builder.StartVector(4, numElems, 4)

def StartTemplatesVector(builder, numElems: int) -> int:
    return StageStartTemplatesVector(builder, numElems)

def StageEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return StageEnd(builder)

import analysis.fb.TaskTemplate
try:
    from typing import List
except:
    pass

class StageT(object):

    # StageT
    def __init__(
        self,
        name = None,
        plane = 0,
        after = None,
        templates = None,
    ):
        self.name = name  # type: Optional[str]
        self.plane = plane  # type: int
        self.after = after  # type: Optional[List[int]]
        self.templates = templates  # type: Optional[List[analysis.fb.TaskTemplate.TaskTemplateT]]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        stage = Stage()
        stage.Init(buf, pos)
        return cls.InitFromObj(stage)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, stage):
        x = StageT()
        x._UnPack(stage)
        return x

    # StageT
    def _UnPack(self, stage):
        if stage is None:
            return
        self.name = stage.Name()
        self.plane = stage.Plane()
        if not stage.AfterIsNone():
            if np is None:
                self.after = []
                for i in range(stage.AfterLength()):
                    self.after.append(stage.After(i))
            else:
                self.after = stage.AfterAsNumpy()
        if not stage.TemplatesIsNone():
            self.templates = []
            for i in range(stage.TemplatesLength()):
                if stage.Templates(i) is None:
                    self.templates.append(None)
                else:
                    taskTemplate_ = analysis.fb.TaskTemplate.TaskTemplateT.InitFromObj(stage.Templates(i))
                    self.templates.append(taskTemplate_)

    # StageT
    def Pack(self, builder):
        if self.name is not None:
            name = builder.CreateString(self.name)
        if self.after is not None:
            if np is not None and type(self.after) is np.ndarray:
                after = builder.CreateNumpyVector(self.after)
            else:
                StageStartAfterVector(builder, len(self.after))
                for i in reversed(range(len(self.after))):
                    builder.PrependInt32(self.after[i])
                after = builder.EndVector()
        if self.templates is not None:
            templateslist = []
            for i in range(len(self.templates)):
                templateslist.append(self.templates[i].Pack(builder))
            StageStartTemplatesVector(builder, len(self.templates))
            for i in reversed(range(len(self.templates))):
                builder.PrependUOffsetTRelative(templateslist[i])
            templates = builder.EndVector()
        StageStart(builder)
        if self.name is not None:
            StageAddName(builder, name)
        StageAddPlane(builder, self.plane)
        if self.after is not None:
            StageAddAfter(builder, after)
        if self.templates is not None:
            StageAddTemplates(builder, templates)
        stage = StageEnd(builder)
        return stage
