from __future__ import annotations

import flatbuffers
import numpy as np

import typing
from analysis.fb.ExecPlane import ExecPlane
from analysis.fb.TaskTemplate import TaskTemplate, TaskTemplateT

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Stage(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Stage: ...
  @classmethod
  def GetRootAsStage(cls, buf: bytes, offset: int) -> Stage: ...
  @classmethod
  def StageBufferHasIdentifier(cls, buf: bytes, offset: int, size_prefixed: bool) -> bool: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Name(self) -> str | None: ...
  def Plane(self) -> typing.Literal[ExecPlane.Chunk, ExecPlane.Graph, ExecPlane.Mixed]: ...
  def After(self, i: int) -> typing.List[int]: ...
  def AfterAsNumpy(self) -> np.ndarray: ...
  def AfterLength(self) -> int: ...
  def AfterIsNone(self) -> bool: ...
  def Templates(self, i: int) -> TaskTemplate | None: ...
  def TemplatesLength(self) -> int: ...
  def TemplatesIsNone(self) -> bool: ...
class StageT(object):
  name: str | None
  plane: typing.Literal[ExecPlane.Chunk, ExecPlane.Graph, ExecPlane.Mixed]
  after: typing.List[int]
  templates: typing.List[TaskTemplateT]
  def __init__(
    self,
    name: str | None = ...,
    plane: typing.Literal[ExecPlane.Chunk, ExecPlane.Graph, ExecPlane.Mixed] = ...,
    after: typing.List[int] | None = ...,
    templates: typing.List['TaskTemplateT'] | None = ...,
  ) -> None: ...
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> StageT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> StageT: ...
  @classmethod
  def InitFromObj(cls, stage: Stage) -> StageT: ...
  def _UnPack(self, stage: Stage) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def StageStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def StageAddName(builder: flatbuffers.Builder, name: uoffset) -> None: ...
def StageAddPlane(builder: flatbuffers.Builder, plane: typing.Literal[ExecPlane.Chunk, ExecPlane.Graph, ExecPlane.Mixed]) -> None: ...
def StageAddAfter(builder: flatbuffers.Builder, after: uoffset) -> None: ...
def StageStartAfterVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartAfterVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StageAddTemplates(builder: flatbuffers.Builder, templates: uoffset) -> None: ...
def StageStartTemplatesVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartTemplatesVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StageEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

