# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fb

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from analysis.fb.DependencyRule import DependencyRule
from analysis.fb.Domain import Domain
from analysis.fb.FieldRef import FieldRef
from analysis.fb.GraphReduceSpec import GraphReduceSpec
from analysis.fb.OutputRef import OutputRef
from flatbuffers.table import Table
from typing import Optional
np = import_numpy()

class TaskTemplate(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = TaskTemplate()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsTaskTemplate(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def TaskTemplateBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x4B\x50\x4C\x4E", size_prefixed=size_prefixed)

    # TaskTemplate
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # TaskTemplate
    def Name(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # TaskTemplate
    def Plane(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # TaskTemplate
    def Kernel(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # TaskTemplate
    def Domain(self) -> Optional[Domain]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = Domain()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # TaskTemplate
    def Inputs(self, j: int) -> Optional[FieldRef]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = FieldRef()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # TaskTemplate
    def InputsLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # TaskTemplate
    def InputsIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        return o == 0

    # TaskTemplate
    def Outputs(self, j: int) -> Optional[OutputRef]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = OutputRef()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # TaskTemplate
    def OutputsLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # TaskTemplate
    def OutputsIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        return o == 0

    # TaskTemplate
    def Deps(self) -> Optional[DependencyRule]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = DependencyRule()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # TaskTemplate
    def CoveredBoxesRef(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return -1

    # TaskTemplate
    def GraphReduce(self) -> Optional[GraphReduceSpec]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = GraphReduceSpec()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # TaskTemplate
    def ParamsType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # TaskTemplate
    def Params(self) -> Optional[flatbuffers.table.Table]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            obj = Table(bytearray(), 0)
            self._tab.Union(obj, o)
            return obj
        return None

def TaskTemplateStart(builder: flatbuffers.Builder):
    builder.StartObject(11)

def Start(builder: flatbuffers.Builder):
    TaskTemplateStart(builder)

def TaskTemplateAddName(builder: flatbuffers.Builder, name: int):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(name), 0)

def AddName(builder: flatbuffers.Builder, name: int):
    TaskTemplateAddName(builder, name)

def TaskTemplateAddPlane(builder: flatbuffers.Builder, plane: int):
    builder.PrependUint8Slot(1, plane, 0)

def AddPlane(builder: flatbuffers.Builder, plane: int):
    TaskTemplateAddPlane(builder, plane)

def TaskTemplateAddKernel(builder: flatbuffers.Builder, kernel: int):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(kernel), 0)

def AddKernel(builder: flatbuffers.Builder, kernel: int):
    TaskTemplateAddKernel(builder, kernel)

def TaskTemplateAddDomain(builder: flatbuffers.Builder, domain: int):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(domain), 0)

def AddDomain(builder: flatbuffers.Builder, domain: int):
    TaskTemplateAddDomain(builder, domain)

def TaskTemplateAddInputs(builder: flatbuffers.Builder, inputs: int):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(inputs), 0)

def AddInputs(builder: flatbuffers.Builder, inputs: int):
    TaskTemplateAddInputs(builder, inputs)

def TaskTemplateStartInputsVector(builder, numElems: int) -> int:
    return builder.StartVector(4, numElems, 4)

def StartInputsVector(builder, numElems: int) -> int:
    return TaskTemplateStartInputsVector(builder, numElems)

def TaskTemplateAddOutputs(builder: flatbuffers.Builder, outputs: int):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(outputs), 0)

def AddOutputs(builder: flatbuffers.Builder, outputs: int):
    TaskTemplateAddOutputs(builder, outputs)

def TaskTemplateStartOutputsVector(builder, numElems: int) -> int:
    return builder.StartVector(4, numElems, 4)

def StartOutputsVector(builder, numElems: int) -> int:
    return TaskTemplateStartOutputsVector(builder, numElems)

def TaskTemplateAddDeps(builder: flatbuffers.Builder, deps: int):
    builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(deps), 0)

def AddDeps(builder: flatbuffers.Builder, deps: int):
    TaskTemplateAddDeps(builder, deps)

def TaskTemplateAddCoveredBoxesRef(builder: flatbuffers.Builder, coveredBoxesRef: int):
    builder.PrependInt32Slot(7, coveredBoxesRef, -1)

def AddCoveredBoxesRef(builder: flatbuffers.Builder, coveredBoxesRef: int):
    TaskTemplateAddCoveredBoxesRef(builder, coveredBoxesRef)

def TaskTemplateAddGraphReduce(builder: flatbuffers.Builder, graphReduce: int):
    builder.PrependUOffsetTRelativeSlot(8, flatbuffers.number_types.UOffsetTFlags.py_type(graphReduce), 0)

def AddGraphReduce(builder: flatbuffers.Builder, graphReduce: int):
    TaskTemplateAddGraphReduce(builder, graphReduce)

def TaskTemplateAddParamsType(builder: flatbuffers.Builder, paramsType: int):
    builder.PrependUint8Slot(9, paramsType, 0)

def AddParamsType(builder: flatbuffers.Builder, paramsType: int):
    TaskTemplateAddParamsType(builder, paramsType)

def TaskTemplateAddParams(builder: flatbuffers.Builder, params: int):
    builder.PrependUOffsetTRelativeSlot(10, flatbuffers.number_types.UOffsetTFlags.py_type(params), 0)

def AddParams(builder: flatbuffers.Builder, params: int):
    TaskTemplateAddParams(builder, params)

def TaskTemplateEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return TaskTemplateEnd(builder)

import analysis.fb.AmrSubboxPackParams
import analysis.fb.CylindricalFluxParams
import analysis.fb.DependencyRule
import analysis.fb.Domain
import analysis.fb.FieldExprParams
import analysis.fb.FieldRef
import analysis.fb.FiniteOnlyParams
import analysis.fb.FluxSurfaceParams
import analysis.fb.GradStencilParams
import analysis.fb.GraphReduceSpec
import analysis.fb.Histogram1DParams
import analysis.fb.Histogram2DParams
import analysis.fb.KernelParams
import analysis.fb.OutputRef
import analysis.fb.ParticleCicGridParams
import analysis.fb.ParticleCicProjectionParams
import analysis.fb.ParticleFieldParams
import analysis.fb.ParticleHistogramParams
import analysis.fb.PlotfileLoadParams
import analysis.fb.ScalarParams
import analysis.fb.SliceFinalizeParams
import analysis.fb.TopKModesParams
import analysis.fb.UniformProjectionParams
import analysis.fb.UniformSliceCellParams
import analysis.fb.UniformSliceParams
import analysis.fb.ValuesParams
try:
    from typing import List, Optional, Union
except:
    pass

class TaskTemplateT(object):

    # TaskTemplateT
    def __init__(
        self,
        name = None,
        plane = 0,
        kernel = None,
        domain = None,
        inputs = None,
        outputs = None,
        deps = None,
        coveredBoxesRef = -1,
        graphReduce = None,
        paramsType = 0,
        params = None,
    ):
        self.name = name  # type: Optional[str]
        self.plane = plane  # type: int
        self.kernel = kernel  # type: Optional[str]
        self.domain = domain  # type: Optional[analysis.fb.Domain.DomainT]
        self.inputs = inputs  # type: Optional[List[analysis.fb.FieldRef.FieldRefT]]
        self.outputs = outputs  # type: Optional[List[analysis.fb.OutputRef.OutputRefT]]
        self.deps = deps  # type: Optional[analysis.fb.DependencyRule.DependencyRuleT]
        self.coveredBoxesRef = coveredBoxesRef  # type: int
        self.graphReduce = graphReduce  # type: Optional[analysis.fb.GraphReduceSpec.GraphReduceSpecT]
        self.paramsType = paramsType  # type: int
        self.params = params  # type: Union[None, 'analysis.fb.AmrSubboxPackParams.AmrSubboxPackParamsT', 'analysis.fb.GradStencilParams.GradStencilParamsT', 'analysis.fb.PlotfileLoadParams.PlotfileLoadParamsT', 'analysis.fb.FluxSurfaceParams.FluxSurfaceParamsT', 'analysis.fb.CylindricalFluxParams.CylindricalFluxParamsT', 'analysis.fb.UniformSliceCellParams.UniformSliceCellParamsT', 'analysis.fb.UniformProjectionParams.UniformProjectionParamsT', 'analysis.fb.FieldExprParams.FieldExprParamsT', 'analysis.fb.UniformSliceParams.UniformSliceParamsT', 'analysis.fb.Histogram1DParams.Histogram1DParamsT', 'analysis.fb.Histogram2DParams.Histogram2DParamsT', 'analysis.fb.ParticleFieldParams.ParticleFieldParamsT', 'analysis.fb.ParticleCicGridParams.ParticleCicGridParamsT', 'analysis.fb.ParticleCicProjectionParams.ParticleCicProjectionParamsT', 'analysis.fb.ScalarParams.ScalarParamsT', 'analysis.fb.ValuesParams.ValuesParamsT', 'analysis.fb.FiniteOnlyParams.FiniteOnlyParamsT', 'analysis.fb.ParticleHistogramParams.ParticleHistogramParamsT', 'analysis.fb.TopKModesParams.TopKModesParamsT', 'analysis.fb.SliceFinalizeParams.SliceFinalizeParamsT']

    @classmethod
    def InitFromBuf(cls, buf, pos):
        taskTemplate = TaskTemplate()
        taskTemplate.Init(buf, pos)
        return cls.InitFromObj(taskTemplate)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, taskTemplate):
        x = TaskTemplateT()
        x._UnPack(taskTemplate)
        return x

    # TaskTemplateT
    def _UnPack(self, taskTemplate):
        if taskTemplate is None:
            return
        self.name = taskTemplate.Name()
        self.plane = taskTemplate.Plane()
        self.kernel = taskTemplate.Kernel()
        if taskTemplate.Domain() is not None:
            self.domain = analysis.fb.Domain.DomainT.InitFromObj(taskTemplate.Domain())
        if not taskTemplate.InputsIsNone():
            self.inputs = []
            for i in range(taskTemplate.InputsLength()):
                if taskTemplate.Inputs(i) is None:
                    self.inputs.append(None)
                else:
                    fieldRef_ = analysis.fb.FieldRef.FieldRefT.InitFromObj(taskTemplate.Inputs(i))
                    self.inputs.append(fieldRef_)
        if not taskTemplate.OutputsIsNone():
            self.outputs = []
            for i in range(taskTemplate.OutputsLength()):
                if taskTemplate.Outputs(i) is None:
                    self.outputs.append(None)
                else:
                    outputRef_ = analysis.fb.OutputRef.OutputRefT.InitFromObj(taskTemplate.Outputs(i))
                    self.outputs.append(outputRef_)
        if taskTemplate.Deps() is not None:
            self.deps = analysis.fb.DependencyRule.DependencyRuleT.InitFromObj(taskTemplate.Deps())
        self.coveredBoxesRef = taskTemplate.CoveredBoxesRef()
        if taskTemplate.GraphReduce() is not None:
            self.graphReduce = analysis.fb.GraphReduceSpec.GraphReduceSpecT.InitFromObj(taskTemplate.GraphReduce())
        self.paramsType = taskTemplate.ParamsType()
        self.params = analysis.fb.KernelParams.KernelParamsCreator(self.paramsType, taskTemplate.Params())

    # TaskTemplateT
    def Pack(self, builder):
        if self.name is not None:
            name = builder.CreateString(self.name)
        if self.kernel is not None:
            kernel = builder.CreateString(self.kernel)
        if self.domain is not None:
            domain = self.domain.Pack(builder)
        if self.inputs is not None:
            inputslist = []
            for i in range(len(self.inputs)):
                inputslist.append(self.inputs[i].Pack(builder))
            TaskTemplateStartInputsVector(builder, len(self.inputs))
            for i in reversed(range(len(self.inputs))):
                builder.PrependUOffsetTRelative(inputslist[i])
            inputs = builder.EndVector()
        if self.outputs is not None:
            outputslist = []
            for i in range(len(self.outputs)):
                outputslist.append(self.outputs[i].Pack(builder))
            TaskTemplateStartOutputsVector(builder, len(self.outputs))
            for i in reversed(range(len(self.outputs))):
                builder.PrependUOffsetTRelative(outputslist[i])
            outputs = builder.EndVector()
        if self.deps is not None:
            deps = self.deps.Pack(builder)
        if self.graphReduce is not None:
            graphReduce = self.graphReduce.Pack(builder)
        if self.params is not None:
            params = self.params.Pack(builder)
        TaskTemplateStart(builder)
        if self.name is not None:
            TaskTemplateAddName(builder, name)
        TaskTemplateAddPlane(builder, self.plane)
        if self.kernel is not None:
            TaskTemplateAddKernel(builder, kernel)
        if self.domain is not None:
            TaskTemplateAddDomain(builder, domain)
        if self.inputs is not None:
            TaskTemplateAddInputs(builder, inputs)
        if self.outputs is not None:
            TaskTemplateAddOutputs(builder, outputs)
        if self.deps is not None:
            TaskTemplateAddDeps(builder, deps)
        TaskTemplateAddCoveredBoxesRef(builder, self.coveredBoxesRef)
        if self.graphReduce is not None:
            TaskTemplateAddGraphReduce(builder, graphReduce)
        TaskTemplateAddParamsType(builder, self.paramsType)
        if self.params is not None:
            TaskTemplateAddParams(builder, params)
        taskTemplate = TaskTemplateEnd(builder)
        return taskTemplate
