from __future__ import annotations

import flatbuffers
import numpy as np

import typing
from analysis.fb.AmrSubboxPackParams import AmrSubboxPackParamsT
from analysis.fb.CylindricalFluxParams import CylindricalFluxParamsT
from analysis.fb.DependencyRule import DependencyRule, DependencyRuleT
from analysis.fb.Domain import Domain, DomainT
from analysis.fb.ExecPlane import ExecPlane
from analysis.fb.FieldExprParams import FieldExprParamsT
from analysis.fb.FieldRef import FieldRef, FieldRefT
from analysis.fb.FiniteOnlyParams import FiniteOnlyParamsT
from analysis.fb.FluxSurfaceParams import FluxSurfaceParamsT
from analysis.fb.GradStencilParams import GradStencilParamsT
from analysis.fb.GraphReduceSpec import GraphReduceSpec, GraphReduceSpecT
from analysis.fb.Histogram1DParams import Histogram1DParamsT
from analysis.fb.Histogram2DParams import Histogram2DParamsT
from analysis.fb.KernelParams import KernelParams
from analysis.fb.OutputRef import OutputRef, OutputRefT
from analysis.fb.ParticleCicGridParams import ParticleCicGridParamsT
from analysis.fb.ParticleCicProjectionParams import ParticleCicProjectionParamsT
from analysis.fb.ParticleFieldParams import ParticleFieldParamsT
from analysis.fb.ParticleHistogramParams import ParticleHistogramParamsT
from analysis.fb.PlotfileLoadParams import PlotfileLoadParamsT
from analysis.fb.ScalarParams import ScalarParamsT
from analysis.fb.SliceFinalizeParams import SliceFinalizeParamsT
from analysis.fb.TopKModesParams import TopKModesParamsT
from analysis.fb.UniformProjectionParams import UniformProjectionParamsT
from analysis.fb.UniformSliceCellParams import UniformSliceCellParamsT
from analysis.fb.UniformSliceParams import UniformSliceParamsT
from analysis.fb.ValuesParams import ValuesParamsT
from flatbuffers import table

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class TaskTemplate(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> TaskTemplate: ...
  @classmethod
  def GetRootAsTaskTemplate(cls, buf: bytes, offset: int) -> TaskTemplate: ...
  @classmethod
  def TaskTemplateBufferHasIdentifier(cls, buf: bytes, offset: int, size_prefixed: bool) -> bool: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Name(self) -> str | None: ...
  def Plane(self) -> typing.Literal[ExecPlane.Chunk, ExecPlane.Graph, ExecPlane.Mixed]: ...
  def Kernel(self) -> str | None: ...
  def Domain(self) -> Domain | None: ...
  def Inputs(self, i: int) -> FieldRef | None: ...
  def InputsLength(self) -> int: ...
  def InputsIsNone(self) -> bool: ...
  def Outputs(self, i: int) -> OutputRef | None: ...
  def OutputsLength(self) -> int: ...
  def OutputsIsNone(self) -> bool: ...
  def Deps(self) -> DependencyRule | None: ...
  def CoveredBoxesRef(self) -> int: ...
  def GraphReduce(self) -> GraphReduceSpec | None: ...
  def ParamsType(self) -> typing.Literal[KernelParams.NONE, KernelParams.AmrSubboxPackParams, KernelParams.GradStencilParams, KernelParams.PlotfileLoadParams, KernelParams.FluxSurfaceParams, KernelParams.CylindricalFluxParams, KernelParams.UniformSliceCellParams, KernelParams.UniformProjectionParams, KernelParams.FieldExprParams, KernelParams.UniformSliceParams, KernelParams.Histogram1DParams, KernelParams.Histogram2DParams, KernelParams.ParticleFieldParams, KernelParams.ParticleCicGridParams, KernelParams.ParticleCicProjectionParams, KernelParams.ScalarParams, KernelParams.ValuesParams, KernelParams.FiniteOnlyParams, KernelParams.ParticleHistogramParams, KernelParams.TopKModesParams, KernelParams.SliceFinalizeParams]: ...
  def Params(self) -> table.Table | None: ...
class TaskTemplateT(object):
  name: str | None
  plane: typing.Literal[ExecPlane.Chunk, ExecPlane.Graph, ExecPlane.Mixed]
  kernel: str | None
  domain: DomainT | None
  inputs: typing.List[FieldRefT]
  outputs: typing.List[OutputRefT]
  deps: DependencyRuleT | None
  coveredBoxesRef: int
  graphReduce: GraphReduceSpecT | None
  paramsType: typing.Literal[KernelParams.NONE, KernelParams.AmrSubboxPackParams, KernelParams.GradStencilParams, KernelParams.PlotfileLoadParams, KernelParams.FluxSurfaceParams, KernelParams.CylindricalFluxParams, KernelParams.UniformSliceCellParams, KernelParams.UniformProjectionParams, KernelParams.FieldExprParams, KernelParams.UniformSliceParams, KernelParams.Histogram1DParams, KernelParams.Histogram2DParams, KernelParams.ParticleFieldParams, KernelParams.ParticleCicGridParams, KernelParams.ParticleCicProjectionParams, KernelParams.ScalarParams, KernelParams.ValuesParams, KernelParams.FiniteOnlyParams, KernelParams.ParticleHistogramParams, KernelParams.TopKModesParams, KernelParams.SliceFinalizeParams]
  params: typing.Union[None, AmrSubboxPackParamsT, GradStencilParamsT, PlotfileLoadParamsT, FluxSurfaceParamsT, CylindricalFluxParamsT, UniformSliceCellParamsT, UniformProjectionParamsT, FieldExprParamsT, UniformSliceParamsT, Histogram1DParamsT, Histogram2DParamsT, ParticleFieldParamsT, ParticleCicGridParamsT, ParticleCicProjectionParamsT, ScalarParamsT, ValuesParamsT, FiniteOnlyParamsT, ParticleHistogramParamsT, TopKModesParamsT, SliceFinalizeParamsT]
  def __init__(
    self,
    name: str | None = ...,
    plane: typing.Literal[ExecPlane.Chunk, ExecPlane.Graph, ExecPlane.Mixed] = ...,
    kernel: str | None = ...,
    domain: 'DomainT' | None = ...,
    inputs: typing.List['FieldRefT'] | None = ...,
    outputs: typing.List['OutputRefT'] | None = ...,
    deps: 'DependencyRuleT' | None = ...,
    coveredBoxesRef: int = ...,
    graphReduce: 'GraphReduceSpecT' | None = ...,
    paramsType: typing.Literal[KernelParams.NONE, KernelParams.AmrSubboxPackParams, KernelParams.GradStencilParams, KernelParams.PlotfileLoadParams, KernelParams.FluxSurfaceParams, KernelParams.CylindricalFluxParams, KernelParams.UniformSliceCellParams, KernelParams.UniformProjectionParams, KernelParams.FieldExprParams, KernelParams.UniformSliceParams, KernelParams.Histogram1DParams, KernelParams.Histogram2DParams, KernelParams.ParticleFieldParams, KernelParams.ParticleCicGridParams, KernelParams.ParticleCicProjectionParams, KernelParams.ScalarParams, KernelParams.ValuesParams, KernelParams.FiniteOnlyParams, KernelParams.ParticleHistogramParams, KernelParams.TopKModesParams, KernelParams.SliceFinalizeParams] = ...,
    params: typing.Union[None, AmrSubboxPackParamsT, GradStencilParamsT, PlotfileLoadParamsT, FluxSurfaceParamsT, CylindricalFluxParamsT, UniformSliceCellParamsT, UniformProjectionParamsT, FieldExprParamsT, UniformSliceParamsT, Histogram1DParamsT, Histogram2DParamsT, ParticleFieldParamsT, ParticleCicGridParamsT, ParticleCicProjectionParamsT, ScalarParamsT, ValuesParamsT, FiniteOnlyParamsT, ParticleHistogramParamsT, TopKModesParamsT, SliceFinalizeParamsT] = ...,
  ) -> None: ...
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> TaskTemplateT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> TaskTemplateT: ...
  @classmethod
  def InitFromObj(cls, taskTemplate: TaskTemplate) -> TaskTemplateT: ...
  def _UnPack(self, taskTemplate: TaskTemplate) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def TaskTemplateStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def TaskTemplateAddName(builder: flatbuffers.Builder, name: uoffset) -> None: ...
def TaskTemplateAddPlane(builder: flatbuffers.Builder, plane: typing.Literal[ExecPlane.Chunk, ExecPlane.Graph, ExecPlane.Mixed]) -> None: ...
def TaskTemplateAddKernel(builder: flatbuffers.Builder, kernel: uoffset) -> None: ...
def TaskTemplateAddDomain(builder: flatbuffers.Builder, domain: uoffset) -> None: ...
def TaskTemplateAddInputs(builder: flatbuffers.Builder, inputs: uoffset) -> None: ...
def TaskTemplateStartInputsVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartInputsVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def TaskTemplateAddOutputs(builder: flatbuffers.Builder, outputs: uoffset) -> None: ...
def TaskTemplateStartOutputsVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartOutputsVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def TaskTemplateAddDeps(builder: flatbuffers.Builder, deps: uoffset) -> None: ...
def TaskTemplateAddCoveredBoxesRef(builder: flatbuffers.Builder, coveredBoxesRef: int) -> None: ...
def TaskTemplateAddGraphReduce(builder: flatbuffers.Builder, graphReduce: uoffset) -> None: ...
def TaskTemplateAddParamsType(builder: flatbuffers.Builder, paramsType: typing.Literal[KernelParams.NONE, KernelParams.AmrSubboxPackParams, KernelParams.GradStencilParams, KernelParams.PlotfileLoadParams, KernelParams.FluxSurfaceParams, KernelParams.CylindricalFluxParams, KernelParams.UniformSliceCellParams, KernelParams.UniformProjectionParams, KernelParams.FieldExprParams, KernelParams.UniformSliceParams, KernelParams.Histogram1DParams, KernelParams.Histogram2DParams, KernelParams.ParticleFieldParams, KernelParams.ParticleCicGridParams, KernelParams.ParticleCicProjectionParams, KernelParams.ScalarParams, KernelParams.ValuesParams, KernelParams.FiniteOnlyParams, KernelParams.ParticleHistogramParams, KernelParams.TopKModesParams, KernelParams.SliceFinalizeParams]) -> None: ...
def TaskTemplateAddParams(builder: flatbuffers.Builder, params: uoffset) -> None: ...
def TaskTemplateEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

