from __future__ import annotations

import flatbuffers
import numpy as np

import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class TopKModesParams(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> TopKModesParams: ...
  @classmethod
  def GetRootAsTopKModesParams(cls, buf: bytes, offset: int) -> TopKModesParams: ...
  @classmethod
  def TopKModesParamsBufferHasIdentifier(cls, buf: bytes, offset: int, size_prefixed: bool) -> bool: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def K(self) -> int: ...
class TopKModesParamsT(object):
  k: int
  def __init__(
    self,
    k: int = ...,
  ) -> None: ...
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> TopKModesParamsT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> TopKModesParamsT: ...
  @classmethod
  def InitFromObj(cls, topKmodesParams: TopKModesParams) -> TopKModesParamsT: ...
  def _UnPack(self, topKmodesParams: TopKModesParams) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def TopKModesParamsStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def TopKModesParamsAddK(builder: flatbuffers.Builder, k: int) -> None: ...
def TopKModesParamsEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

