# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fb

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
np = import_numpy()

class TopKModesParams(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = TopKModesParams()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsTopKModesParams(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def TopKModesParamsBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x4B\x50\x4C\x4E", size_prefixed=size_prefixed)

    # TopKModesParams
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # TopKModesParams
    def K(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

def TopKModesParamsStart(builder: flatbuffers.Builder):
    builder.StartObject(1)

def Start(builder: flatbuffers.Builder):
    TopKModesParamsStart(builder)

def TopKModesParamsAddK(builder: flatbuffers.Builder, k: int):
    builder.PrependInt64Slot(0, k, 0)

def AddK(builder: flatbuffers.Builder, k: int):
    TopKModesParamsAddK(builder, k)

def TopKModesParamsEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return TopKModesParamsEnd(builder)


class TopKModesParamsT(object):

    # TopKModesParamsT
    def __init__(
        self,
        k = 0,
    ):
        self.k = k  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        topKmodesParams = TopKModesParams()
        topKmodesParams.Init(buf, pos)
        return cls.InitFromObj(topKmodesParams)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, topKmodesParams):
        x = TopKModesParamsT()
        x._UnPack(topKmodesParams)
        return x

    # TopKModesParamsT
    def _UnPack(self, topKmodesParams):
        if topKmodesParams is None:
            return
        self.k = topKmodesParams.K()

    # TopKModesParamsT
    def Pack(self, builder):
        TopKModesParamsStart(builder)
        TopKModesParamsAddK(builder, self.k)
        topKmodesParams = TopKModesParamsEnd(builder)
        return topKmodesParams
