from __future__ import annotations

import flatbuffers
import numpy as np

import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class UniformSliceCellParams(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> UniformSliceCellParams: ...
  @classmethod
  def GetRootAsUniformSliceCellParams(cls, buf: bytes, offset: int) -> UniformSliceCellParams: ...
  @classmethod
  def UniformSliceCellParamsBufferHasIdentifier(cls, buf: bytes, offset: int, size_prefixed: bool) -> bool: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Axis(self) -> int: ...
  def Coord(self) -> float: ...
  def PlaneIndex(self) -> int: ...
  def HasPlaneIndex(self) -> bool: ...
  def Rect(self, i: int) -> typing.List[float]: ...
  def RectAsNumpy(self) -> np.ndarray: ...
  def RectLength(self) -> int: ...
  def RectIsNone(self) -> bool: ...
  def Resolution(self, i: int) -> typing.List[int]: ...
  def ResolutionAsNumpy(self) -> np.ndarray: ...
  def ResolutionLength(self) -> int: ...
  def ResolutionIsNone(self) -> bool: ...
class UniformSliceCellParamsT(object):
  axis: int
  coord: float
  planeIndex: int
  hasPlaneIndex: bool
  rect: typing.List[float]
  resolution: typing.List[int]
  def __init__(
    self,
    axis: int = ...,
    coord: float = ...,
    planeIndex: int = ...,
    hasPlaneIndex: bool = ...,
    rect: typing.List[float] | None = ...,
    resolution: typing.List[int] | None = ...,
  ) -> None: ...
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> UniformSliceCellParamsT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> UniformSliceCellParamsT: ...
  @classmethod
  def InitFromObj(cls, uniformSliceCellParams: UniformSliceCellParams) -> UniformSliceCellParamsT: ...
  def _UnPack(self, uniformSliceCellParams: UniformSliceCellParams) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def UniformSliceCellParamsStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def UniformSliceCellParamsAddAxis(builder: flatbuffers.Builder, axis: int) -> None: ...
def UniformSliceCellParamsAddCoord(builder: flatbuffers.Builder, coord: float) -> None: ...
def UniformSliceCellParamsAddPlaneIndex(builder: flatbuffers.Builder, planeIndex: int) -> None: ...
def UniformSliceCellParamsAddHasPlaneIndex(builder: flatbuffers.Builder, hasPlaneIndex: bool) -> None: ...
def UniformSliceCellParamsAddRect(builder: flatbuffers.Builder, rect: uoffset) -> None: ...
def UniformSliceCellParamsStartRectVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartRectVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def UniformSliceCellParamsAddResolution(builder: flatbuffers.Builder, resolution: uoffset) -> None: ...
def UniformSliceCellParamsStartResolutionVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartResolutionVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def UniformSliceCellParamsEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

