# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fb

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
np = import_numpy()

class UniformSliceCellParams(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = UniformSliceCellParams()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsUniformSliceCellParams(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def UniformSliceCellParamsBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x4B\x50\x4C\x4E", size_prefixed=size_prefixed)

    # UniformSliceCellParams
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # UniformSliceCellParams
    def Axis(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 2

    # UniformSliceCellParams
    def Coord(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # UniformSliceCellParams
    def PlaneIndex(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # UniformSliceCellParams
    def HasPlaneIndex(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # UniformSliceCellParams
    def Rect(self, j: int):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Float64Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 8))
        return 0

    # UniformSliceCellParams
    def RectAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float64Flags, o)
        return 0

    # UniformSliceCellParams
    def RectLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # UniformSliceCellParams
    def RectIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        return o == 0

    # UniformSliceCellParams
    def Resolution(self, j: int):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # UniformSliceCellParams
    def ResolutionAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # UniformSliceCellParams
    def ResolutionLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # UniformSliceCellParams
    def ResolutionIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        return o == 0

def UniformSliceCellParamsStart(builder: flatbuffers.Builder):
    builder.StartObject(6)

def Start(builder: flatbuffers.Builder):
    UniformSliceCellParamsStart(builder)

def UniformSliceCellParamsAddAxis(builder: flatbuffers.Builder, axis: int):
    builder.PrependInt32Slot(0, axis, 2)

def AddAxis(builder: flatbuffers.Builder, axis: int):
    UniformSliceCellParamsAddAxis(builder, axis)

def UniformSliceCellParamsAddCoord(builder: flatbuffers.Builder, coord: float):
    builder.PrependFloat64Slot(1, coord, 0.0)

def AddCoord(builder: flatbuffers.Builder, coord: float):
    UniformSliceCellParamsAddCoord(builder, coord)

def UniformSliceCellParamsAddPlaneIndex(builder: flatbuffers.Builder, planeIndex: int):
    builder.PrependInt32Slot(2, planeIndex, 0)

def AddPlaneIndex(builder: flatbuffers.Builder, planeIndex: int):
    UniformSliceCellParamsAddPlaneIndex(builder, planeIndex)

def UniformSliceCellParamsAddHasPlaneIndex(builder: flatbuffers.Builder, hasPlaneIndex: bool):
    builder.PrependBoolSlot(3, hasPlaneIndex, 0)

def AddHasPlaneIndex(builder: flatbuffers.Builder, hasPlaneIndex: bool):
    UniformSliceCellParamsAddHasPlaneIndex(builder, hasPlaneIndex)

def UniformSliceCellParamsAddRect(builder: flatbuffers.Builder, rect: int):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(rect), 0)

def AddRect(builder: flatbuffers.Builder, rect: int):
    UniformSliceCellParamsAddRect(builder, rect)

def UniformSliceCellParamsStartRectVector(builder, numElems: int) -> int:
    return builder.StartVector(8, numElems, 8)

def StartRectVector(builder, numElems: int) -> int:
    return UniformSliceCellParamsStartRectVector(builder, numElems)

def UniformSliceCellParamsAddResolution(builder: flatbuffers.Builder, resolution: int):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(resolution), 0)

def AddResolution(builder: flatbuffers.Builder, resolution: int):
    UniformSliceCellParamsAddResolution(builder, resolution)

def UniformSliceCellParamsStartResolutionVector(builder, numElems: int) -> int:
    return builder.StartVector(4, numElems, 4)

def StartResolutionVector(builder, numElems: int) -> int:
    return UniformSliceCellParamsStartResolutionVector(builder, numElems)

def UniformSliceCellParamsEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return UniformSliceCellParamsEnd(builder)

try:
    from typing import List
except:
    pass

class UniformSliceCellParamsT(object):

    # UniformSliceCellParamsT
    def __init__(
        self,
        axis = 2,
        coord = 0.0,
        planeIndex = 0,
        hasPlaneIndex = False,
        rect = None,
        resolution = None,
    ):
        self.axis = axis  # type: int
        self.coord = coord  # type: float
        self.planeIndex = planeIndex  # type: int
        self.hasPlaneIndex = hasPlaneIndex  # type: bool
        self.rect = rect  # type: Optional[List[float]]
        self.resolution = resolution  # type: Optional[List[int]]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        uniformSliceCellParams = UniformSliceCellParams()
        uniformSliceCellParams.Init(buf, pos)
        return cls.InitFromObj(uniformSliceCellParams)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, uniformSliceCellParams):
        x = UniformSliceCellParamsT()
        x._UnPack(uniformSliceCellParams)
        return x

    # UniformSliceCellParamsT
    def _UnPack(self, uniformSliceCellParams):
        if uniformSliceCellParams is None:
            return
        self.axis = uniformSliceCellParams.Axis()
        self.coord = uniformSliceCellParams.Coord()
        self.planeIndex = uniformSliceCellParams.PlaneIndex()
        self.hasPlaneIndex = uniformSliceCellParams.HasPlaneIndex()
        if not uniformSliceCellParams.RectIsNone():
            if np is None:
                self.rect = []
                for i in range(uniformSliceCellParams.RectLength()):
                    self.rect.append(uniformSliceCellParams.Rect(i))
            else:
                self.rect = uniformSliceCellParams.RectAsNumpy()
        if not uniformSliceCellParams.ResolutionIsNone():
            if np is None:
                self.resolution = []
                for i in range(uniformSliceCellParams.ResolutionLength()):
                    self.resolution.append(uniformSliceCellParams.Resolution(i))
            else:
                self.resolution = uniformSliceCellParams.ResolutionAsNumpy()

    # UniformSliceCellParamsT
    def Pack(self, builder):
        if self.rect is not None:
            if np is not None and type(self.rect) is np.ndarray:
                rect = builder.CreateNumpyVector(self.rect)
            else:
                UniformSliceCellParamsStartRectVector(builder, len(self.rect))
                for i in reversed(range(len(self.rect))):
                    builder.PrependFloat64(self.rect[i])
                rect = builder.EndVector()
        if self.resolution is not None:
            if np is not None and type(self.resolution) is np.ndarray:
                resolution = builder.CreateNumpyVector(self.resolution)
            else:
                UniformSliceCellParamsStartResolutionVector(builder, len(self.resolution))
                for i in reversed(range(len(self.resolution))):
                    builder.PrependInt32(self.resolution[i])
                resolution = builder.EndVector()
        UniformSliceCellParamsStart(builder)
        UniformSliceCellParamsAddAxis(builder, self.axis)
        UniformSliceCellParamsAddCoord(builder, self.coord)
        UniformSliceCellParamsAddPlaneIndex(builder, self.planeIndex)
        UniformSliceCellParamsAddHasPlaneIndex(builder, self.hasPlaneIndex)
        if self.rect is not None:
            UniformSliceCellParamsAddRect(builder, rect)
        if self.resolution is not None:
            UniformSliceCellParamsAddResolution(builder, resolution)
        uniformSliceCellParams = UniformSliceCellParamsEnd(builder)
        return uniformSliceCellParams
