# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fb

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
np = import_numpy()

class UniformSliceParams(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = UniformSliceParams()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsUniformSliceParams(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def UniformSliceParamsBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x4B\x50\x4C\x4E", size_prefixed=size_prefixed)

    # UniformSliceParams
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # UniformSliceParams
    def Axis(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 2

    # UniformSliceParams
    def Coord(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # UniformSliceParams
    def Rect(self, j: int):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Float64Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 8))
        return 0

    # UniformSliceParams
    def RectAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float64Flags, o)
        return 0

    # UniformSliceParams
    def RectLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # UniformSliceParams
    def RectIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

    # UniformSliceParams
    def Resolution(self, j: int):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # UniformSliceParams
    def ResolutionAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # UniformSliceParams
    def ResolutionLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # UniformSliceParams
    def ResolutionIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        return o == 0

def UniformSliceParamsStart(builder: flatbuffers.Builder):
    builder.StartObject(4)

def Start(builder: flatbuffers.Builder):
    UniformSliceParamsStart(builder)

def UniformSliceParamsAddAxis(builder: flatbuffers.Builder, axis: int):
    builder.PrependInt32Slot(0, axis, 2)

def AddAxis(builder: flatbuffers.Builder, axis: int):
    UniformSliceParamsAddAxis(builder, axis)

def UniformSliceParamsAddCoord(builder: flatbuffers.Builder, coord: float):
    builder.PrependFloat64Slot(1, coord, 0.0)

def AddCoord(builder: flatbuffers.Builder, coord: float):
    UniformSliceParamsAddCoord(builder, coord)

def UniformSliceParamsAddRect(builder: flatbuffers.Builder, rect: int):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(rect), 0)

def AddRect(builder: flatbuffers.Builder, rect: int):
    UniformSliceParamsAddRect(builder, rect)

def UniformSliceParamsStartRectVector(builder, numElems: int) -> int:
    return builder.StartVector(8, numElems, 8)

def StartRectVector(builder, numElems: int) -> int:
    return UniformSliceParamsStartRectVector(builder, numElems)

def UniformSliceParamsAddResolution(builder: flatbuffers.Builder, resolution: int):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(resolution), 0)

def AddResolution(builder: flatbuffers.Builder, resolution: int):
    UniformSliceParamsAddResolution(builder, resolution)

def UniformSliceParamsStartResolutionVector(builder, numElems: int) -> int:
    return builder.StartVector(4, numElems, 4)

def StartResolutionVector(builder, numElems: int) -> int:
    return UniformSliceParamsStartResolutionVector(builder, numElems)

def UniformSliceParamsEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return UniformSliceParamsEnd(builder)

try:
    from typing import List
except:
    pass

class UniformSliceParamsT(object):

    # UniformSliceParamsT
    def __init__(
        self,
        axis = 2,
        coord = 0.0,
        rect = None,
        resolution = None,
    ):
        self.axis = axis  # type: int
        self.coord = coord  # type: float
        self.rect = rect  # type: Optional[List[float]]
        self.resolution = resolution  # type: Optional[List[int]]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        uniformSliceParams = UniformSliceParams()
        uniformSliceParams.Init(buf, pos)
        return cls.InitFromObj(uniformSliceParams)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, uniformSliceParams):
        x = UniformSliceParamsT()
        x._UnPack(uniformSliceParams)
        return x

    # UniformSliceParamsT
    def _UnPack(self, uniformSliceParams):
        if uniformSliceParams is None:
            return
        self.axis = uniformSliceParams.Axis()
        self.coord = uniformSliceParams.Coord()
        if not uniformSliceParams.RectIsNone():
            if np is None:
                self.rect = []
                for i in range(uniformSliceParams.RectLength()):
                    self.rect.append(uniformSliceParams.Rect(i))
            else:
                self.rect = uniformSliceParams.RectAsNumpy()
        if not uniformSliceParams.ResolutionIsNone():
            if np is None:
                self.resolution = []
                for i in range(uniformSliceParams.ResolutionLength()):
                    self.resolution.append(uniformSliceParams.Resolution(i))
            else:
                self.resolution = uniformSliceParams.ResolutionAsNumpy()

    # UniformSliceParamsT
    def Pack(self, builder):
        if self.rect is not None:
            if np is not None and type(self.rect) is np.ndarray:
                rect = builder.CreateNumpyVector(self.rect)
            else:
                UniformSliceParamsStartRectVector(builder, len(self.rect))
                for i in reversed(range(len(self.rect))):
                    builder.PrependFloat64(self.rect[i])
                rect = builder.EndVector()
        if self.resolution is not None:
            if np is not None and type(self.resolution) is np.ndarray:
                resolution = builder.CreateNumpyVector(self.resolution)
            else:
                UniformSliceParamsStartResolutionVector(builder, len(self.resolution))
                for i in reversed(range(len(self.resolution))):
                    builder.PrependInt32(self.resolution[i])
                resolution = builder.EndVector()
        UniformSliceParamsStart(builder)
        UniformSliceParamsAddAxis(builder, self.axis)
        UniformSliceParamsAddCoord(builder, self.coord)
        if self.rect is not None:
            UniformSliceParamsAddRect(builder, rect)
        if self.resolution is not None:
            UniformSliceParamsAddResolution(builder, resolution)
        uniformSliceParams = UniformSliceParamsEnd(builder)
        return uniformSliceParams
