from __future__ import annotations

import flatbuffers
import numpy as np

import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class UniformProjectionParams(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> UniformProjectionParams: ...
  @classmethod
  def GetRootAsUniformProjectionParams(cls, buf: bytes, offset: int) -> UniformProjectionParams: ...
  @classmethod
  def UniformProjectionParamsBufferHasIdentifier(cls, buf: bytes, offset: int, size_prefixed: bool) -> bool: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Axis(self) -> int: ...
  def AxisBounds(self, i: int) -> typing.List[float]: ...
  def AxisBoundsAsNumpy(self) -> np.ndarray: ...
  def AxisBoundsLength(self) -> int: ...
  def AxisBoundsIsNone(self) -> bool: ...
  def Rect(self, i: int) -> typing.List[float]: ...
  def RectAsNumpy(self) -> np.ndarray: ...
  def RectLength(self) -> int: ...
  def RectIsNone(self) -> bool: ...
  def Resolution(self, i: int) -> typing.List[int]: ...
  def ResolutionAsNumpy(self) -> np.ndarray: ...
  def ResolutionLength(self) -> int: ...
  def ResolutionIsNone(self) -> bool: ...
class UniformProjectionParamsT(object):
  axis: int
  axisBounds: typing.List[float]
  rect: typing.List[float]
  resolution: typing.List[int]
  def __init__(
    self,
    axis: int = ...,
    axisBounds: typing.List[float] | None = ...,
    rect: typing.List[float] | None = ...,
    resolution: typing.List[int] | None = ...,
  ) -> None: ...
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> UniformProjectionParamsT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> UniformProjectionParamsT: ...
  @classmethod
  def InitFromObj(cls, uniformProjectionParams: UniformProjectionParams) -> UniformProjectionParamsT: ...
  def _UnPack(self, uniformProjectionParams: UniformProjectionParams) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def UniformProjectionParamsStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def UniformProjectionParamsAddAxis(builder: flatbuffers.Builder, axis: int) -> None: ...
def UniformProjectionParamsAddAxisBounds(builder: flatbuffers.Builder, axisBounds: uoffset) -> None: ...
def UniformProjectionParamsStartAxisBoundsVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartAxisBoundsVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def UniformProjectionParamsAddRect(builder: flatbuffers.Builder, rect: uoffset) -> None: ...
def UniformProjectionParamsStartRectVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartRectVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def UniformProjectionParamsAddResolution(builder: flatbuffers.Builder, resolution: uoffset) -> None: ...
def UniformProjectionParamsStartResolutionVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartResolutionVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def UniformProjectionParamsEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

