from __future__ import annotations

import flatbuffers
import numpy as np

import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class UniformSliceParams(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> UniformSliceParams: ...
  @classmethod
  def GetRootAsUniformSliceParams(cls, buf: bytes, offset: int) -> UniformSliceParams: ...
  @classmethod
  def UniformSliceParamsBufferHasIdentifier(cls, buf: bytes, offset: int, size_prefixed: bool) -> bool: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Axis(self) -> int: ...
  def Coord(self) -> float: ...
  def Rect(self, i: int) -> typing.List[float]: ...
  def RectAsNumpy(self) -> np.ndarray: ...
  def RectLength(self) -> int: ...
  def RectIsNone(self) -> bool: ...
  def Resolution(self, i: int) -> typing.List[int]: ...
  def ResolutionAsNumpy(self) -> np.ndarray: ...
  def ResolutionLength(self) -> int: ...
  def ResolutionIsNone(self) -> bool: ...
class UniformSliceParamsT(object):
  axis: int
  coord: float
  rect: typing.List[float]
  resolution: typing.List[int]
  def __init__(
    self,
    axis: int = ...,
    coord: float = ...,
    rect: typing.List[float] | None = ...,
    resolution: typing.List[int] | None = ...,
  ) -> None: ...
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> UniformSliceParamsT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> UniformSliceParamsT: ...
  @classmethod
  def InitFromObj(cls, uniformSliceParams: UniformSliceParams) -> UniformSliceParamsT: ...
  def _UnPack(self, uniformSliceParams: UniformSliceParams) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def UniformSliceParamsStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def UniformSliceParamsAddAxis(builder: flatbuffers.Builder, axis: int) -> None: ...
def UniformSliceParamsAddCoord(builder: flatbuffers.Builder, coord: float) -> None: ...
def UniformSliceParamsAddRect(builder: flatbuffers.Builder, rect: uoffset) -> None: ...
def UniformSliceParamsStartRectVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartRectVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def UniformSliceParamsAddResolution(builder: flatbuffers.Builder, resolution: uoffset) -> None: ...
def UniformSliceParamsStartResolutionVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartResolutionVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def UniformSliceParamsEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

