# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fb

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
np = import_numpy()

class UniformProjectionParams(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = UniformProjectionParams()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsUniformProjectionParams(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def UniformProjectionParamsBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x4B\x50\x4C\x4E", size_prefixed=size_prefixed)

    # UniformProjectionParams
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # UniformProjectionParams
    def Axis(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 2

    # UniformProjectionParams
    def AxisBounds(self, j: int):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Float64Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 8))
        return 0

    # UniformProjectionParams
    def AxisBoundsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float64Flags, o)
        return 0

    # UniformProjectionParams
    def AxisBoundsLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # UniformProjectionParams
    def AxisBoundsIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

    # UniformProjectionParams
    def Rect(self, j: int):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Float64Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 8))
        return 0

    # UniformProjectionParams
    def RectAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float64Flags, o)
        return 0

    # UniformProjectionParams
    def RectLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # UniformProjectionParams
    def RectIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

    # UniformProjectionParams
    def Resolution(self, j: int):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # UniformProjectionParams
    def ResolutionAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # UniformProjectionParams
    def ResolutionLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # UniformProjectionParams
    def ResolutionIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        return o == 0

def UniformProjectionParamsStart(builder: flatbuffers.Builder):
    builder.StartObject(4)

def Start(builder: flatbuffers.Builder):
    UniformProjectionParamsStart(builder)

def UniformProjectionParamsAddAxis(builder: flatbuffers.Builder, axis: int):
    builder.PrependInt32Slot(0, axis, 2)

def AddAxis(builder: flatbuffers.Builder, axis: int):
    UniformProjectionParamsAddAxis(builder, axis)

def UniformProjectionParamsAddAxisBounds(builder: flatbuffers.Builder, axisBounds: int):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(axisBounds), 0)

def AddAxisBounds(builder: flatbuffers.Builder, axisBounds: int):
    UniformProjectionParamsAddAxisBounds(builder, axisBounds)

def UniformProjectionParamsStartAxisBoundsVector(builder, numElems: int) -> int:
    return builder.StartVector(8, numElems, 8)

def StartAxisBoundsVector(builder, numElems: int) -> int:
    return UniformProjectionParamsStartAxisBoundsVector(builder, numElems)

def UniformProjectionParamsAddRect(builder: flatbuffers.Builder, rect: int):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(rect), 0)

def AddRect(builder: flatbuffers.Builder, rect: int):
    UniformProjectionParamsAddRect(builder, rect)

def UniformProjectionParamsStartRectVector(builder, numElems: int) -> int:
    return builder.StartVector(8, numElems, 8)

def StartRectVector(builder, numElems: int) -> int:
    return UniformProjectionParamsStartRectVector(builder, numElems)

def UniformProjectionParamsAddResolution(builder: flatbuffers.Builder, resolution: int):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(resolution), 0)

def AddResolution(builder: flatbuffers.Builder, resolution: int):
    UniformProjectionParamsAddResolution(builder, resolution)

def UniformProjectionParamsStartResolutionVector(builder, numElems: int) -> int:
    return builder.StartVector(4, numElems, 4)

def StartResolutionVector(builder, numElems: int) -> int:
    return UniformProjectionParamsStartResolutionVector(builder, numElems)

def UniformProjectionParamsEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return UniformProjectionParamsEnd(builder)

try:
    from typing import List
except:
    pass

class UniformProjectionParamsT(object):

    # UniformProjectionParamsT
    def __init__(
        self,
        axis = 2,
        axisBounds = None,
        rect = None,
        resolution = None,
    ):
        self.axis = axis  # type: int
        self.axisBounds = axisBounds  # type: Optional[List[float]]
        self.rect = rect  # type: Optional[List[float]]
        self.resolution = resolution  # type: Optional[List[int]]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        uniformProjectionParams = UniformProjectionParams()
        uniformProjectionParams.Init(buf, pos)
        return cls.InitFromObj(uniformProjectionParams)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, uniformProjectionParams):
        x = UniformProjectionParamsT()
        x._UnPack(uniformProjectionParams)
        return x

    # UniformProjectionParamsT
    def _UnPack(self, uniformProjectionParams):
        if uniformProjectionParams is None:
            return
        self.axis = uniformProjectionParams.Axis()
        if not uniformProjectionParams.AxisBoundsIsNone():
            if np is None:
                self.axisBounds = []
                for i in range(uniformProjectionParams.AxisBoundsLength()):
                    self.axisBounds.append(uniformProjectionParams.AxisBounds(i))
            else:
                self.axisBounds = uniformProjectionParams.AxisBoundsAsNumpy()
        if not uniformProjectionParams.RectIsNone():
            if np is None:
                self.rect = []
                for i in range(uniformProjectionParams.RectLength()):
                    self.rect.append(uniformProjectionParams.Rect(i))
            else:
                self.rect = uniformProjectionParams.RectAsNumpy()
        if not uniformProjectionParams.ResolutionIsNone():
            if np is None:
                self.resolution = []
                for i in range(uniformProjectionParams.ResolutionLength()):
                    self.resolution.append(uniformProjectionParams.Resolution(i))
            else:
                self.resolution = uniformProjectionParams.ResolutionAsNumpy()

    # UniformProjectionParamsT
    def Pack(self, builder):
        if self.axisBounds is not None:
            if np is not None and type(self.axisBounds) is np.ndarray:
                axisBounds = builder.CreateNumpyVector(self.axisBounds)
            else:
                UniformProjectionParamsStartAxisBoundsVector(builder, len(self.axisBounds))
                for i in reversed(range(len(self.axisBounds))):
                    builder.PrependFloat64(self.axisBounds[i])
                axisBounds = builder.EndVector()
        if self.rect is not None:
            if np is not None and type(self.rect) is np.ndarray:
                rect = builder.CreateNumpyVector(self.rect)
            else:
                UniformProjectionParamsStartRectVector(builder, len(self.rect))
                for i in reversed(range(len(self.rect))):
                    builder.PrependFloat64(self.rect[i])
                rect = builder.EndVector()
        if self.resolution is not None:
            if np is not None and type(self.resolution) is np.ndarray:
                resolution = builder.CreateNumpyVector(self.resolution)
            else:
                UniformProjectionParamsStartResolutionVector(builder, len(self.resolution))
                for i in reversed(range(len(self.resolution))):
                    builder.PrependInt32(self.resolution[i])
                resolution = builder.EndVector()
        UniformProjectionParamsStart(builder)
        UniformProjectionParamsAddAxis(builder, self.axis)
        if self.axisBounds is not None:
            UniformProjectionParamsAddAxisBounds(builder, axisBounds)
        if self.rect is not None:
            UniformProjectionParamsAddRect(builder, rect)
        if self.resolution is not None:
            UniformProjectionParamsAddResolution(builder, resolution)
        uniformProjectionParams = UniformProjectionParamsEnd(builder)
        return uniformProjectionParams
