# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fb

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
np = import_numpy()

class ValuesParams(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ValuesParams()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsValuesParams(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def ValuesParamsBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x4B\x50\x4C\x4E", size_prefixed=size_prefixed)

    # ValuesParams
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ValuesParams
    def Values(self, j: int):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Float64Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 8))
        return 0

    # ValuesParams
    def ValuesAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float64Flags, o)
        return 0

    # ValuesParams
    def ValuesLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ValuesParams
    def ValuesIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def ValuesParamsStart(builder: flatbuffers.Builder):
    builder.StartObject(1)

def Start(builder: flatbuffers.Builder):
    ValuesParamsStart(builder)

def ValuesParamsAddValues(builder: flatbuffers.Builder, values: int):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(values), 0)

def AddValues(builder: flatbuffers.Builder, values: int):
    ValuesParamsAddValues(builder, values)

def ValuesParamsStartValuesVector(builder, numElems: int) -> int:
    return builder.StartVector(8, numElems, 8)

def StartValuesVector(builder, numElems: int) -> int:
    return ValuesParamsStartValuesVector(builder, numElems)

def ValuesParamsEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return ValuesParamsEnd(builder)

try:
    from typing import List
except:
    pass

class ValuesParamsT(object):

    # ValuesParamsT
    def __init__(
        self,
        values = None,
    ):
        self.values = values  # type: Optional[List[float]]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        valuesParams = ValuesParams()
        valuesParams.Init(buf, pos)
        return cls.InitFromObj(valuesParams)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, valuesParams):
        x = ValuesParamsT()
        x._UnPack(valuesParams)
        return x

    # ValuesParamsT
    def _UnPack(self, valuesParams):
        if valuesParams is None:
            return
        if not valuesParams.ValuesIsNone():
            if np is None:
                self.values = []
                for i in range(valuesParams.ValuesLength()):
                    self.values.append(valuesParams.Values(i))
            else:
                self.values = valuesParams.ValuesAsNumpy()

    # ValuesParamsT
    def Pack(self, builder):
        if self.values is not None:
            if np is not None and type(self.values) is np.ndarray:
                values = builder.CreateNumpyVector(self.values)
            else:
                ValuesParamsStartValuesVector(builder, len(self.values))
                for i in reversed(range(len(self.values))):
                    builder.PrependFloat64(self.values[i])
                values = builder.EndVector()
        ValuesParamsStart(builder)
        if self.values is not None:
            ValuesParamsAddValues(builder, values)
        valuesParams = ValuesParamsEnd(builder)
        return valuesParams
