from __future__ import annotations

import flatbuffers
import numpy as np

import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class ValuesParams(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> ValuesParams: ...
  @classmethod
  def GetRootAsValuesParams(cls, buf: bytes, offset: int) -> ValuesParams: ...
  @classmethod
  def ValuesParamsBufferHasIdentifier(cls, buf: bytes, offset: int, size_prefixed: bool) -> bool: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Values(self, i: int) -> typing.List[float]: ...
  def ValuesAsNumpy(self) -> np.ndarray: ...
  def ValuesLength(self) -> int: ...
  def ValuesIsNone(self) -> bool: ...
class ValuesParamsT(object):
  values: typing.List[float]
  def __init__(
    self,
    values: typing.List[float] | None = ...,
  ) -> None: ...
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> ValuesParamsT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> ValuesParamsT: ...
  @classmethod
  def InitFromObj(cls, valuesParams: ValuesParams) -> ValuesParamsT: ...
  def _UnPack(self, valuesParams: ValuesParams) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def ValuesParamsStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def ValuesParamsAddValues(builder: flatbuffers.Builder, values: uoffset) -> None: ...
def ValuesParamsStartValuesVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartValuesVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def ValuesParamsEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

